### ISSUE TITLE
Restrictive layer help text

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1013]
Write inn-app help text for restrictive layer. 

[Google Doc](https://docs.google.com/document/d/1Dg6jQf_bhgxgx20SUeL9ozVPZeX9aWE7fo1DmLOGQmw/edit#heading=h.7j133c6dhgat)

```[tasklist]
### Tasks
- [x] Laura writes
- [ ] Courtney Reviews
- [x] Paul Reviews
```

**Comment by hamriclr** [comment]
@CourtneyLee333 Drafted here: https://docs.google.com/document/d/1Dg6jQf_bhgxgx20SUeL9ozVPZeX9aWE7fo1DmLOGQmw/edit

I also included revisions to the other 3 help text docs you asked me to review in that document.
