### ISSUE TITLE
Design signifier(s) for actions can't be accomplished while offline

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1021]
Design the UI to communicate to users that actions are not available offline. Options include:
- [ ] Disabled state for buttons
- [ ] Not available offline notification 
- [ ] Tooltips

**General rule** 
- As a user, I should understand if an action is not available to me while offline
(alternate framing: I should not be confused why the app isn't doing something I tell to do because of an offline state)

## Acceptance Criteria
- [x] work with Derek to decide not-available-offline strategy. 
- [x] Design the experiences critical for launch. 
    - [ ] Disable basemap icon button
    - [ ] Disabled state - standard button components
    - [ ] "Not available offline" notification 

[Figma page: Offline Use](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9314-5129&t=dRYCWQbJocQLLQWk-1)

**Comment by CourtneyLee333** [comment]
@DerekCaelin In the Figma link above you can see my first round of design and notes. I've only included screens that will need edits for the offline experience, with the expectation that all other screens will work as normal. Please review, and let me know if you want to discuss.
