### ISSUE TITLE
Update Edit Depth form design to use InfoSheet component

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#1027]

**Comment by CourtneyLee333** [comment]
@DerekCaelin FYI this issue exists, and should have an implementation counterpart. Not a high pri, but it is part of our component work that was deferred when Ruxandra did the rest of the InfoSheet work.

**Comment by CourtneyLee333** [comment]
@tm-ruxandra I clearly did a terrible job providing details on this issue and now I don't know which piece we were talking about. Do you? I assume it's one of these:

- Data collector view of the UI to change the depths (NRCS, BLM, or custom)
- Project manager view of the same 
- Data collector view of the 3 dot iconbutton for each depth (switch on and off inputs)

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 "Edit Depth Modal" / "Depth Editor" in the code refers to the interface activated by the 3-dot iconbutton on each site depth, so I'd assume that's what this ticket was originally referring to.

**Comment by CourtneyLee333** [comment]
@tm-ruxandra Thank you! It looks to me like the implementation uses the InfoSheet component already. Can you validate that?

**Comment by CourtneyLee333** [comment]
I'm really not sure. Closing this for now and we can re-open if the need arises.
