### ISSUE TITLE
Finalize restrictive layer design

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#1029]
[Final Design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9963-20243&t=ufBRd9aPF7qLWfIr-1)

**Comment by DerekCaelin** [comment]
@CourtneyLee333 do you see there being any changes to restrictive layers at this stage, or is the design ready for developers?

**Comment by CourtneyLee333** [comment]
I have some small decisions to make before being 100% ready to hand it off. Nothing that will affect engineering size or scope.
