### ISSUE TITLE
Design autosave signifiers for Terraso storymaps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1035]
Design UI changes for Terraso story maps auto save feature. See parent issue techmatters/terraso-product#1034 for details.

## References
[Product spec](https://docs.google.com/document/d/1OJoFjGDbmhdaxydYEhyeLkSm8PM76VVO5gXUrQRgoQA/edit)

[Figma section](https://www.figma.com/design/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?node-id=2637-745&t=iSelGwxoxewQXAHM-1)

Note from Jose: "offline is not an error: it's an expected state"

## Acceptance criteria
- [x] Remove “Save draft” button
- [ ] Signifier:
   - [ ] progress indicator
   - [ ] save complete
   - [ ] save failed
   - [ ] you’re offline
- [ ] Convey to user that they are autosaving a draft, need to hit publish/update(?) to push changes
- [ ] Convey to user that preview goes to previewing draft (not published)

**Comment by CourtneyLee333** [comment]
@DerekCaelin This is ready for your review. On the top row of the section you'll find my preferred design set. The second row shows 3 alternative placements of the new messaging.

**Comment by DerekCaelin** [comment]
Thanks @CourtneyLee333! This looks great to me. Two questions:
- Do we need to specify "Saved _to Terraso_?". Would it be simpler to say "Saved"?
- My understanding of snackbar notifications is that they are inherently temporary. Are there consequences for having a persistent snack bar (e.g., other error messages wont be able to display)?  I wonder if having the persistent `Trying to connect...` notification is enough.

**Comment by DerekCaelin** [comment]
@josebui would you take a look at the top row of designs in [Figma](https://www.figma.com/design/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?node-id=2637-745&t=iSelGwxoxewQXAHM-1) and provide comments, please?

**Comment by DerekCaelin** [comment]
Jose and paul provided comments [in slack](https://tech-matters.slack.com/archives/C05B4U4L413/p1727709726552199?thread_ts=1727449212.160739&cid=C05B4U4L413)
