### ISSUE TITLE
File bug reports for 4 types of soil ID crashes

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1036]
In a recent test of soil ID, @shrouxm identified 4 types of crashes. document the 4 crash types and submit to Jon.

**Comment by shrouxm** [comment]
@DerekCaelin finally (:weary:) did this:
- https://github.com/techmatters/soil-id-algorithm/issues/183
- https://github.com/techmatters/soil-id-algorithm/issues/184
- https://github.com/techmatters/soil-id-algorithm/issues/185
- https://github.com/techmatters/soil-id-algorithm/issues/186
- https://github.com/techmatters/soil-id-algorithm/issues/187
