### ISSUE TITLE
Make outline of website updates

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#1049]
- Rework Hubspot support forms to be embedded in the website pages, or to have LandPKS branding
- Home page needs more sales pitch content
- Create new page for Partners - describe what partnership means, CTA to become a partner. Move most of the logos there. 
- Create new About section - history, team
- Add Hubspot usability testing form to website
- template for article/resource
- template for blog post/news

**Comment by CourtneyLee333** [comment]
@DerekCaelin Since we didn't discuss this at the marketing meeting yesterday, will you review the outline and let me know if you think we need to meet about it?

**Comment by DerekCaelin** [comment]
These look good to me. I'll split them out into issues.
