### ISSUE TITLE
Design error notification

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1064]
Design a temporary notification for the user when an error occurs, eg:
- user is trying to sync data for a site that has been deleted

Carissa recommends a "toast" which appears to be like a web based "snack bar"

[Figma design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8336-11349&t=j7UZC87Cr0SzZXaA-1)

**Comment by CourtneyLee333** [comment]
I've combined this with https://github.com/techmatters/terraso-product/issues/1021

**Comment by DerekCaelin** [comment]
We're bringing it back!

**Comment by CourtneyLee333** [comment]
@DerekCaelin @knipec I'm wondering what the scope of this task is. Are you just wanting the component to use? Are you looking for a generic message that can be used in all instances of error? Do you want me to create specific messaging for every kind of error that might happen?

**Comment by DerekCaelin** [comment]
@CourtneyLee333 the specific goal is to decide how to notify to the user if there is an error in syncing (such as site no longer exists, or site has been moved and user doesn't have permissions). @knipec recommends a "toast" notification. 

We could expand the scope a little to think about _unexpected_ error messages in general. The toast could be a way to expose to the user that something has gone wrong.

**Comment by knipec** [comment]
@DerekCaelin @CourtneyLee333 
The scope I’m imagining for this task is:
- Design the error messaging experience for scenarios like these:
  - I am viewing a screen that requires data (e.g., site, site note, project), data got deleted, then I pull
  - I am viewing a screen that requires permissions, permissions got revoked, then I pull
  - I make an online edit to a project that got deleted
  - I make an online edit to a site that I no longer have permissions to edit
  - I make a bunch of offline soil data edits to sites, then return online and push. Some sites were deleted, others revoked my edit permissions, and some accept my edits.
- In these scenarios, I’d want to know:
  - The text
  - The visual design of the snackbar (or however we display the message)

Non-goal: There is other error handling that it would be nice to do, but I’m imagining that as out of scope for this task, and instead part of the unplanned #902 

Let me know if that sounds right to you!
(Side note: I have been using "toast" and "snackbar" interchangeably but I can standardize on "snackbar" 😄)
