### ISSUE TITLE
Research - revise names listed in required inputs and soil tabs?

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1079]
Currently we use the same name for inputs on the required inputs list and the inputs listed on the soil tab. Is the use of the word "Soil" redundant in the context of the soil tab? Should we name things differently on the required data inputs list and the soil tab? EG ("Soil Color" on required data inputs and "Color" on the soils tab).

## Conclusion
- maintain the use of "Soil", even if redundant. 

<img width="172" alt="image" src="https://github.com/user-attachments/assets/cdc42a8a-ef28-41ac-913a-d121cdcef11f"> 
<img width="172" alt="image" src="https://github.com/user-attachments/assets/dbd45c9f-2bef-423f-be29-8db697a3723b">

## Acceptance Criteria
- [x] reflect on current design and decide whether an update is requred

 (If so, Derek will create a user story to update the designs and implement the new designs).

**Comment by CourtneyLee333** [comment]
@DerekCaelin The redundancy doesn't bother me, and I'd say there is a decent case for the word "soil" being helpful in this context. Since it's already implemented with one string for each input that gets pulled in the various places, let's leave it until we have a good reason to make a change. I like consistency.

**Comment by DerekCaelin** [comment]
Sounds good to me. FYI @paulschreiber

**Comment by DerekCaelin** [comment]
Courtney, re: this issue: https://github.com/techmatters/terraso-mobile-client/issues/2225

Should we call the `Soil Texture` observation `Soil Texture Class`?
