### ISSUE TITLE
Design update soil cracks screen with new help text

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1085]
Design updates to "vertical cracks" screen, now to be a "soil cracks" screen. See parent issue for details

[The Figma design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10684-12570&t=uo9cXOrs8JuPv4SD-1)

## References
[Jon-approved help text](https://docs.google.com/document/d/145VxZJnB05EM3dmK3plDqdIjRseXLBnsoPAw8kVp140/edit)

## Acceptance criteria
- [x] Title: "Vertical Cracking" to "Soil Cracks"
- [x] New menu options and help text

**Comment by CourtneyLee333** [comment]
@DerekCaelin ready for your review.

**Comment by DerekCaelin** [comment]
Looks good to me!
