### ISSUE TITLE
Courtney Help Documentation Section

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1104]
- [x] Merge "accessing sites" with "creating sites" and "site dashboard" as appropriate
- [x] Move User Roles to Projects section. And hook up projects section to main page.
- [x] Separate out the inputs from the Sites section
- [x]  Organize content around Site Management, Project Management, Data Collection, Soil ID, LCC, etc...

**Comment by CourtneyLee333** [comment]
I did this yesterday :p
