### ISSUE TITLE
Design template for blog post / news

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1110]
See parent task for details

## References
https://github.com/techmatters/terraso-product/issues/1049

**Comment by CourtneyLee333** [comment]
@DerekCaelin I got [this template](https://landpks.terraso.org/?p=2012&preview=true&_thumbnail_id=2140) ready for your review. I still need to write up instructions on using it, but it's pretty straightforward.

**Comment by DerekCaelin** [comment]
Wow. So pretty. I love it.
