### ISSUE TITLE
Review create site design with offline in mind

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1138]
How, if at all, should the design of the "create site" experience change while the user is offline. 

The happy path:

If I create a site offline and add it to a project at that time, the project should be cached already so that my site can inherit the project specs. 

If I create a site offline and do not add it to a project at that time, and then add it to the project later while still offline, I will get the warning that it might delete my data. 

### Design
Figma [Offline Use - Site Creation is possible](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=11024-4381&t=9D6C2SWplVycv1tw-1)

**Comment by CourtneyLee333** [comment]
Waiting for decisions to be made in the spec re: adding to project.

**Comment by CourtneyLee333** [comment]
@DerekCaelin I think I've covered everything. Do you see anything missing?
