### ISSUE TITLE
Terminology Updates - Delete Project dialog

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1150]
Make updates to the Delete project dialog box.

## Design 
![image](https://github.com/user-attachments/assets/dfa6ada5-5117-442d-94bd-afbe97255489)
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10731-12928&node-type=frame&t=Qqa0NUYJwdrkxrVV-0)

## Acceptance Criteria
- [x] `its sites' data` -> `its sites' observations`
- [x] `keep site data` -> `keep site observations`

**Comment by paulschreiber** [comment]
Please verify in 209 or later.
