### ISSUE TITLE
Revisit design: download project data

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1157]
Review current design for downloading project data and update based on new learnings. View parent issue for details.

## References
- [Spec - Download Project Data](https://docs.google.com/document/d/17xM6DCmC7VoSyf7IGNsBEiRmbu4JaEt0HaVLSUxBcI4/edit#heading=h.50oo5lmvaphd) 
- [Spec - Project management](https://docs.google.com/document/d/1Mo54pX4gbn0GWJfTOOvjA7TB41AgHOKYxEMSKtm3dOM/edit)
- [Terraso web client download page](https://www.figma.com/file/THhEUPoklhvtHQHUKTo8XB/Terraso_Hi-fi-ALL?type=design&node-id=2253-1959&mode=design&t=Dsjbs6TgokuEy6zB-0)
- [Terraso - share public link documentaiton](https://github.com/techmatters/terraso-web-client/issues/1322)

## Designs
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13002&mode=design&t=YHeqcffux9COXQxs-0)
#### Design as of 4/23/2024 - please see figma for most up-to-date version
<img src="https://github.com/techmatters/terraso-product/assets/10799815/6b541df8-f43e-4ed0-9437-cdb95844267d" width="200px">

## Acceptance Critieria
- [ ] Review older design and decide whether it needs to be updated.
- [ ] Update design as needed
- [ ] Feedback from co-design partners

**Comment by CourtneyLee333** [comment]
Waiting for decisions to be made in the spec.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 please review and update the design you created:

<img src="https://github.com/techmatters/terraso-product/assets/10799815/6b541df8-f43e-4ed0-9437-cdb95844267d" width="200px">

Please bear in mind: 
- We will be generating a URL to download the file
- For MVP file will be a CSV, not a ZIP
- Paul suggests not simply copying a download link to clipboard but initiating a "share" experience where people choose their way to send it to themselves.

**Comment by CourtneyLee333** [comment]
On hold based on outstanding questions.

**Comment by CourtneyLee333** [comment]
@DerekCaelin [The figma playground for you to review.](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=11110-39155&t=0jmQN69PiMDmA0q7-1)

**Comment by DerekCaelin** [comment]
Calling this finished, with the expectation that we will speak with the Engineers about Courtney's questions.
