### ISSUE TITLE
Sign in screen: design update, reference terms of service and privacy policy

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1168]
Update the sign-in screen to reference our terms of service and privacy policy.

Proposed language (from app.terraso.org/login)

If you don’t already have a Terraso account, signing in will create one in accordance with our [terms of service](terraso.org/terms-of-service) and [privacy policy](https://techmatters.org/privacy-policy/).

**Comment by CourtneyLee333** [comment]
@DerekCaelin I don't have access to update the web app. Is this something Paul or Jose needs to do? There doesn't seem to be any design work, just change the text.

**Comment by DerekCaelin** [comment]
OK, I will ask Jose to update the text.
