### ISSUE TITLE
Design site metadata editing workflow

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#117]
```[tasklist]
- [x] Wireframes approved
- [x] Final Design approved
```
[LandPKS MUI Library](https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?node-id=8375%3A86793&t=e12gnjGPvVsDDbF9-1)
[LandPKS Wireframes and Prototype](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype?t=hiT0127wb8Tey06i-1) - Wireframes flows: Site Config, Site Settings, Site Team
Final Design: Managing a Site section

**Comment by CourtneyLee333** [comment]
@ltseng Wireframes are ready for your review.

**Comment by ltseng** [comment]
Was it an explicit choice to only be able to add sites to projects at the site creation step and from within a project? I could potentially see a third place being the Site's settings screen, but happy to leave it out to reduce complexity.

**Comment by CourtneyLee333** [comment]
Ready for BLM review.

**Comment by CourtneyLee333** [comment]
@Hanal-code ready for your review.

**Comment by CourtneyLee333** [comment]
@ltseng @Hanal-code Final Design ready for your review

**Comment by ltseng** [comment]
Approved
