### ISSUE TITLE
Offline: Don't persist Soil ID error states on load

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1179]
Provide the user with another way to clear error states for soil id.

## Acceptance criteria
- [ ] as a user who has encountered an error getting soil ID (temporary popover, temporary/site location dashboard, soil id screen), closing an reopening the app clears the error state and soil ID attempts to load again

**Comment by CourtneyLee333** [comment]
How do we test this? What error are we looking for, and how do we produce it?

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 You can check this with a site at a coordinate that doesn't have SoilWeb data.

**Comment by CourtneyLee333** [comment]
Okay, I found a location that returned "No matches", created a site, and the app fetched again. I closed the app and returned to that site, and it fetched again. 

To be clear, this is a site that has SoilWeb data, but the algorithm is failing so it returns "No matches". It should instead say "Error", but these issues are separate from this ticket I believe.

**Comment by DerekCaelin** [comment]
I found an old site that consistently returned "Error" ("Test Site A, `41.68523, -72.68802`)

It now tries to update soil ID. I get a "No Matches" error but, as Courtney says, it's related to our current issue with soil id. So this passes!
