### ISSUE TITLE
Design user flow for viewing site-level audit log

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#149]
```[tasklist]
- [ ] Wireframe approved
- [ ] Final Design approved
```
[LandPKS MUI Library](https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?node-id=8375%3A86793&t=e12gnjGPvVsDDbF9-1)
[LandPKS Wireframes and Prototype working files ](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype?t=hiT0127wb8Tey06i-1)

**Comment by CourtneyLee333** [comment]
@ltseng We talked briefly at the sprint planning about the format for audit log output. Can you write it out for me? I see [this list of samples](https://docs.google.com/document/d/1LGogXepXyGoyuddtgkwaeTFN-bvdKrhFE8hKjSopmmI/edit?usp=sharing), but there is a lot of variance, so I'd like to get clear about it.

**Comment by CourtneyLee333** [comment]
I also see a lot of audit log examples that are structured in tabular format. Would that be better than sentence style? There would likely be horizontal and vertical scrolling, which might not be possible in our tabbed sub-navigation.

**Comment by CourtneyLee333** [comment]
My horizontal scrolling comment was in the context of a table, not sentences.

**Comment by ltseng** [comment]
OK, in that case, I do prefer sentence style, but remain open to seeing those other examples if structured well.

**Comment by CourtneyLee333** [comment]
If you Google "audit log" and look at the images, they are all shown in tables. The format you listed above would be separated out into each of those elements being its own column. To me it seems much more easily scanned for specific data when in a table format, but what I don't know is what options we have for tables in a mobile app environment.

**Comment by ltseng** [comment]
@JeancarloBarrios the specific question that we want more clarity is around scrolling and zooming actions. Will React Native force the table to display in a zoomed-out format, without letting the user interact with the table?

**Comment by JeancarloBarrios** [comment]
A table sounds doable, but do you have an example of how you envision it, how it will look, and what interaction it may have? Zooming is possible.

**Comment by ltseng** [comment]
Creating a table example in [this Google Sheet](https://docs.google.com/spreadsheets/d/1dfm4Q9gM_O1gcl2Cl0R60xA36wzaB5kDQcGbccgbUx8/edit#gid=0)

Zooming, panning/scrolling, and copying are the actions I'm envisioning

**Comment by CourtneyLee333** [comment]
I wasn't imagining zooming. I think the table should be at a decent width that is going to extend beyond the edges of the mobile screen. Scrolling horizontally, as well as vertically, would be needed. 

I also hadn't heard anything about copying? What will that be for?

**Comment by ltseng** [comment]
I was thinking of how people would ideally get this information out of LandPKS into the document editor of their choice. It's probably most likely that people would want to just download the audit log as a CSV rather than highlighting the entire table, copying it, and pasting it into Google Sheets, especially from a phone.

**Comment by ltseng** [comment]
I wasn't sure if the table would support wrapping text by default. I'll try to display some examples during the meeting tomorrow.

**Comment by CourtneyLee333** [comment]
Tables should definitely support wrapping. Here's an idea for responsive table that might work:
<img width="269" alt="Screenshot 2023-06-14 at 10 18 43 AM" src="https://github.com/techmatters/terraso-product/assets/8915145/22bebd85-ee3f-4b94-8265-f94876fd791d">

I can explore the design of what goes on each line, what rows get highlighted, etc...

**Comment by ltseng** [comment]
This is no longer needed, so I'm closing for now
