### ISSUE TITLE
Design site member view and manage roles

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#155]
```[tasklist]
- [x] Wireframes approved
- [x] Final Design approved
```
[LandPKS MUI Library](https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?node-id=8375%3A86793&t=e12gnjGPvVsDDbF9-1)
[LandPKS Wireframes and Prototype](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype?t=hiT0127wb8Tey06i-1) - Wireframe flow: WIP Site Team (no project)
Final Design: Managing a Site section

**Comment by CourtneyLee333** [comment]
@Hanal-code ready for your review.

**Comment by CourtneyLee333** [comment]
@ltseng @Hanal-code Final Design ready for your review

**Comment by ltseng** [comment]
Looks good
