### ISSUE TITLE
Soil depth intervals - Part 1

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#157]
## User Story

- When a project is created, the project should be set to use LandPKS soil depth intervals by default. The project manager can also select NRCS depth intervals, create custom ones, or set "None Specified." See [spec ](https://docs.google.com/document/d/1U0tyXpBXm664UHnI7z1BrsSz1WrmnFP4EEmF-YpAK-k/edit#) for specific intervals
- As a site or project manager, if I select custom depth intervals at the project level, I can create and name up to 20 different custom default soil depth intervals between 0 and 200 cm in the US and international LandPKS apps.
  - Names must be unique
  - Names can use up to 10 characters
  - Depth intervals cannot overlap. One interval can end on the same integer value as another one begins (e.g. 0 -2 cm and 2 - 4 cm)
- These soil depth intervals should be common across all data input methods for the site or project
- As a site or project contributor, I can add another custom soil depth interval that does not overlap with the ones set by the site or project manager, if custom intervals have been specified.

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/205
- [ ] https://github.com/techmatters/terraso-product/issues/206
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-client-shared/issues/11
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/456
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/381
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/502
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/975
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/622
```

## Acceptance criteria

- I can only set custom depth intervals for sites or projects I manage.
- I can only add more custom depth intervals on a per-site basis for sites I have contributor access to
- Deleting a default custom soil depth interval should also delete all data collected at that depth.
- Corresponding audit log entries should be created for any create/edit/delete action taken by authenticated users in the site and project audit logs
- Analytics should be collected according to the spec document

[Custom soil depth intervals](https://docs.google.com/document/d/1U0tyXpBXm664UHnI7z1BrsSz1WrmnFP4EEmF-YpAK-k/edit#)
[Test cases](https://docs.google.com/spreadsheets/d/1tfn3UTpapi8E3YCATE4Na-XLa-f0JuTsOcSGUaXK7ws/edit)

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/504
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/943
```

```[tasklist]
### Out of Capri
```

**Comment by CourtneyLee333** [comment]
@ltseng  I wonder - can the project manager decide whether or not the contributor can add more intervals? Or, does the contributor always have the option to add intervals that are outside of the required intervals? 

And, don't we have a scenario where a contributor or manager can determine the intervals per site, and override presets, when they encounter soil horizons that are different than the presets?

**Comment by CourtneyLee333** [comment]
I also don't know how common or significant the scenario will be where the soil horizons are different from the pre-set intervals. I've included some questions about this in the notes for the next BLM meeting.

**Comment by ltseng** [comment]
@david-code and @ajabeckett -

@CourtneyLee333 and I conferred and made the following changes, which should be reflected in the user story above:

- Remove the toggle for "Soil Pit Required" -> When a project is created for the first time, it will default to using LandPKS depth intervals. The project manager can then go in and change the depth intervals to NRCS, Custom, or none required (i.e. per-site depth intervals).
- Independently, when a project is created for the first time, it will by default have slope, soil texture and rock fragments, and soil color required.
- When the project has either LandPKS, NRCS, or Custom depth intervals chosen, they will see a version of the screenshot below  with the circle icon for required data inputs next to Slope, Texture, Rock Fragment, and Color

![Image](https://github.com/techmatters/terraso-product/assets/2730009/c1974c1e-8fb9-4f7a-aedd-61aeb81a60dd)

- When the project has depth intervals set to "None specified," they will see a version of the screenshot below, with the circle icon for required data inputs next to Slope only. Then, as the data collectors create depth intervals, each depth interval will automatically be populated with similar rows with circle icons for texture, rock fragment, and color

![Image](https://github.com/techmatters/terraso-product/assets/2730009/f9c7af8d-d004-4c2d-b460-0708c1f9ae63)

- The project manager will have the option to not require any data inputs, but that will be a change they have to intentionally make to the default project requirements. In the case where all data requirements have been toggled off:
  - If they have LandPKS, NRCS, or custom depth intervals specified at the project level, data collectors would simply see a list of the depth intervals, with the three dots/More icon next to each depth interval, from which data collectors could select data inputs on an ad hoc basis.
  - If project depth intervals are set to "None specified," data collectors would need to create depth intervals, and then interact with the tree dots/More icon in order to select data inputs on an ad hoc basis.
