### ISSUE TITLE
Input soil color data

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#160]
A critical component of the data inputs that help to determine SoilID.

## References
[Spec - Soil Color](https://docs.google.com/document/d/1qY0D9JjLi9Ew_F2b7qOD7ZS4kqWtAEJUzZz039pB10M/edit)

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/210
- [ ] https://github.com/techmatters/terraso-product/issues/211
- [ ] https://github.com/techmatters/terraso-product/issues/572
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/129
- [ ] https://github.com/techmatters/terraso-client-shared/issues/10
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1115
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/974
- [ ] https://github.com/techmatters/terraso-product/issues/729
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/623
```

```[tasklist]
### QA
- [ ] https://github.com/techmatters/terraso-product/issues/644
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1352
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1319
```

## Additional Context
Note from Laura: 
**Note: engineers, please note that there are some technical discussions that Courtney and I would like to have before you start any technical work here.**

- As a site contributor or manager, I can contribute soil color data in the US and international LandPKS apps.
  - I can enter the Munsell color value (see [spec](https://docs.google.com/document/d/1qY0D9JjLi9Ew_F2b7qOD7ZS4kqWtAEJUzZz039pB10M/edit) for specific values)
  - I can take or select a photo from my device, select a bounding box (small, medium, and large), select the areas in the photos which represent the color sample and the soil sample, and see the results of the LandPKS color algorithm.
  - In the US app, the Munsell color value should be the default/first choice. In the International app, the photo selection process should be the default/first choice.
  - I can provide additional information on whether the soil was dry or moist
  - I can certify whether or not the photo was taken under even lighting conditions and has no shadows
 

## Acceptance criteria

- [ ] I can skip the process of taking/uploading a photo and directly input the Munsell color value if I so desire
- [ ] I can provide soil color data for sites I have contributor/manager access to
- [ ] I can delete soil color data for a given site and start over
- [ ] As an authenticated user, any data I contribute for soil color should be tracked in the site audit log.

**Comment by CourtneyLee333** [comment]
@ltseng Can you provide more detail for "If I chose to provide manual data for a site, I should be asked if I want to provide manual data for the other soil depths for the site."?

**Comment by ltseng** [comment]
It's a direct carryover from the current app. When a user chooses to use manual input for the first time to provide soil color for a single depth, they are asked if they want to switch to manual inputs for the other depths. If they agree, then they don't need to manually toggle over to manual input for the other depths. If they disagree, then the other depths will show the guided experience with selecting a color reference, sample size, and points on their photo. 

![Screenshot_20230703-090241_LandPKS.jpg](https://github.com/techmatters/terraso-product/assets/2730009/aa7d7335-4822-4e4b-91af-b8ca5aaac39d)

**Comment by CourtneyLee333** [comment]
Thanks!

**Comment by ltseng** [comment]
Courtney and I discussed a better workflow for this today, where the default for soil color input is manual, but users can select a "Guide me" option to go through the photo upload/identification process. As a result, I have removed the requirement above for "If I chose to provide manual data for a site, I should be asked if I want to provide manual data for the other soil depths for the site."

**Comment by CourtneyLee333** [comment]
Also, perhaps it's better to force the lighting and moisture requirements, rather than ask if they were met. TBD, waiting on Laura's answers to this on the spec.

**Comment by ltseng** [comment]
@shrouxm and @david-code when we get to building the soil color guide, keep in mind that this will ideally be built as a reusable component that can be later called from the [Toolbox](#330)

**Comment by DerekCaelin** [comment]
Closing since this is released. We have done QA and logged errors, and will follow up with Shawn Salley on the color experience.
