### ISSUE TITLE
Story Maps: embed story maps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#17]
## Description

Create an embed code that allows users to share their story maps on another site.

## Problem

[Landscapes.Global](https://Landscapes.Global) and the LMS team want to use Terasso Story maps as a way to tell stories about landscapes. They want to embed a story map in their own page, so the user doesn't need to navigate away from their site in order to see the story map content.

**Learning:** [Media embed in Moodle is a URL, not an embed code](https://docs.moodle.org/22/en/Embedding_content). 

## References

- Dependent on: https://github.com/techmatters/terraso-web-client/issues/775
- Moodle Embed documentation: https://docs.moodle.org/22/en/Embedding_content
- [Product Sketches](https://app.mural.co/t/techmatters9109/m/techmatters9109/1681155747395/ed40bd0c65875006200062d0ec8d655cc8bf46c8?sender=u3faecbd439cadb255c696741)

## Design

**Share module mockup** 

- Add 'Copy Code' chunk below 'Copy link'  
- Terraso Story map embed will have the vertical scrollbar and link to Terraso.

<img width="513" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/d2ae9116-c783-4530-89c5-25bf94c3b87f">

**See the click-through prototype:**
https://www.figma.com/proto/GTlHki4txQ924a6FFKHFDp/Story-Map---Embed-a-published-story-map?page-id=0%3A1&type=design&node-id=9-6667&viewport=-454%2C330%2C0.5&scaling=min-zoom&starting-point-node-id=9%3A6667

# Release Criteria

## Product
- [x] As a story map viewer in Terraso, I want to be able to copy the embed code for a map so that I can paste it onto a website or a blog, so that I can share the map externally and anyone can view it without needing a Terraso account.
- [x] As the viewer of an embedded story map, I should understand that the map was created using Terraso 
- [x] As the viewer of an embedded story map outside Terraso, I should be able to navigate to Terraso to see the map. 

## Design 
- [x] Implementation matches design
- [x] Copy Editing (N/A)
- [ ] Translation (Spanish)
- [ ] Additional changes...

## QA
Happy Path Test
- [x] From story map, click "share" and see embed code
- [x] Copy code button adds code to the clip board
- [x] UI signifies that the code has been copied
- [x] Pasted code generates a well-formatted story map
- [x] Iframe on generates a story map
- [x] story map does not have the standard terraso header
- [x] Story Map has clear signifier that story map was made with Terraso
- [x] Clicking on element brings the user to Terraso in a new window

Unhappy Path Test
- [x] user can't edit the embed code in the Terraso UI
- [x] changing the name of the story map updates the embed code

**Comment by Hanal-code** [comment]
Click-thru mockup (Figma): 
https://www.figma.com/proto/GTlHki4txQ924a6FFKHFDp/Story-Map---Embed-a-published-story-map?page-id=0%3A1&type=design&node-id=9-6667&viewport=1002%2C231%2C0.5&scaling=min-zoom&starting-point-node-id=9%3A6667

**Comment by Hanal-code** [comment]
**Share module mockup** 

- Add 'Copy Code' chunk below 'Copy link'  
- Terraso Story map embed will have the vertical scrollbar and link to Terraso.

<img width="513" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/d2ae9116-c783-4530-89c5-25bf94c3b87f">



**See the click-through prototype:**
https://www.figma.com/proto/GTlHki4txQ924a6FFKHFDp/Story-Map---Embed-a-published-story-map?page-id=0%3A1&type=design&node-id=9-6667&viewport=-454%2C330%2C0.5&scaling=min-zoom&starting-point-node-id=9%3A6667

**Comment by DerekCaelin** [comment]
@josebui this is ready for implementation. I will sort it in our backlog.

**Comment by DerekCaelin** [comment]
My tests of the feature are going well so far. @josebui @Hanal-code should the "title" in the iframe be "Terraso Story Map" or the name of the story map itself? 

![Image](https://github.com/techmatters/terraso-product/assets/10799815/a114938f-36ad-40e0-a2c5-3e73927c7713)

**Comment by DerekCaelin** [comment]
### Issues

html: 
`<iframe src="https://app.staging.terraso.net/tools/story-maps/t8o6a8t/new-test-of-story-maps/embed" title="Terraso Story Map" width="100%" height="100%" frameborder="0"></iframe>`

## When embedding in an LMS (Moodle), the iframe height is too small:

<img width="1408" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/f31409b4-b60a-4752-95a2-f4098e0f978a">
<img width="1408" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/8aea88a1-fbc5-438c-b0ce-dac4337abf96">

## When embedding in a WordPress blog, the story map doesn't show up:
<img width="1408" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/c70615f2-c6ab-4d30-a251-49d294b8cba1">
<img width="1408" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/f241f9c9-abd1-4f27-a60b-9d8e5eec8b20">

**Comment by DerekCaelin** [comment]
@josebui can we set the default view to be width: 750px, height: 500px?

**Comment by josebui** [comment]
I added the fixed dimensions you can tests it on staging now

**Comment by DerekCaelin** [comment]
@josebui dimensions look great now, thank you.

The WordPress embed issue persists. I've tried to embed the iFrame in our WP staging blog and it doesn't appear. Is this more likely to be an issue with WP or with our code?

**Comment by DerekCaelin** [comment]
@paulschreiber would you please create an account for Jose on WordPress? (Or suggest why iFrames might not be working on our own site?)

**Comment by DerekCaelin** [comment]
@josebui I've tested this in another wp instance and it is working. So I think I will file the wordpress issue as a separate bug.

This passes QA and the user stories. @Hanal-code does implementation match design?

**Comment by Hanal-code** [comment]
@DerekCaelin  yes, verified on Terraso, LMS (https://learn-tst.landscapes.global/course/view.php?id=2)
