### ISSUE TITLE
Enforcing geographical boundaries in the US and international apps

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#179]
### User Story

US Soil ID only

- As a user of the US Soil ID app, I should not be able to create a site for locations outside of the US as specified by the NRCS SSURGO map boundary, give or take a 100 m buffer zone (to account for GPS inaccuracies).
  - Users of the US Soil ID app should not be able to see sites in the US that were created in the international Soil ID app.
  - When users type in a lat/long pair to the site creation form that corresponds with a location outside of the US, display this error message: "Location is outside of the US. The US version of LandPKS Soil ID can only be used for US locations."

International Soil ID only

- As a user of the International Soil ID app, I can create sites for locations anywhere in the world.
  - Users should see a warning about the data sources used and limited functionality for sites created in the US from the international Soil ID app. The app should also recommend that they switch to the US app

```[tasklist]
### Designs
- [ ] https://github.com/techmatters/terraso-product/issues/352
- [ ] https://github.com/techmatters/terraso-product/issues/353
- [ ] https://github.com/techmatters/terraso-product/issues/354
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/373
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/374
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/375
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/376
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/377
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/768
- [ ] https://github.com/techmatters/terraso-backend/issues/769
- [ ] https://github.com/techmatters/terraso-backend/issues/770
```

Acceptance criteria

- Users of the US app should be blocked from creating sites outside of the US
- Users of the international app can create sites anywhere in the world, but any sites they create in the US should use international soil information sources, soil names, data input methods, and reports.

[Creating a site](https://docs.google.com/document/d/1vxITdvD9EOjOa92BG7iaSyv55iWZpNCKPDlJOh4sb2Q/edit#)

**Comment by ltseng** [comment]
Start with bare bones notice to user that perhaps the reason why they are not seeing good data is because the location they've selected is outside of the US

**Comment by CourtneyLee333** [comment]
@ltseng Have we changed our plan for users of the US app when dropping a pin outside the US?

**Comment by ltseng** [comment]
No, that plan has not changed. The way in which we do it with regards to implementation may have changed (see Steve's email several weeks ago now about the team's assessment of the remaining time), but we should still plan to block US app users from creating sites outside of the US.
