### ISSUE TITLE
Location Dashboard

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#184]
A page which allows users to explore information about a location, and to start the site creation experience. 

## References

[Location Dashboard](https://docs.google.com/document/d/1DRogX4b5lDO5uFuS3dVGFkc3d8ZJjNhdk5tLs_EEOgk/edit#)
[Design - Home screen, location popover](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13278&mode=design&t=YcLt8kGzaHxgBrgS-0)
[Design - Location dashboard](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-15841&mode=design&t=YcLt8kGzaHxgBrgS-0)

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/309
- [ ] https://github.com/techmatters/terraso-product/issues/321
- [ ] Develop copy documentation for US Location Dashboard
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/456
- [ ] https://github.com/techmatters/terraso-product/issues/334
- [ ] https://github.com/techmatters/terraso-product/issues/163
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1161
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/543
```

## Acceptance criteria

- [ ] As a user, when I select a location on the map, I want to see a page consisting of 
   - [ ] Map 
   - [ ] Location details: Latitude, longitude, and elevation
   - [ ] A "Create site here" button
   - [ ] A SoilID tile
- [ ] As a user selecting the "Explore the data" button on the SoilID Tile, I want to see a SoilID page consisting of
   - [ ] A description of SoilID
   - [ ] A ranked list of soils form SoilID, with names and rank percentages
   - [ ] A "Create site here" button
- [ ] As a user selecting the a soil type from the ranked soil list, I want to see a page consisting of
   - [ ] The soil name and description
   - [ ] The location score
   - [ ] Soil properties
   - [ ] A "Create site here" button

**Comment by ltseng** [comment]
If a site exists at a given set of coordinates, could I expect to create another site from the existing site's dashboard? If not, where can I expect to do so?

**Comment by ltseng** [comment]
Assigning to @david-code and @shrouxm to break down into subtasks

**Comment by DerekCaelin** [comment]
Merging this issue with a unifying "location dashboard" issue: 
- https://github.com/techmatters/terraso-product/issues/667#issue-2256981799
