### ISSUE TITLE
Site completion status

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#187]
## User Story

- As a project member, I can see the site completion status (rounded to the nearest integer) of any site in the project as calculated by [the following formula](https://docs.google.com/document/d/1jWkO84GtzwuopdIHA3zh04mMsL2OcDIRrgbdL9mgmsU/edit):
  - sum(completed data inputs for the given site)/sum(total required data inputs for the given site) 
  - More specific calculations are available in [the spec](https://docs.google.com/document/d/1jWkO84GtzwuopdIHA3zh04mMsL2OcDIRrgbdL9mgmsU/edit#heading=h.iz3z96xpn0zy).
- If the project manager has set any soil pit requirements, then the number of required data inputs is dependent on the number of depth intervals defined per site.
-If the project manager has not set any soil pit requirements, then site completion status can only be calculated by the number of required surface-level data inputs.
- If no data input methods are specified as required, then project sites will not display a completion status.

```[tasklist]
### Design
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/49
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/71
- [ ] Add completion status to sort menu within a project
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1401
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1402
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1400
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/561
```

## Acceptance criteria

- The number of required data inputs for a site should be calculated as a combination of required surface-level data inputs and required depth-dependent data inputs (if applicable)
- I can see the completion status for any site belonging to a project where I am a member, and where at least one data input method has been set as required by the project manager, as a percentage between 0 and 100%
- As I complete required data input methods for a given site, I should see the completion status percentage increase.
- If I delete previously-gathered data for a given site, I should see the completion status increase.
- The number of required data inputs for a site should be calculated as a combination of required surface-level data inputs and required depth-dependent data inputs (if applicable)

## Resources
[Site completion status](https://docs.google.com/document/d/1jWkO84GtzwuopdIHA3zh04mMsL2OcDIRrgbdL9mgmsU/edit)
[Project data collection presets](https://docs.google.com/document/d/1MKMD02X6mD0DiD3pYT-qG3mlo5WMFGIDjLogH57r7TM/edit?pli=1)

**Comment by ltseng** [comment]
Note that this work will not include the addition of the "sample collected for lab test" checkbox for MVP

**Comment by CourtneyLee333** [comment]
@ltseng I believe design work is done for this. Let me know if that's not right.

**Comment by ltseng** [comment]
I think it's done as well, so feel free to ignore this task from now on.

**Comment by DerekCaelin** [comment]
Not planned at this time
