### ISSUE TITLE
Design UI for slope and slope shape

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#207]
```[tasklist]
- [x] Wireframe approved
- [x] Update wireframes based on spec changes
- [ ] Final Design approved
```
[Final Design - Site Dashboard: Slope](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1848%3A49976&mode=design&t=Yx4SQATp8zUQgmgX-1)

**Comment by CourtneyLee333** [comment]
@ltseng Do we have a repository of imagery and videos used by the current app?

**Comment by ltseng** [comment]
I don't know that immediately off the top of my head, we should probably ask either Laura or @paulschreiber. On the meantime, there are a couple folders in the previous LandPKS Github repo that contain images used in the app. Here's one of them: https://github.com/LandPotential/LandPKS/tree/master/SVG

**Comment by paulschreiber** [comment]
@CourtneyLee333 We have the source for the existing app, including images/videos.

**Comment by CourtneyLee333** [comment]
@paulschreiber How can I access the visual assets?

**Comment by CourtneyLee333** [comment]
@ltseng @Hanal-code Please review my very rough wireframes and let me know what you think. Be sure to read the comments, and note the alternative main Slope screen layout.

**Comment by ltseng** [comment]
Left some feedback, but I think we might want to discuss live as a group.

**Comment by CourtneyLee333** [comment]
As of 7/25 - needs review from stakeholders, but we are waiting to have more data inputs speced and wireframed.

**Comment by ltseng** [comment]
Looks great!

**Comment by CourtneyLee333** [comment]
Final design ready for review.

**Comment by ltseng** [comment]
Made a couple comments

**Comment by ltseng** [comment]
Looks good!

**Comment by CourtneyLee333** [comment]
@ltseng Do we need to get sign-off from stakeholders on the final designs?
