### ISSUE TITLE
Design UI for soil texture collection

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#208]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Site Dashboard: Soil Texture](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1850%3A50163&mode=design&t=Yx4SQATp8zUQgmgX-1)

**Comment by CourtneyLee333** [comment]
Final design ready for review.

**Comment by ltseng** [comment]
Looks great to me!
