### ISSUE TITLE
Design UI for entering Munsell value

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#210]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Soil Color final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2067%3A93347&mode=design&t=oKe5X2nidVRpfPFg-1)

**Comment by ltseng** [comment]
Looks good!
