### ISSUE TITLE
Design workflow for getting soil color from photo

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#211]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Soil Color final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2067%3A93347&mode=design&t=oKe5X2nidVRpfPFg-1)

**Comment by CourtneyLee333** [comment]
@ltseng This is ready for your review. There are some graphics missing, and some discussion that needs to be had with developers when they get this far. But for now I'm as far as I can go.

**Comment by ltseng** [comment]
One small question, but otherwise looks good!
