### ISSUE TITLE
Design general flow for data inputs

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#212]
Include tool tips and help info sheets.

```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[LandPKS MUI Library](https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?node-id=8375%3A86793&t=e12gnjGPvVsDDbF9-1)
[LandPKS Wireframes and Prototype working files ](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype?t=hiT0127wb8Tey06i-1)

**Comment by CourtneyLee333** [comment]
@ltseng I'm considering this done, at the high level. The only thing to show for Final Design is the app bar and tab slider, [which you can see here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1341%3A45887&mode=design&t=8XUH6NqO9JSfwfyW-1).

**Comment by ltseng** [comment]
Sounds great! I'll close this issue out then.
