### ISSUE TITLE
Design UI for electrical conductivity collection

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#214]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Soil EC final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2116%3A18180&mode=design&t=oKe5X2nidVRpfPFg-1)

**Comment by CourtneyLee333** [comment]
@ltseng Wireframe ready for your review [here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1632%3A47052&mode=design&t=xyWIp4g9JSEQoVAS-1)

**Comment by ltseng** [comment]
I signed off in Figma, but forgot to do it here too. Looks good!
