### ISSUE TITLE
Design UI for soil structure collection

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#215]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Soil Structure final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2108%3A17782&mode=design&t=oKe5X2nidVRpfPFg-1)

**Comment by CourtneyLee333** [comment]
@ltseng I've left a note for the engs about graphics - when they get this far along we should have a convo about what sizes/formats/specs/whatever they need me to produce.

**Comment by ltseng** [comment]
Sounds good, looks great otherwise!
