### ISSUE TITLE
Design UI for pH collection

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#216]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Soil pH final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2116%3A18011&mode=design&t=oKe5X2nidVRpfPFg-1)

**Comment by ltseng** [comment]
Left one minor comment, otherwise looks good!
