### ISSUE TITLE
Design UI for SOC/SOM collection

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#217]
Need instructions on how you can determine your SOM %.

```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[SOC/SOM final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2116%3A18361&mode=design&t=oKe5X2nidVRpfPFg-1)

**Comment by CourtneyLee333** [comment]
@ltseng Wireframe ready for your review [here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1640%3A47969&mode=design&t=fS8fNbnyePQ74XHN-1), with comments/questions about lab testing.

**Comment by ltseng** [comment]
Reviewed and looks good!

**Comment by ltseng** [comment]
Looks good! 👍
