### ISSUE TITLE
Design UI for SAR data collection

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#218]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[SAR final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2116%3A18376&mode=design&t=oKe5X2nidVRpfPFg-1)

**Comment by CourtneyLee333** [comment]
This hasn't been fully speced yet.

**Comment by CourtneyLee333** [comment]
@ltseng Wireframe ready for review [here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1651%3A47152&mode=design&t=fS8fNbnyePQ74XHN-1)

**Comment by ltseng** [comment]
Looks good enough to move forward with!
