### ISSUE TITLE
Creating a project

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#22]
User story

- As an authenticated user, I can create a project, name it, and set it as public/private. 
- I will become the Project Manager for any projects I create

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/63
- [ ] https://github.com/techmatters/terraso-product/issues/65
```

```[tasklist]
### Frontend
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/34
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/35
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/53
- [ ] https://github.com/techmatters/terraso-client-shared/issues/18
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/144
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/208
- [ ] https://github.com/techmatters/terraso-product/issues/343
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/338
- [ ] https://github.com/techmatters/terraso-backend/issues/374
- [ ] https://github.com/techmatters/terraso-backend/issues/458
- [ ] https://github.com/techmatters/terraso-backend/issues/454
```

Acceptance criteria
- All users should see a "My Projects" page with a button to create a project
- I must provide a unique title in order to save the project. The project cannot share a name with any other project I belong to at the time of creation.
  - Note: in the case that a user is added to a project that shares the same name as one of their existing ones, allow this to happen, but they will not be able to create another project with that same name. 
- I can set the privacy of the project to public or private (default to private) if I am an authenticated user
- I can set the project description when creating a project, or leave it blank. I can also edit the project description at any point afterwards.
- After successfully creating a project, it should appear in the list of My Projects
- I can cancel at any point during the project creation process without it appearing in the list of My Projects
- Creating a project as an authenticated user should generate an audit log entry.

[Project management spec](https://docs.google.com/document/d/1Mo54pX4gbn0GWJfTOOvjA7TB41AgHOKYxEMSKtm3dOM/edit#)

[Test Cases](https://docs.google.com/spreadsheets/d/1wYMTBKBBn35L1zY8ikK-CN7veWb6Vp2_hg1in9wYPUk/edit#gid=2004954072)

**Comment by shrouxm** [comment]
@ltseng this user story is marked complete but there are several acceptance criteria that are not yet met:
- projects are not searchable or filterable (there is now an open PR for searching but nothing for filtering)
- sites are not searchable or filterable (there is now an open PR for searching sites by name, but nothing for filtering or searching by notes)

should we re-open this issue, or are those items being tracked somewhere else now?

**Comment by ltseng** [comment]
I'm going to make a new user story for searching and filtering projects, and sites within a project. Then, I can do QA on that one separately, since I'm considering the QA for this one largely complete, at least from a manager's perspective.

**Comment by ltseng** [comment]
Created new user story here - https://github.com/techmatters/terraso-product/issues/391

**Comment by shrouxm** [comment]
@ltseng why was this re-opened? same question with https://github.com/techmatters/terraso-product/issues/32 and https://github.com/techmatters/terraso-product/issues/33

**Comment by ltseng** [comment]
I will probably want to do a full round of QA, using this and the other issues as the testing issues, and link a couple of new bugs/issues that Courtney has sent me for design work. I'm happy to create a new QA issue, but it would likely contain duplicate acceptance criteria/test cases as these issues.

I know we did a preliminary round of testing for the usability tests, but those were quick and focused solely on the study tasks. Courtney and I would like to do a more comprehensive round of review and testing before fully signing off on all of these user stories.

**Comment by ltseng** [comment]
Ok, I've run the functional tests on this flow and am satisfied that it passes on all platforms available to me. @CourtneyLee333 do you want to do another round of design QA on this? The test case document is linked above, under the spec link. If not. I'll close this user story (finally)

**Comment by ltseng** [comment]
I'm copying this design feedback into a separate task [here](https://github.com/techmatters/terraso-mobile-client/issues/534) and officially closing this user story.
