### ISSUE TITLE
Setting data collection methods for a project

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#26]
## Acceptance Criteria
```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/288
- [ ] https://github.com/techmatters/terraso-product/issues/289
- [ ] https://github.com/techmatters/terraso-product/issues/290
- [ ] https://github.com/techmatters/terraso-product/issues/291
- [ ] https://github.com/techmatters/terraso-product/issues/292
- [ ] https://github.com/techmatters/terraso-product/issues/293
- [ ] https://github.com/techmatters/terraso-product/issues/294
- [ ] https://github.com/techmatters/terraso-product/issues/295
- [ ] https://github.com/techmatters/terraso-product/issues/296
- [ ] https://github.com/techmatters/terraso-product/issues/303
- [ ] https://github.com/techmatters/terraso-product/issues/304
- [ ] https://github.com/techmatters/terraso-product/issues/305
- [ ] https://github.com/techmatters/terraso-product/issues/306
- [ ] https://github.com/techmatters/terraso-product/issues/307
- [ ] https://github.com/techmatters/terraso-product/issues/308
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-client-shared/issues/85
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/381
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/775
- [ ] https://github.com/techmatters/terraso-backend/issues/1197
```

## Acceptance criteria
(Requires techmatters/terraso-product#23 to be completed first)
- As a project manager, I can set individual data input methods to be required for all sites across a project
- When data input methods are set as required for a project:
  - Required data input methods will appear first, and optional data input methods will be hidden in a side menu, but still accessible to individual project contributors/managers
    - When a project is created, it will require slope, soil texture (and rock fragments), and soil color by default. Project managers can then make changes to the required data inputs, even going as far as turning all requirements off.
  - For projects that have no set depth intervals, required data inputs will appear upon the creation of each per-site depth interval
- Marking a previously-required data collection method as optional should not delete any already-collected data.
- Bedrock measurements should only affect (i.e. disable) required data inputs for lower soil depth intervals than the one containing the bedrock.

## Resources
[Project data collection presets](https://docs.google.com/document/d/1MKMD02X6mD0DiD3pYT-qG3mlo5WMFGIDjLogH57r7TM/edit?pli=1)

**Comment by ltseng** [comment]
@CourtneyLee333 ready for you to break down into Design tasks.

This is a pretty large task now that I've written it out, but I'm not sure how to further simplify it.

**Comment by CourtneyLee333** [comment]
@ltseng I already built out the subissues =)

**Comment by ltseng** [comment]
You're completely right! @david-code and @JeancarloBarrios on to you

**Comment by ltseng** [comment]
Make sure to check https://github.com/techmatters/terraso-product/issues/157#issuecomment-1805932305 for an updated summary comment on how this feature should work
