### ISSUE TITLE
Archiving projects

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#28]
## User Story

- As a Project Manager, I can archive a given project where I have that role
  - Archiving a project will remove it from the My Projects view into the Archived Projects view for myself and all other members/managers of the project
  - Archiving a project will also archive all sites associated with that project
  - As a Project Manager or Member, I can access the audit logs for the archived project and site from the Archived Projects view, but no changes can be made to the project or site, and no additional events will be logged to their audit logs.

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/74
```

```[tasklist]
### Frontend
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/68
- [ ] https://github.com/techmatters/terraso-client-shared/issues/18
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/149
```

```[tasklist]
### Backend
- [ ] https://github.com/techmatters/terraso-backend/issues/565
- [ ] https://github.com/techmatters/terraso-backend/issues/566
- [ ] https://github.com/techmatters/terraso-backend/issues/567
- [ ] Audit log updates for archive and unarchive events
```

## Acceptance criteria

- I should only see the option to archive/unarchive a site from a project where I am a Project Manager
- After archiving a project, it should appear in my Archived Projects page
- After archiving a project and its associated sites, I should not be able to edit any aspect of the project or its sites. This includes, but is not limited to, changing the project name/privacy, inviting new project members or changing existing member roles, adding or removing sites, and adding site data.
- After unarchiving a project, it should appear in My Projects, and all aspects of the project and its sites should be editable. The project should also appear as editable for all other managers and members of the project.

[Project Management Spec](https://docs.google.com/document/d/1Mo54pX4gbn0GWJfTOOvjA7TB41AgHOKYxEMSKtm3dOM/edit#)

**Comment by DerekCaelin** [comment]
This may be necessary in the future but is not currently planned
