### ISSUE TITLE
In-App help text for scientific parts of LandPKS

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#285]
## User Story

- As a user of the LandPKS mobile apps, I can access timely and relevant help content within the app on the many data input methods that are available to me. This help content should minimally address:
  - What the data input method is and how it is performed
  - Why it is useful for measuring soil health
  - What other reports or functions of LandPKS it may be useful for.
- As a user of the LandPKS mobile apps, I can access timely and relevant help content within the app on the many reports that are available to me. This help content should minimally address:
  - What the report is
  - How it is calculated
  - Why I might find it useful to engage with the reports

```[tasklist]
### Design
- [x] Write help content for soil cracking
- [x] Write help content for soil texture/rock fragments
- [x] Write help content for soil color
- [x] Write help content for slope
- [ ] https://github.com/techmatters/terraso-product/issues/618
- [ ] https://github.com/techmatters/terraso-product/issues/607
- [ ] https://github.com/techmatters/terraso-product/issues/286
- [ ] https://github.com/techmatters/terraso-product/issues/609
- [ ] https://github.com/techmatters/terraso-product/issues/610
- [ ] https://github.com/techmatters/terraso-product/issues/619
- [ ] https://github.com/techmatters/terraso-product/issues/611
- [ ] https://github.com/techmatters/terraso-product/issues/620
```

## Acceptance criteria

- As a user, I can find help content within 1 or 2 clicks in the appropriate context that I start from.

**Comment by CourtneyLee333** [comment]
I have marked everything here that is done, and I've created issues and added labels for Capri MVP. The remaining tasks will need to be converted to tickets and labeled appropriately in the next phase.
