### ISSUE TITLE
International Location Dashboard

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#287]
Ideally building on https://github.com/techmatters/terraso-product/issues/184

## User Story

- As a user who has not created a site for a given location, when I access the location dashboard in the international app,I can
  - view location-specific metadata (lat/long/elevation, satellite photo)
  - view Soil ID predictions
  - view Climate reports
  - create a site
- As a site manager/contributor, when I access the site dashboard in the international app, I can:
  - view site-specific metadata (bedrock, date last modified, privacy), plus the location-specific metadata
  - access all the functions listed above (minus create a location)
  - take site data
  - take data for and view LCC rating
  - view AWC reports
  - view WOCAT 
  - view summaries of data
  - export reports of data
- As a site viewer, when I access the site dashboard in the international app, I can:
  - view site-specific metadata
  - view site data
  - view summaries of data
  - View available LCC ratings and AWC reports
  - View WOCAT
  - Export reports of data

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/339
- [ ] https://github.com/techmatters/terraso-product/issues/338
```

```[tasklist]
### Front end
- [ ] Placeholder
```

```[tasklist]
### Back end
- [ ] Placeholder
```

## Acceptance criteria

- I can create sites from the location dashboard when one doesn't exist
- I can access the location dashboard by selecting a location on the map and selecting "More Info"
- I can access the site dashboard as a site member by selecting a site from either the map view, sites list view, or project sites list view.
- I can take data for a site as a site contributor/manager
- I can view data for a site as a site contributor/viewer/manager.

## Resources
[Location Dashboard](https://docs.google.com/document/d/1DRogX4b5lDO5uFuS3dVGFkc3d8ZJjNhdk5tLs_EEOgk/edit#)

**Comment by DerekCaelin** [comment]
Will recreate as a smaller user story
