### ISSUE TITLE
Deleting projects

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#29]
## User Story

- As a Project Manager, I can delete a given project where I have that role
  - Deleting a project will remove it from the My Projects page for all members/managers
  - Deleting a project will also delete all sites associated with that project
  - I should see a warning message telling me that all data for this project and associated sites will be completely deleted, and asking me to confirm this action.
  - ~I should see the option to bulk transfer all sites out of this project into another one in which I have edit access.~

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/75
```

```[tasklist]
### Frontend
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/67
- [ ] https://github.com/techmatters/terraso-client-shared/issues/18
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/150
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/508
```

## Acceptance criteria

- I can only delete projects where I am a Project Manager
- If sites are attached to the project that I am deleting, those sites should also be deleted for me, if I choose not to transfer those sites to another project. Those sites should no longer appear in My Sites, or for anyone else associated with the project.
- ~If I choose to transfer sites to another project, I should see those sites appear in the other project after deleting the original one, and those sites should remain in My Sites.~

[Project Management Spec](https://docs.google.com/document/d/1Mo54pX4gbn0GWJfTOOvjA7TB41AgHOKYxEMSKtm3dOM/edit#)

[Test Cases](https://docs.google.com/spreadsheets/d/1vkBvEUu0-WIMA-D7Cob_f5H0NcupVh5S6JJQzOg2tYI/edit#gid=2004954072)
```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/516
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/518
```

**Comment by ltseng** [comment]
Just realized that we never designed UI for "I should see the option to bulk transfer all sites out of this project into another one in which I have edit access," so I'm logging this as a backlog issue for next year instead of further delaying the completion of this user story.

**Comment by CourtneyLee333** [comment]
@ltseng I think this one covers it 
https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=165%3A21734&mode=design&t=6ikLIkCJCkT959yk-1

**Comment by CourtneyLee333** [comment]
along with this 
https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=224%3A20288&mode=design&t=6ikLIkCJCkT959yk-1

**Comment by ltseng** [comment]
Correct, but I meant as part of the workflow to delete a project. We may have already discussed this, in which case I never updated the acceptance criteria, but I was envisioning that for the future, we could ask managers if they wanted to transfer sites in bulk to another project or to their own account at the time of deletion. Right now, we inform project managers that this is what they would have to do, but they would have to cancel deleting the project, go find another project or create a new one, and then transfer all the sites to that new one from the one they wanted to delete. This is fine, but doesn't meet the acceptance criteria as I originally intended, so I'm striking it out.

**Comment by ltseng** [comment]
Functional testing is done, but there are a couple bugs we need to resolve before I can fully close this user story out.
