### ISSUE TITLE
Transferring sites between projects

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#30]
## User Story

- As a Project Manager, I can transfer one or multiple sites between projects that I have edit access to

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/77
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/65
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/145
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/431
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/433
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-product/issues/219
- [ ] https://github.com/techmatters/terraso-backend/issues/402
```

## Acceptance criteria

- I can only transfer sites if I am a Project Manager on both the original and destination projects
- I can only transfer sites from and to sites where I have the Project Manager role
- After I move a site from Project A (original site) to Project B (destination site):
  - members of A and B will see the site in project B, and that site will continue to appear in My Sites
  - members of A will no longer see the site in project A, and that site will disappear from My Sites
  - members of B will see the site in project B, and that site will appear in My Sites

[Project Management Spec](https://docs.google.com/document/d/1Mo54pX4gbn0GWJfTOOvjA7TB41AgHOKYxEMSKtm3dOM/edit#)

[Test Cases](https://docs.google.com/spreadsheets/d/1xlq1rFtj8p9W9xliZfehzP3nujJ6K9IT5rnd9c4_X64/edit#gid=2004954072)

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/562
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/563
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/564
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/565
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/566
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/570
```

**Comment by ltseng** [comment]
@david-code can you check on whether the backend work for this story has been done already? If so, please link the subissue here. If not, please create one.

@JeancarloBarrios Please update this user story with the subissue for the audit log updates when sites are transferred between projects.

**Comment by david-code** [comment]
@ltseng Added a closed issue that allows users to move sites between projects.

**Comment by ltseng** [comment]
![image](https://github.com/techmatters/terraso-product/assets/2730009/890ed2a9-e6e2-4e00-90df-2806debeeeca)

@david-code should I do anything else to see a Save button show up, or is that part of the UI not done yet?

I'm also guessing that this will need another styling pass before it's fully ready to test?

**Comment by ltseng** [comment]
@CourtneyLee333 I'm done with functional testing for now and have found a couple minor bugs, which you can see in the description above, as well as in the test cases document which is linked above. Would you like to take a styling pass?

**Comment by CourtneyLee333** [comment]
It occurs to me that since we no longer are making the distinction between transferring existing sites and creating new sites from within the project, we should change the heading "Transfer existing sites" to "Transfer Sites to this Project".

**Comment by ltseng** [comment]
That makes sense too!
