### ISSUE TITLE
Review feedback on Product Principles and finalize

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#302]

**Comment by Hanal-code** [comment]
Notes:  https://docs.google.com/document/d/1mrLIuC8x98sGVifmhL7q7EuFDn0vvO7suWMEnge4lgY/edit#heading=h.6dliojk7idhj

**Comment by Hanal-code** [comment]
Poster (PDF): https://drive.google.com/drive/folders/1jELaid2xzXizssyfYup07XujfOa98FfM

**Comment by Hanal-code** [comment]
@DerekCaelin Can review the PDF and move it to Done?
