### ISSUE TITLE
Notes requirements

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#308]
Project management setting. Needs to include:

- As a project manager, I can set a prompt for all sites in a project that will display whenever a project member takes a note

[LandPKS Prototype - WIP Project Data Inputs](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=165%3A21853&mode=design&t=YaH6rZrQRyon5NFj-1)

**Comment by CourtneyLee333** [comment]
@ltseng Rather than mockup all the possible data collection requirements, I've started a list at the bottom of the mockup for engineers.

**Comment by ltseng** [comment]
Sounds good and looks good!

**Comment by CourtneyLee333** [comment]
Actually, ignore my last comment. This is done, and refers only to the requirement toggle for a minimum of one note from the data collector.
