### ISSUE TITLE
Design US dashboard for site

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#310]
- view site-specific metadata (bedrock, data privacy, location accuracy, and date last modified)
- view location-specific metadata (lat/long/elevation, satellite photo)

```[tasklist]
- [x] Reports discovery
- [x] Site tab layout wireframe
- [x] Site tab final design
- [x] Dashboard layout wireframe
- [x] Dashboard layout final design
```
[Site Dashboard final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3376%3A43617&mode=design&t=wkxXPZXrG2avVro7-1)

**Comment by CourtneyLee333** [comment]
Wireframe ready for stakeholders

**Comment by CourtneyLee333** [comment]
@ltseng FYI I've updated the design based on some feedback from Hana. Also, I don't think location accuracy belongs on the site dashboard, do you? Location accuracy is relevant to what GPS is pulling, but it seems that once the user has entered the coordinates or an address this isn't relevant. I'm not sure how we need to convey the accuracy of the GPS, but I don't think site meta data is the right place. Thoughts?

**Comment by CourtneyLee333** [comment]
Looking at the prototype on your phone is a good way to get a better sense of how it's working. Let me know if you need to know how to do that.

**Comment by ltseng** [comment]
I think I might need a direct link, if you can give me one?

**Comment by CourtneyLee333** [comment]
https://www.figma.com/proto/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?page-id=138%3A13384&type=design&node-id=3376-43617&viewport=2099%2C-4102%2C0.71&t=Q2K2eeqFOTntuXFt-1&scaling=min-zoom&starting-point-node-id=712%3A25895&show-proto-sidebar=1&mode=design

**Comment by CourtneyLee333** [comment]
Since we are funneling users through the map in order to find the exact location they want, perhaps the right place for GPS accuracy is on the location popover. Once they see the location or site dashboard, those coordinates are what they are. And yes, I agree that location accuracy could be displayed again in a UI to change site coords based on my current GPS location. 

Here is my reasoning on the "Pinned Note" icon. We are using the "paper with lines" in the FAB to indicate "Add Note" to the "notes feed" if you will. We are also using that icon on the Notes tab to indicate the place where notes feed is. The pinned note ("Site Instructions") is specifically the manager's note to the data collectors, and is seen on the manager's note on the Notes tab:
<img width="284" alt="Screenshot 2023-11-06 at 9 07 02 AM" src="https://github.com/techmatters/terraso-product/assets/8915145/8d3aba31-1de9-4a17-87a9-52b6fcd22116">

So, on the dashboard where I'm showing that pinned note button, it's meant to indicate that there is specifically a manager's instructions about the site/project, and that tapping that button will take you to the manager's pinned note. This is different than the data collector adding their own note. Using the same icon button to mean two different things will be confusing.

**Comment by ltseng** [comment]
Ah, that reasoning all makes sense. Thanks for explaining it to me! 

Location accuracy is one of those things that BLM asked for after seeing our first round of wireframes for the Location/Site dashboard, probably in the context of being able to move/edit the coordinates afterwards. From that lens, I'd be happy to move this piece of information wherever you think makes the most sense.

**Comment by ltseng** [comment]
Otherwise, I'm officially approving it!
