### ISSUE TITLE
Design UI for adding and deleting site notes

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#311]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Notes final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2237%3A17206&mode=design&t=ZCX9JKYtXVn0i4S9-1)

**Comment by CourtneyLee333** [comment]
@ltseng I left some comments on the wireframes for you.

**Comment by ltseng** [comment]
Couple minor comments, but looks good!

**Comment by CourtneyLee333** [comment]
I'm going to do a final design for this one before showing to stakeholders.

**Comment by CourtneyLee333** [comment]
Final design ready for review.

**Comment by ltseng** [comment]
Looks great!

**Comment by CourtneyLee333** [comment]
@ltseng I've updated this and plan to present it to BLM meeting tomorrow.

**Comment by ltseng** [comment]
Looks great! I'll add it to the agenda.

**Comment by CourtneyLee333** [comment]
Needs review by stakeholders.

**Comment by CourtneyLee333** [comment]
Updated per review and notes discussion.

**Comment by ltseng** [comment]
Left one comment

**Comment by Hanal-code** [comment]
@CourtneyLee333 One question about the Note -- how can user dismiss the virtual keyboard to reveal the Done button? 
I observed some usability study participants weren't aware how to dismiss the keyboard on mobile. So  I'm wondering if there is a way to show the Done button above the keyboard.

**Comment by CourtneyLee333** [comment]
@Hanal-code The Done button should always show above the keyboard. I have this on the agenda to talk about at the design patterns meeting tomorrow.

**Comment by ltseng** [comment]
![image](https://github.com/techmatters/terraso-product/assets/2730009/ec10418d-ca87-4132-8354-d5a3636d29c4)
@ajabeckett here is the linked frame for site notes

@CourtneyLee333 It looks like Aja doesn't have access to your Figma. Is that something you can fix?

**Comment by CourtneyLee333** [comment]
Aja had view access, but I just upgraded her to edit access.
