### ISSUE TITLE
Design UI for adding and deleting photos to sites

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#312]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Photos final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2523%3A14027&mode=design&t=874Ad8whS9zbrlbQ-1)

**Comment by CourtneyLee333** [comment]
@ltseng My concepts might need to evolve once engineers get into the camera and photo details.

**Comment by CourtneyLee333** [comment]
Waiting for feedback from stakeholders on the synthesis meeting notes, then will make final design to present to stakeholders.

**Comment by CourtneyLee333** [comment]
Final design updated per stakeholder review and notes discussion.

**Comment by ltseng** [comment]
Sorry, I thought I left this feedback already, only to realize I hadn't. Looks good!

**Comment by Hanal-code** [comment]
Reviewed and commented.

**Comment by CourtneyLee333** [comment]
@Hanal-code please un-assign this issue from yourself if my responses satisfy your review.

**Comment by Hanal-code** [comment]
Done
