### ISSUE TITLE
Design UI for Vertical Cracking

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#313]
[Site Dashboard: Soil](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1850%3A50097&mode=design&t=chBSqgwrUdCkuj7E-1)

**Comment by CourtneyLee333** [comment]
@ltseng Wireframe ready for your review [here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1128%3A38470&mode=design&t=fS8fNbnyePQ74XHN-1)

**Comment by ltseng** [comment]
One minor comment, but otherwise looks good
