### ISSUE TITLE
Replace select bottom sheet

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-product#317]
The NativeBase builtin Select component uses a bottom sheet to display the options. We may want to replace this with another option in the future.

**Comment by david-code** [comment]
> @david-code is this tech debt or new development?

More tech-debt, so I added the label. I also think Courtney might have made a separate issue for this as well.

**Comment by shrouxm** [comment]
didn't notice this existed when i made https://github.com/techmatters/terraso-mobile-client/issues/423, closing in favor of that one since it's a bit more fleshed out and in the right repo
