### ISSUE TITLE
Mockup location dashboards for usability test

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#321]
Site and non-site locations. Site needs privacy toggle.

[Site Dashboard](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1341%3A45860&mode=design&t=xyWIp4g9JSEQoVAS-1)
[Non-Site Dashboard](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1517%3A48049&mode=design&t=xyWIp4g9JSEQoVAS-1)

**Comment by ltseng** [comment]
Done!

**Comment by CourtneyLee333** [comment]
@Hanal-code @ltseng I've tagged you in the relevant Figma frames. Let me know your thoughts, then I can edit and get this to the engineers.

**Comment by CourtneyLee333** [comment]
The LCC question lingers.

**Comment by ltseng** [comment]
Sorry for the confusion, how is it now?

**Comment by CourtneyLee333** [comment]
@ltseng I added the direct links to the mockups in the issue description, if you want to assign this issue to the engineers.
