### ISSUE TITLE
Project completion status

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#328]
## User Story

- As a project member, I can view project completion status (rounded to the nearest integer) for the project in some central location for the project (e.g. the projects list cards) as calculated by the formula in [this spec](https://docs.google.com/document/d/1jWkO84GtzwuopdIHA3zh04mMsL2OcDIRrgbdL9mgmsU/edit#heading=h.sv2bzje1fmyw) - sum(completed sites)/total number of sites.

```[tasklist]
### Design
- [ ] Placeholder
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/71
```

```[tasklist]
### Back end
- [ ] Placeholder
```

## Acceptance criteria

- Whenever a site is marked completed, the project completion status should update accordingly.
- Whenever a site is changed from complete to incomplete, the project completion status should update accordingly.
- All project members should be able to view the project completion status.

## Resources
[Project and site completion status](https://docs.google.com/document/d/1jWkO84GtzwuopdIHA3zh04mMsL2OcDIRrgbdL9mgmsU/edit#heading=h.sv2bzje1fmyw)

**Comment by CourtneyLee333** [comment]
@ltseng I believe design work is done for this. Since we don't have a project main dashboard, the completion status shows on the project card and site cards. Let me know if something else is needed for now.I imagine some user testing after launch will help us to know if we need a project dashboard.

**Comment by DerekCaelin** [comment]
Might be needed, not currently planned.
