### ISSUE TITLE
Adding a site to a project

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#33]
## User Story

- As a user with permission to manage the site, I can set the site to be part of any project that I can edit. If I do not own the project, but choose to add my site to the project, I should be warned that I will lose ownership of the site after adding it to the project.

```[tasklist]
### Frontend
- [ ] https://github.com/techmatters/terraso-product/issues/78
- [ ] https://github.com/techmatters/terraso-product/issues/79
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/38
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/39
- [ ] https://github.com/techmatters/terraso-client-shared/issues/18
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/147
```

```[tasklist]
### Backend
- [ ] https://github.com/techmatters/terraso-backend/issues/402
```

## Acceptance criteria

- I can only add new or existing sites to projects that I have the Manager or Member role in, for sites that I manage
- I cannot see the option to add sites to projects I do not belong to
- If I add an existing site to a project, I should be warned that I will lose ownership of that site
- If I add a site to a project that shares a name with a site that's already in the project, the site should have (1) appended to its name (or (2), (3), etc. if necessary)

[Creating a site](https://docs.google.com/document/d/1vxITdvD9EOjOa92BG7iaSyv55iWZpNCKPDlJOh4sb2Q/edit#)
[Test Cases](https://docs.google.com/spreadsheets/d/1TJIe0ZGUsswrJ2a5lSdCVpbR72zG9Vngbl-dWBXeChs/edit#gid=2004954072)

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/513
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/525
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/546
```

**Comment by ltseng** [comment]
@david-code @shrouxm @JeancarloBarrios @CourtneyLee333 wanted to point out an important distinction that I may have previously left ambiguous for this task. I should only be able to add a site to a project if I manage the site. If I am a site contributor/viewer, I should not have the ability to add it to a project, even if I'm the manager on the project.

**Comment by CourtneyLee333** [comment]
@Hanal-code See Lillian's comment above - this is related to what we were talking about yesterday.

**Comment by CourtneyLee333** [comment]
@ltseng Hana and I got into a discussion yesterday about this. A scenario came to mind for me that could be problematic and I wonder if you think this is worth discussing:
- Rita has a site that she's been collecting data for. 
- Dave has a project that he manages. 
- Dave notices Rita's site would fit well in his project and asks Rita if she'll add the site to his project so they can work together.
- Rita agrees, and adds Dave as a manager to her site so he can transfer it. (Or, Dave adds Rita as a manager to the project so she can transfer it.)
- Once Rita's site is part  of Dave's project, Dave removes Rita from the project. 
- Dave submits and gets paid for Rita's data collection work.

**Comment by Hanal-code** [comment]
Another question from that scenario: How to reconcile the difference between the Site member list and the Project member list? Does Dave's project absorb/add the contributor/viewer member list to his project or remove them when adding the Rita's site?

**Comment by CourtneyLee333** [comment]
The site will inherit the member list of the project is gets transferred to.

**Comment by ltseng** [comment]
The above scenario that you identified is one that I am aware of, but my hope is that it's a low-probability one. Rita could always come to us to have the site restored to her, and the audit log will show the true history of the site.

**Comment by ltseng** [comment]
QA is done. There is one open issue for styling (just removing one of the Site Location options), but I have added that to another open user story for polishing up the app, so I'm closing this user story! 😁😁😁

**Comment by ltseng** [comment]
Functional testing is complete, but there are a couple bugs we need to resolve before I can fully close this story.
