### ISSUE TITLE
Design global dashboard for non-site location

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#339]
First step is to go through specs and fill out the [Mural board ](https://app.mural.co/t/techmatters9109/m/techmatters9109/1695926924529/96fa3d04031c1e7c69d0e7e0eff203ba21f1a698?sender=u7b3b2fb95ea53b5320ac3477)for differences between US and Global.

**Comment by DerekCaelin** [comment]
going to make a smaller user story.
