### ISSUE TITLE
Design error message for attempting to create a site outside of US territory

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#352]
There is no popover or dashboard, just the message dialog.

**Comment by CourtneyLee333** [comment]
@ltseng We can add a reference to the Int'l app when we launch it. For now, should we send them to the legacy version, or just not mention it?

**Comment by CourtneyLee333** [comment]
Oops, just realized I put my comments on the wrong issue.

**Comment by CourtneyLee333** [comment]
We already designed a dialog box when user taps a non-US location on the map. This error message will be a form field validation error when user enters coordinates in the site creation form:
"Location is outside of the US. The US version of LandPKS Soil ID can only be used for US locations."

**Comment by CourtneyLee333** [comment]
@ltseng Assigning this to you for review, but also, where should we document this for engineers?

**Comment by ltseng** [comment]
This message looks fine. If this message is documented in Figma, I will also put it in the overarching user story.
