### ISSUE TITLE
Design location popover for site outside of US territory

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#353]
[Dialog final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2547%3A10394&mode=design&t=cfc4uev8pRaFPXoD-1)

**Comment by CourtneyLee333** [comment]
@ltseng We can add a reference to the Int'l app when we launch it. For now, should we send them to the legacy version, or just not mention it?

**Comment by ltseng** [comment]
Hmm good question, especially since there's an iOS and an Android version of the legacy app to contend with. I almost would prefer to refer them to a knowledge base article that we can write and update independently of the app.

**Comment by CourtneyLee333** [comment]
Do you want to assign this to a later sprint, when we have that detail worked out? Or make a note somewhere to update this later?

**Comment by ltseng** [comment]
Let's not mention it right now and I'll make a note to update it later, so you can move forward with this task.
