### ISSUE TITLE
Design logout UI

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#355]
Bottom of hamburger menu. 

[Left side drawer menu final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=712%3A25892&mode=design&t=3ISjqX4ZWgkFfFIE-1)

**Comment by CourtneyLee333** [comment]
@ltseng The legacy app has a rather confusing sign-out message. Do we need to make everything explicit, or is it sufficient to just have a confirmation dialog box to Sign Out or Cancel? I assume that most people understand at this point that they can sign back into their account and their data will still be there.

**Comment by ltseng** [comment]
I think just a confirmation dialog box should be fine.

**Comment by ltseng** [comment]
I think when we start looking at the anonymous user case, where people can create sites and take data without ever creating an account, things may be tricky. For example, a user could create a site anonymously and then decide to either create an account (in which case we should save their data) or sign in to an existing account (and maybe they don't want to save their data? But then we couldn't save it for them when they sign out again of that account). Things could get weird then - but that's a future problem to wrangle.

**Comment by ltseng** [comment]
Looks great!

(and just a note for our future reference, archived projects and sites may be on the chopping block for me when it comes to things we have to sacrifice to get to releasing an MVP in December)
