### ISSUE TITLE
Design UI for Land Cover input

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#378]
This one is straightforward, no wireframe needed.

[Land tab final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2274%3A18885&mode=design&t=pcwP7cODPGQcFNfG-1)

**Comment by ltseng** [comment]
Love how straightforward this one was :) Looks great!

**Comment by ltseng** [comment]
I think we can skip presenting this one too
