### ISSUE TITLE
Design UI for Soil Limitations collection

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#379]
Likely don't need to wireframe this, and go straight to final design. 

[Soil Limitations final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2274%3A18885&mode=design&t=ZCX9JKYtXVn0i4S9-1)

**Comment by ltseng** [comment]
Looks good - we'll probably want to test the names, as discussed in Slack, as well as see to what degree we want to mention/explain LCC specifically in the international version of this screen.

**Comment by CourtneyLee333** [comment]
Prepared for stakeholder meeting.

**Comment by CourtneyLee333** [comment]
@ltseng updated per stakeholder review.

**Comment by ltseng** [comment]
Looks fine!
