### ISSUE TITLE
Revise language on homescreen cards for first time users

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#38]
Update the first-time view of the landscapes card on the home screen

### Context
- Be a user without any landscapes
- Go to app.terraso.org (home screen)
- Look at "Landscapes" card

## Current language:
`Explore the landscapes in Terraso. Become a member of your landscape to connect with others on Terraso and lets you share information. [CTA]`

## Updated Design

[Updated mockup with the new copy]
- Copy: `Connect with your landscape and share documents, data, and maps with your community.`
-  'Connect...'  links to `https://app.staging.terraso.net/landscapes`

![Image](https://github.com/techmatters/terraso-product/assets/10799815/49524755-d406-4b58-b9d4-745ee10847cf)

Visual asset (170px W x 128px H) 4px rounded : top-left & bottom-left corners. 
![Slice_ Landscapes Map](https://github.com/techmatters/terraso-product/assets/92342777/4926de08-21e4-47ea-847c-c0e877bf0348)

# Release criteria

## Product
- [x] As a user without a landscape, I want to see a call to action!

## Design
- [x] Copy edits
- [ ] Implemented according to design

## Enginering
- [ ] Translated to Spanish

Dependent on  https://github.com/techmatters/terraso-product/issues/84

**Comment by DerekCaelin** [comment]
I love this. `Find Your Landscape` is a good CTA.

**Comment by DerekCaelin** [comment]
@paulschreiber this is ready for your copy review.

**Comment by paulschreiber** [comment]
How about:
[Join your landscape](https://app.terraso.org/landscapes) and share documents, data and maps with your community.

**Comment by DerekCaelin** [comment]
I've run this by our 1000L partners - they suggest "connect" over "join". So, what about:

`Connect with your landscape and share documents, data, and maps with your community.`

**Comment by paulschreiber** [comment]
Works for me.

**Comment by DerekCaelin** [comment]
@Hanal-code OK by you?

**Comment by Hanal-code** [comment]
@DerekCaelin Yes.

**Comment by Hanal-code** [comment]
[Updated mockup with the new copy]
- Copy: `Connect with your landscape and share documents, data, and maps with your community.`
-  'Connect...'  links to `https://app.staging.terraso.net/landscapes`

<img width="591" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/a7edd0bc-d9d6-4f9e-a87f-32734c6115a1">

**popover open**
Copy: `Landscape is an interconnected, socio-ecological system influenced by distinct ecological, historical, economic and socio-cultural processes and activities.`
MUI: https://mui.com/material-ui/react-popover/
<img width="610" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/32e3cdfe-d79c-4413-af11-f190403f24f4">

**Comment by DerekCaelin** [comment]
@Hanal-code as we discussed I am separating the popover into a separate issue so we can refine it more.

**Comment by josebui** [comment]
Figma resources:
- https://www.figma.com/file/UeId7ECFT98cIXLtEHSK2G/Terraso_Hi-fi-mock?type=design&node-id=1321%3A2023&t=0Xl8wjU4R4q57kcV-1
- https://www.figma.com/file/UeId7ECFT98cIXLtEHSK2G/Terraso_Hi-fi-mock?type=design&version-id=3531978968&node-id=1142-4856&viewport=1270%2C-266%2C0.25&t=0Xl8wjU4R4q57kcV-0

**Comment by Hanal-code** [comment]
**Visual assets for Groups card and Story Maps card**
Image dimension: 170px W x 128px H,  4px rounded for top-left & bottom-left corners only. 

Group's image: 
![Groups Avatars](https://github.com/techmatters/terraso-product/assets/92342777/8fa86ec7-1e20-4434-a8f7-5e417c9fbc58)

Story Map's image:
PNG (@2x):
<img width="170" alt="Story_map" src="https://github.com/techmatters/terraso-product/assets/92342777/25d3e6a1-68ff-4092-ac40-1fdba0aca635">


**MOCKUP - Story Maps** 
<img width="572" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/874cf4bd-5548-4cf8-b3c4-9ef00b444b30">

Note the white caption 'Rocky Hill’s Story Map'  overlay

**Comment by paulschreiber** [comment]
I'm not sure what " in which people and nature live together" means. "A landscape is a territory defined by natural or administrative boundaries" seems fine.

**Comment by DerekCaelin** [comment]
The "people and nature live together" element is a simplification of the concept that humans derive a livelihood from socio-ecological systems; interacting with the land or water.  

So; a watershed without people is not a landscape.

**Comment by DerekCaelin** [comment]
Update now from the 1000L Comms team: the language they would like us to use is:
`"A landscape is a territory defined by natural or administrative boundaries, in which people and nature live together. It is influenced by ecological, historical, economic, and socio-cultural processes and activities that take place within and adjacent to the region."`

**Comment by Hanal-code** [comment]
@jodiezhuu Thx for working on this. I reviewed the build and found a few items to tweak.
1. Remove the rounded corners for top right and bottom right corners. `border-radius: 4px 0px 0px 4px;`
2. Remove borders for images. 
3. Remove extra space below the image. 
4. Adjust the text size to  `font-size: 1rem;`

**[screenshot]**
<img width="1012" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/d1ee2ed5-d1e7-420c-ab7f-0879e4f45bd9">

**Comment by DerekCaelin** [comment]
@jodiezhuu I think there is slight margin issue with this picture. The right margin appears to be 0, whereas the left is a few pixels. 
<img width="197" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/89a12c40-348a-45cf-99a1-239a6e8b7e5a">

**Comment by paulschreiber** [comment]
I've fixed the image. There are now 7px on each side (vs 14/0).

**Comment by jodiezhuu** [comment]
Thanks Paul! I'll merge it to staging

**Comment by jodiezhuu** [comment]
@Hanal-code I think the image is a bit pixelated, could you provide a different one? Also, I fixed the corner radius.

**Comment by Hanal-code** [comment]
@jodiezhuu Can you add margin between the edge and the image? `margin-left: 8px;` That will fix both left and right margin issues. 

**[current]**
<img width="551" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/ae70484a-b28e-4b1f-8566-37652ca315fc">
 
**[Mockup]**
<img width="549" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/aa08f7cd-0c9e-48be-adec-18caf0bd5421">

**Comment by Hanal-code** [comment]
@jodiezhuu Looks good. Thanks.
