### ISSUE TITLE
Searching and filtering projects, and sites within projects.

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#391]
## User Story

- As a user, I can search for projects that I am a member of by title.
- As a user, I can sort the list of projects I am a member of by project name, completion status, and date last updated
- As a user, I can filter the list of projects I am a part of by project role - Manager, Contributor, or Viewer.
- As a user, I can search for sites within projects that I am a part of by title (partial and complete match) and by notes
- As a user, I can sort sites within projects by site name, date last updated, site completion status, and distance from user's current location.

```[tasklist]
### Design
- [x] Complete, see [Figma final designs](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=165-21442&mode=design&t=0QiPOgmgAoLreGwG-0)
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/143
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/421
```

```[tasklist]
### Backend
- [ ] https://github.com/techmatters/terraso-backend/issues/868
```

## Acceptance criteria

- The list of projects can be searched by project name (partial or complete match)
  - This list can be sorted by project name, project completion status, and date last updated.
  - This list can be filtered by project role - Manager, Contributor, or Viewer
 - The list of sites within a single project can be searched by site name and by notes
   - This list can be sorted by site name, date last updated, site completion status, and distance from user's current location

## Resources
[Project management spec](https://docs.google.com/document/d/1Mo54pX4gbn0GWJfTOOvjA7TB41AgHOKYxEMSKtm3dOM/edit#)

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/690
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/689
```

**Comment by ltseng** [comment]
@shrouxm can you link your open PRs here, and create subissues for the remaining work?

**Comment by shrouxm** [comment]
@ltseng the old "Creating a project" user story mentioned that the project site list should be searchable by the site's notes, but the spec and this new user story only mention searching by name, is searching by notes a requirement for the project site list?

**Comment by ltseng** [comment]
Ah, thanks for catching that. Yes, these sites within a project should be searchable by notes too. I'll update the description above
