### ISSUE TITLE
Design Soil ID report for non-site

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#393]
```[tasklist]
- [x] Wireframes (if needed)
- [x] Final Design
```
[Location Soil ID](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4056%3A32229&mode=design&t=Gm2c8P18M7giThS7-1) final design

**Comment by CourtneyLee333** [comment]
Waiting for review of Site Soil ID by stakeholders.

**Comment by CourtneyLee333** [comment]
(waiting for answer to whether soil series breakdown belongs here)

**Comment by CourtneyLee333** [comment]
@ltseng Do you think this wireframe is approved? Or, should I put this on hold until we have some discussions in January?

**Comment by ltseng** [comment]
Let's put this on hold until we have those discussions in January

**Comment by CourtneyLee333** [comment]
@ltseng If I understand things correctly, the wireframes for Soil ID for temporary location dashboard should be ready to go. Do you agree?

**Comment by ltseng** [comment]
I think these should be set, yes!

**Comment by CourtneyLee333** [comment]
@ltseng Final design, including first draft of text, is linked above and ready for your review.

**Comment by ltseng** [comment]
This all has my approval, and has for a while :) Let's get Laura on reviewing the help text!
