### ISSUE TITLE
Design Ecological Site ID report for non-site

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#397]
[Location Dashboard wireframe](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3831%3A31600&mode=design&t=AiJ6mks96Ays9ZIw-1)

**Comment by CourtneyLee333** [comment]
(waiting for answer to whether soil series breakdown belongs here)

**Comment by CourtneyLee333** [comment]
@ltseng I'm marking this one as done for now, and we can make a new issue if needed after January discussions.

**Comment by ltseng** [comment]
Sounds good!
