### ISSUE TITLE
Design AWC report for site

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#400]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```

[Site AWC final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3811%3A71262&mode=design&t=HXMi1ZU7JU1fTCQs-1)

**Comment by CourtneyLee333** [comment]
@ltseng Reports are moving quickly now! AWC wireframes ready for your review.

**Comment by ltseng** [comment]
They should call you the Flash, cuz that was fast! ⚡ 

Looks great!

**Comment by CourtneyLee333** [comment]
@ltseng I made some minor changes after our review yesterday, if you want to review again.

**Comment by ltseng** [comment]
Still looks good!
