### ISSUE TITLE
Design AWC report for Toolbox

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#401]
- [x] Wireframe approved
- [ ] Final Design approved

[Toolbox AWC wireframe](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4008%3A32409&mode=design&t=3u40b63pWD0s2s2v-1) - there is an empty view and a results view.

**Comment by CourtneyLee333** [comment]
@ltseng The wireframe is ready for your review. Info sheet text TBD, but you can see the gist of what I plan to include. The idea is to put all the info for this tool in one place, rather than have multiple info and question mark icons.

**Comment by ltseng** [comment]
I think this will be perfect!

**Comment by CourtneyLee333** [comment]
Should present at next BLM meeting
