### ISSUE TITLE
Design Project Instructions field

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#404]
[WIP Project Data Inputs final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=165%3A21853&mode=design&t=1KGZTPp6EZfEp7lW-1)

**Comment by CourtneyLee333** [comment]
Not sure if "Site Notes" is the appropriate heading. User feedback will help.

**Comment by ltseng** [comment]
I left feedback on the Site Notes name as well as the Slope and Land naming in the [Playground](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2710-31333&mode=design&t=fM8LkdUF1G34Asb2-0)

**Comment by CourtneyLee333** [comment]
The plan is to finalize this in our spec review 10/3.
