### ISSUE TITLE
Site Creation workflow and design updates

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#406]
## Description
Updates to several screens and workflows based on UT1 findings. The study showed that upon creating a site through various methods, users wanted to immediately be able to verify the location. In this parent issue I am reworking the workflows and UIs to encourage the use of the map to verify location before creating the site. 

## Design Tasks
```[tasklist]
- [ ] https://github.com/techmatters/terraso-product/issues/407
- [ ] https://github.com/techmatters/terraso-product/issues/408
- [ ] https://github.com/techmatters/terraso-product/issues/409
- [ ] https://github.com/techmatters/terraso-product/issues/410
- [ ] https://github.com/techmatters/terraso-product/issues/411
- [ ] https://github.com/techmatters/terraso-product/issues/412
- [ ] https://github.com/techmatters/terraso-product/issues/413
```

```[tasklist]
### Front End
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/488
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/489
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/490
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/491
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/708
```

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/691
```

**Comment by CourtneyLee333** [comment]
@Hanal-code @ltseng I've only tagged you in this parent issue for a holistic view. Feel free to comment on this issue, the children, or both.

**Comment by Hanal-code** [comment]
@CourtneyLee333 My comments are added.

**Comment by CourtneyLee333** [comment]
@ltseng @Hanal-code I see Hana's comments, but none from Lillian. I'm not sure what you both think of the new workflow, and if this is approved or needs more work.

**Comment by ltseng** [comment]
I'm sorry, I missed this one! Left some clarifying comments, but largely approved.

**Comment by CourtneyLee333** [comment]
Needs design finalized and handed off to engineers.

**Comment by ltseng** [comment]
@CourtneyLee333 will you help me do Design QA on this?

**Comment by CourtneyLee333** [comment]
@ltseng Definitely. Do we have a spreadsheet or test cases document to work with?

**Comment by ltseng** [comment]
I haven't gotten around to writing one up. For Design QA, I was hoping you would tell me if the new screens matched your designs or not, and I could possibly revise some of the ones I used for the home screen, site creation, and project management user stories accordingly.

**Comment by ltseng** [comment]
@paulschreiber when you get back, I think we need to discuss this work. I had assumed that the Figma links in each of the design update tasks were what we wanted to build, only for Courtney to point out that they were the wrong links. As a result, Courtney has found a number of issues with the design updates, which you can view [here](https://docs.google.com/document/d/1IwLjAjOss07z1ush6X2gPh-NgAbQF1x3G0ZSsesSJS4/edit). Hopefully these are simple to fix!
