### ISSUE TITLE
Update Project Creation workflow

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#414]
The workflow of project creation needs some tweaking per the UT1. We noticed it was jarring when the user goes through the project creation form only to land on the project settings screen which seems to be an identical form. I've worked up a new flow that will meet Jeff's requirement of data privacy front and center, and that should be a less confusing process. 

[Project Creation playground](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2710%3A31333&mode=design&t=cutZLUAv4N20Jl95-1)

**Comment by CourtneyLee333** [comment]
@shrouxm @david-code Tagging you in this design update, pending review and approval.

**Comment by ltseng** [comment]
I left some comments, but those were more on the content of the project settings screen than on the workflow. The workflow itself looks good.

**Comment by Hanal-code** [comment]
@CourtneyLee333 My comments are added.

**Comment by CourtneyLee333** [comment]
Design needs to get transferred to Final Design page.
