### ISSUE TITLE
Delete user account

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#418]
To be accepted by the app store, users need a way to delete their accounts. 

## References

- https://developer.apple.com/support/offering-account-deletion-in-your-app/
- [Product Spec](https://docs.google.com/document/d/18t3V8KWm1wft7K66f91wwKfUQdwIQqJonFJszGaHGeM/edit#heading=h.b4eice3hjq0r)
- [Copy Document](https://docs.google.com/document/d/1gthFDYh2VyhjXao6aw9Na4kyhkzBv2kjXR3nXU-h9Rc/edit)
### Dependent upon
- https://github.com/techmatters/terraso-mobile-client/issues/1163
- [Delete Account Email Template](https://app.hubspot.com/templates/9151742)

## Designs
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13101&mode=design&t=ZTcIgD4vChShEXhu-0)

## Process
```[tasklist]
### Issues
- [x] Product task - write spec
- [x] Team Reviews design
- [x] Design Capri version of settings menu
- [ ] https://github.com/techmatters/terraso-product/issues/687
- [x] Write Copy For Deletion Experence
- [ ] https://github.com/techmatters/terraso-product/issues/698
- [ ] https://github.com/techmatters/terraso-product/issues/683
- [ ] https://github.com/techmatters/terraso-product/issues/751
- [ ] https://github.com/techmatters/terraso-product/issues/745
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1263
- [ ] https://github.com/techmatters/terraso-backend/issues/1112
- [x] https://github.com/techmatters/terraso-mobile-client/issues/1179
- [ ] https://github.com/techmatters/terraso-product/issues/761
```

## Acceptance Criteria 
- [ ] As a user I can go through a process to delete my account
   - [ ] I can push a button to start the deletion process
   - [ ] I can read about the consequences of my deleteion
   - [ ] I can confirm my intent
   - [ ] I see a notification confirming the process has begun
   - [x] https://github.com/techmatters/terraso-mobile-client/issues/1179
- [ ] Write a script that allows staff members to complete deletion. Script should
  - [ ] delete the user account
     - [ ] delete unaffiliated sites
     - [ ] delete projects and affiliated sites where the user is the sole manager
  - [ ] Use the hubspot template to inform the user their account has been deleted - [Delete Account Email Template](https://app.hubspot.com/templates/9151742)

- [ ] Deletion should not delete Terraso identity and things associated with it (story maps, shared files, groups, etc).
- [ ] Deletion should not remove the name of the user from notes attached to projects (or the future audit log).

**Comment by CourtneyLee333** [comment]
@DerekCaelin This is  a user story that needs engineering tasks made into issues and sized.

**Comment by DerekCaelin** [comment]
Closing this issue with the expectation we'll do QA before full launch, represented here: https://github.com/techmatters/terraso-product/issues/761
