### ISSUE TITLE
General map functionality

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#43]
## User Story

- As a user, upon first opening the app, I see a simple topographic map of the area around me within 500-1000 m of my location, oriented north-south by default (but I can rotate the map as needed).
- As a user, I should see my own orientation on the map (if possible) so I can determine which site I am facing
- As a user, I can change the map type between a simple topo base map and a satellite view.
- As a user, as I zoom out and pan around the map, I can see all sites I have access to - sites I manage, have contributor or viewer role in, as well as all sites belonging to projects where I have manager, contributor, or viewer role.
- ~As a user, I can visually distinguish whether a site:~
  - ~Has had no user data input~
  - ~Has had some user data input~
  - ~Has completed or not completed all the methods of user data input assigned (for projects with minimum data collection methods)~

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-product/issues/99
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/20
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/46
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/48
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/209
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/210
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/397
- [ ] https://github.com/techmatters/terraso-backend/issues/556
```

## Acceptance criteria

- If I am connected to data and my GPS is turned on when I first load the app, I should be able to see a topographic map of the area directly around me, along with some indicator of where I am on the map, and what direction I am facing.
- I should be able to interact with the map to zoom in and out on any location, as well as rotate it a full 360 degrees around me. 
- If I am connected to data, I should be able to change the map type between topographic and satellite view
- If I have created sites, have view/edit access to shared sites, or belong to a project with sites, I should be able to see all of them as I move around the map.
- If I am not connected to data upon loading the app for the first time, then show a simple vector map of the world immediately around me.
- If I am not connected to GPS upon loading the app, but am connected to data, use my device's IP address to determine my location
- If I am connected to neither GPS nor data, show the United States by default for all versions of the app.
- If I am connected to data, then I should be able to view the up-to-date status for all visible sites.
- If I am not connected to data, then I should see the most recent status (i.e. last connected to data) for all visible sites.
- I can search for locations by landmark (whatever Mapbox supports), lat/long, address, or by site name (partial or complete match)
- I can filter the sites visible to me by my role within the site, or by project association. If I filter sites by role, but the site belongs to a project, then use my role within the project as the filter criterion.

[Home Screen](https://docs.google.com/document/d/1weFSC4n4-yBXy2ejRoyXJBVbFYfujZD4oa9jSwkx73U/edit#)

[Test Cases](https://docs.google.com/spreadsheets/d/1wxnC5aQ0AI6xbNcRW6EvA7IFHTq6saLxbsT72K3TpnE/edit#gid=2004954072)

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/499
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/551
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/370
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/371
```

**Comment by ltseng** [comment]
Sounds good, and yes, let's use this for known issues as well. 

Tagging @CourtneyLee333 for awareness.

**Comment by CourtneyLee333** [comment]
Just to be clear, because I'm not sure we're all using the same terms, "cluster" to me is when map markers at different locations get grouped together into the circle thing as you zoom out to a level where the markers overlap. The chip shaped map marker is for when there are multiple map markers in exactly the same location. I hear the concerns, and am certainly open to figuring out a better way to handle it. Perhaps the same design pattern we use for select in other places, such as the picker wheel?
