### ISSUE TITLE
Finish Site Settings

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#435]
This user story will cover what we need to do to finish the Site Settings page. It will most likely involve removing the ability to share an individual site with other users.

## User Story

- As a site manager, I can achieve the following from the site settings page:
  - Change the site's name
  - Change the site's privacy
  - Delete the site
  - Add the site to a project 

```[tasklist]
### Design
- [ ] Placeholder
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/503
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/535
```

```[tasklist]
### Back end
- [ ] Placeholder
```

## Resources
No spec yet

**Comment by CourtneyLee333** [comment]
@ltseng I believe all design tasks are done for this one.

**Comment by ltseng** [comment]
Sounds good, thanks for checking!
