### ISSUE TITLE
Finalize login experience

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#436]
## User Story

- As a user, I can Sign in/Create an account with:
  - Google
  - Apple
  - Microsoft

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/356

```

```[tasklist]
### Front end
- [ ] Placeholder
```

```[tasklist]
### Back end
- [ ] Placeholder
```

## Acceptance criteria

- I can use Sign in with Google, Apple, or Microsoft to seamlessly log in to LandPKS
- If I sign in with one SSO mechanism, and then sign in with another, I should access my same LandPKS account (unless I elect to use Sign in with Apple's anonymous method)

**Comment by Hanal-code** [comment]
@ltseng  It sounds like it won't use the current Terraso SSO? No mention of Terraso account above. What's the update with the old plan of using the Terraso SSO?

**Comment by ltseng** [comment]
Correct, it looks like we're just going to add the buttons in directly to the LandPKS mobile app landing screen.

**Comment by Hanal-code** [comment]
@ltseng What's the thoughts on these scenarios? 
1)  LPKS app user tries to access the new LPKS web portal to download the LPKS dataset. 
2) Current Terraso user download  the new LPKS app (concern: users may not know the relationship between LPKS and Terraso)
3)  LPKS app user tries to access [Terraso](https://app.terraso.org/)  (concern: users may not know the relationship between LPKS and Terraso)

**Comment by ltseng** [comment]
@Hanal-code 

The only combination which should not work is if a user of the current LandPKS app tries to log in to the new LandPKS app, web portal, or Terraso web app with their old credentials. All others should work.

**Comment by Hanal-code** [comment]
@ltseng I have a few more questions: 

1. Does the LPKS account creation need explicit consent from the user that the credential(email & full name) will be shared with Terraso?  The explicit consent  = user selects some sort of 'I agree' button/input vs. implicit consent (by continuing the login steps, they are agreeing to share)   
2. Can you elaborate on the second bullet list item in the Acceptance criteria?  Do you mean User A can log in with Google or MS credentials to the same Terraso/LPKS account? I don't know if it's supported currently in the Terraso side. 

> _If I sign in with one SSO mechanism, and then sign in with another, I should access my same LandPKS account (unless I elect to use Sign in with Apple's anonymous method)_

**Comment by ltseng** [comment]
1. Yes, and that consent will typically be part of the consent screen that users see upon using any of the SSO options for the first time. See this example:

![2022-07-25-managed-consent-gcloud.gif](https://github.com/techmatters/terraso-product/assets/2730009/794f3001-2006-4b54-b0ea-cb200670d257)

2. As Paul confirmed in a recent meeting, that is how SSO works out of the box with the way Terraso has implemented things, so we shouldn't have to do anything out of the ordinary to achieve this outcome.

**Comment by Hanal-code** [comment]
@ltseng @CourtneyLee333 Can you review the workflow in Mural? I also have questions there as well. 
https://app.mural.co/t/techmatters9109/m/techmatters9109/1696887385627/1aa38a8214ba1d83087dd3b42e56c9d4b7c9a340?sender=ue3adfb39ae85b9ee50a94245
