### ISSUE TITLE
Design Climate Report

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#441]
- A bar graph of average rainfall by year for the last 40 years (mm/inches per year, depending on user setting)
- A bar graph of average rainfall by month (mm/inches per year, depending on user setting)
- A multiple line graph of average, low, and high temperature per month (F/C per year, depending on user setting)
- Average rainfall by year (Single number, mm/inches per year, depending on user setting)
- Average growing period length (Numeric range, days per year)
- Aridity index (Single number)

[Site Dashboard: Climate final design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3279%3A17407&mode=design&t=6xLD17EkbRCW939v-1)

**Comment by CourtneyLee333** [comment]
@ltseng Ready for your review! I'm expecting the charts to have the grids and dots and informational popovers like they have in the legacy app. I think I've laid out enough styles for the engineers, but can certainly produce more if they need it.

**Comment by ltseng** [comment]
Left a couple minor questions, but looks good otherwise!

**Comment by CourtneyLee333** [comment]
@ltseng The answer to both your questions is yes - that's what I meant in my comment above.

**Comment by ltseng** [comment]
Gotcha, thanks! Sorry, I didn't read the full comment before diving in either.

**Comment by ltseng** [comment]
What was her feedback?

**Comment by CourtneyLee333** [comment]
To not use a gradient since the colors aren't meaningful of anything. Also, I realized we need some border between bars to be able differentiate them when they are nearly the same height; they'd all run together otherwise.

**Comment by ltseng** [comment]
Ok, that makes sense. Thanks for the additional info!
