### ISSUE TITLE
Design soil series breakdown display on non-site dashboard

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#451]
[Soil Map Unit Composition](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4970%3A35805&mode=design&t=Gm2c8P18M7giThS7-1) final design

Note this screen has also been added to Site Dashboard.

**Comment by CourtneyLee333** [comment]
Questions in the spec, pending Lillian's return.

**Comment by ltseng** [comment]
@CourtneyLee333 can you link the specific frame above that I should be reviewing? Also for the engineers's reference when they get to this point.

**Comment by ltseng** [comment]
Ah, gotcha, thanks! I assumed we had talked about the above already.

> Is this the same as Soil ID matches? If not, does this breakdown belong in the main dashboard screen, or on the Soil ID screen? And does the soil map snapshot also belong on the main dashboard screen?

As discussed, these are not the same, as Soil ID will return matches from the current and adjacent map units. This one should only show the current map unit. This breakdown should probably be in the main dashboard screen as a result, and perhaps the soil map snapshot should be as well.

> What is the proper title for this information? "Map Unit Composition", "Soil Percentage Breakdown"?
Probably map unit composition

> This information can not be displayed if user is offline, correct?
Correct

**Comment by CourtneyLee333** [comment]
@ltseng Thanks. We did talk about these things but I was under the impression you were going to talk to Jon to make sure of my assumptions. I'll make a wireframe that we can present to BLM next week to make sure we're on the right track.

**Comment by ltseng** [comment]
I was, at the meeting with Jon this afternoon

**Comment by CourtneyLee333** [comment]
Ok great, I'll wait for you to fill me in on how it went.

**Comment by CourtneyLee333** [comment]
@ltseng Following up here...

**Comment by ltseng** [comment]
So sorry I forgot to respond! The answer is yes, we're right, and the location score is not the same as the soil series breakdown for a map unit.

**Comment by CourtneyLee333** [comment]
@ltseng I'm adding you as an assignee to this ticket so we keep it on the radar for January.

**Comment by CourtneyLee333** [comment]
@ltseng Final design, including first draft of text, is linked above and ready for your review.

**Comment by ltseng** [comment]
Happy with this for now. I've sent Laura the link to the help documentation tracker and the next Soil ID help text document.
