### ISSUE TITLE
Identify and fix inconsistencies with links

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#454]
Determine styles for:

- outbound links to browser
- internal links to other screens and webview content

[Links notes for engineers](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2647%3A10445&mode=design&t=dndvQF8yefLoHf3X-1)

**Comment by CourtneyLee333** [comment]
@paulschreiber I want to formalize our decisions about webview content and outbound links. What I gathered from our Slack comments is that you want all third party content to load in the app's webview, rather than opening in a browser. Is that right?

**Comment by CourtneyLee333** [comment]
Decision: open third party content that is relevant to soil, water, etc, in webview, as well as content from LandPKS. Create a message when that content won't load.

**Comment by CourtneyLee333** [comment]
Screens to update:

[App bar info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2066%3A93125&mode=design&t=dndvQF8yefLoHf3X-1)

[Data Privacy info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3809%3A67973&mode=design&t=dndvQF8yefLoHf3X-1) This one has a question for Lillian. 

@ltseng These are the only two screens that need the update, but the data privacy one has a question for you in figma.

**Comment by ltseng** [comment]
Do I need to create an engineering task for this?

**Comment by paulschreiber** [comment]
Two tasks, per above.
