### ISSUE TITLE
Loading icons for state changes

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#460]
## User Story

- As a user, I should see loading icons for any actions taken in the app upon loading, saving, or signing out, including, but not limited to:
  - Signing in
  - ~Loading Sites list~
  - ~Loading Projects list~ 
  - Saving data inputs (e.g. soil texture, photos, notes, etc)
  - Creating a site
  - Creating a project
  - Adding users to projects
  - Signing out

```[tasklist]
### Front end
- [ ] Placeholder
```

```[tasklist]
### Back end
- [ ] Placeholder
```

## Acceptance criteria

- As a user, I can see loading icons or animations for relevant actions taken in the app

**Comment by CourtneyLee333** [comment]
@DerekCaelin Shall we update the name of this to "loading indicator" or "progress indicator" to match the one we currently have for logging in?

**Comment by DerekCaelin** [comment]
Duplicate of other offline work notifications (possibly not needed)
