### ISSUE TITLE
Update LandPKS brand colors

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#461]
Finalize brand colors based on the new logo palette and Terraso colors. 

[Brand Colors Playground](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3652%3A9394&mode=design&t=EabkcDtvOn98tGgg-1)

**Comment by CourtneyLee333** [comment]
@ltseng @Hanal-code We aren't finished with the logo exercise for LandPKS, but it seems decided that we are going generally with some Terraso colors. I spent a little time yesterday developing a palette for the mobile app and would like your thoughts. I've applied the palette to some sample screens to demonstrate various components and how they look together.

**Comment by CourtneyLee333** [comment]
Actually, @ltseng @Hanal-code I'm going to work on this a bit more.

**Comment by CourtneyLee333** [comment]
Alright @ltseng and @Hanal-code I have the new color palette ready for review.

**Comment by ltseng** [comment]
I like the different shades of green you're using to indicate different states. I think the green-on-blue of the Site Dashboard tiles is where I'm having the most trouble adjusting, either to my perceived lack of color contrast (though I'm sure you've run it through a color contrast tool) or to the fact that it reminds me of a cartoon globe.

**Comment by ltseng** [comment]
A globe of the earth in cartoony style, like these:

![image](https://github.com/techmatters/terraso-product/assets/2730009/e7499855-c550-4589-a654-25fe5fac9710)

**Comment by CourtneyLee333** [comment]
Oh, that never occurred to me. Maybe a globe color palette isn't such a bad image to be conjured for this app? The contrast definitely meets accessibility standards. Could you say more about "trouble adjusting"?

**Comment by Hanal-code** [comment]
@CourtneyLee333 I think the latest color palette matches the brand identity. 
One suggestion I have is to explore the dark orange highlight to the bottom app bar to indicate the current selection.  
[Example]
![Image](https://github.com/techmatters/terraso-product/assets/92342777/cc69d591-3f73-4ab9-88fc-0fd72b696ff4)

**Comment by ltseng** [comment]
By "trouble adjusting," I mean that it stands out to me. It might not be a bad thing, to be honest. I'd like to run with this.

**Comment by CourtneyLee333** [comment]
Ok, good! I want it to stand out =) I want to draw attention to the "LandPKS magic" and set these elements apart from the more boring data entry and management type stuff. 

@Hanal-code the concept of indicating the current selection of the bottom navigation gets tricky, with the home screen in particular. For example, someone could be deep in the screens of a site, and the bottom tab indicator would show that they are in the home screen. Or, someone could go to a project and then go to a site within that project; in that case would they be in projects tab or home tab? The way the screens stack, so that back arrows and x to close the screen, is considered in my workflows. I'm not sure what app you've referenced in your screen shot, but it likely has a more simple navigation than LandPKS, or it uses sheets to cover the bottom tabs once you get beyond the top level screen. Maybe we should circle back to this conversation once we can play around with the build more.

**Comment by CourtneyLee333** [comment]
@Hanal-code I'm wondering about the other part of your suggestion about the orange in the bottom nav bar - would you like to see the green background go away, to help reduce the heavy amount of green around the app?

**Comment by Hanal-code** [comment]
@CourtneyLee333 I'd suggest exploring the bottom app bar background color.  It's nice to have the book ending at the top & bottom with the brand color, but it also can limit the possibility of using red color against green.

**Comment by Hanal-code** [comment]
BTW, the example above is the Amazon app.

**Comment by CourtneyLee333** [comment]
OK, Amazon seems to keep the active tab visible, even though you access the same content from different places. If we see an Amazon product as the equivalent to a LandPKS site, the active tab would for a site would either be Home or Projects depending on the path taken to get to the site. I'm fine to start with that direction, and see how it pans out in the app's other navigational elements (like back arrows and x to close.) We might need to do some refinement. 

Color-wise for the bottom tabs, I'm working on some variations and will ping you @Hanal-code to discuss.

**Comment by CourtneyLee333** [comment]
Yelp, on the other hand, when you open a business listing the bottom navigation shows no active tab.

**Comment by Hanal-code** [comment]
@CourtneyLee333 The task at hand is to set the LPKS brand color palette -- so I don't want to deviate the thread from that too much.  My suggestion was to utilize the accent color to indicate the current location. 


That said, here  I noticed three treatments of the current location indicator when looking around a few apps  1) adding an extra graphical element (e.g. bar) 2) changing color & bold  3) Adding a highlight. 
1) Bar: Amazon, Linkedin
[Linkedin]
<img width="188" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/f3172220-4460-4c71-9aac-261f084c4a7d">

2) Color: Yelp. Starbucks
<img width="177" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/e974b82e-e67e-444b-927b-e3307e4397d3">

3) Google Maps

**Comment by CourtneyLee333** [comment]
@ltseng This work is done, and I will release it with a new Figma version tomorrow.
