### ISSUE TITLE
Add location accuracy to GPS UI

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#463]

**Comment by CourtneyLee333** [comment]
When changing site coords after site is created? On location popover?

[Location popover playground](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3666%3A20469&mode=design&t=EabkcDtvOn98tGgg-1)

**Comment by CourtneyLee333** [comment]
@david-code @ajabeckett I need to add location accuracy to the UI when the user is using GPS to see the popover for their location. I don't understand how GPS is working in the app currently; I see the blue dot moving around a good bit so I assume GPS is trying to calibrate or something. Can you give me some insight as to what's happening and what the user needs to understand about the accuracy of the GPS? Do my designs seem feasible? I've included a screenshot for reference of Google maps when you drop a pin at your location.

**Comment by david-code** [comment]
> I don't understand how GPS is working in the app currently; I see the blue dot moving around a good bit so I assume GPS is trying to calibrate or something. Can you give me some insight as to what's happening and what the user needs to understand about the accuracy of the GPS? 

@CourtneyLee333 We get the location data from the Mapbox library we use, which in turn must access it from different data provided by the phone's operating system. I'm not sure about the jitter you're seeing, I don't have a great understanding about how the underlying system works. It may depend on your phone OS, mobile connection and whether you granted fine or coarse location information permission to the app. We should look more into this if the jitter doesn't go away and is distracting.


 As I understand it, the location accuracy of A should mean that the user's position should be within a circle with radius A from the latitude and longitude coordinates that are provided.

Let me know if there are any more questions you have, I'm not sure if that's at all helpful! Also I'm not sure @ajabeckett if you have any more experience with this area.

>  Do my designs seem feasible? I've included a screenshot for reference of Google maps when you drop a pin at your location.

Yes, the designs seem feasible. We receive the user location and location accuracy as soon as the user grants the app permission.

**Comment by CourtneyLee333** [comment]
@ltseng I think we already have a ticket going about the location blue dot moving around, including a screen cast I captured. But now I'm seeing the same behavior on Google Map app. It seems to just take some seconds for the GPS to hone in on the location. So maybe this is expected behavior? (Now the Terraso LandPKS is showing my location a couple dozen yards from where I actually am, once the blue dot settled after having moved around significantly.)

I think the concerns here are:
- When out in the field and creating a site, how will the user get enough confidence that the coordinates the map is using are "close enough" to the actual location?
- How will the user know the location dot on the map is done moving around and settled enough? (As I'm typing this, the blue dot just moved again, and is now closer to my actual location.)
- Should we expect that people concerned with very precise coordinates will have another GPS device to use that provides more accuracy? 

Maybe some of these are questions for BLM folks? It would be helpful to have the updated Site Creation process built, as well as being able to search the map for coordinates, to experiment with these elements and get some of our BLM folks also using them as well.
