### ISSUE TITLE
Update app bar, navigation bar

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#470]
[Navigation Bar style playground](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3759%3A11003&mode=design&t=EPLFMUh68P0R6LX6-1)

**Comment by CourtneyLee333** [comment]
Includes app bar color change as well, to the darker green, to help main green buttons stand out more.

**Comment by CourtneyLee333** [comment]
Navigation bar is the bottom one with Home/Projects/Toolbox. (It used to be called Bottom Tabs and then Bottom Navigation 🤪 )  I looked at a bunch of apps and definitely see the pattern of using back arrows to get to those top-level items rather than keeping the nav bar on all the screens. The point is to clean up the navigation for the user to know where they're at as well as make the "go back" action more linear. I will certainly update the Figma designs to match if this all sounds good to you.

**Comment by CourtneyLee333** [comment]
@ltseng Did you see the Figma playground for this, referenced in the issue description?

**Comment by ltseng** [comment]
I have now 😅 
Let's update the Figma designs accordingly!

**Comment by CourtneyLee333** [comment]
Running list, including notes for "App bar and nav bar updates" next to each section:
- [Home Screen](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=153%3A13795&mode=design&t=NAWJEpAKbZTSf1np-1)
- [Project Management](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=165%3A21442&mode=design&t=NAWJEpAKbZTSf1np-1)

**Comment by CourtneyLee333** [comment]
@ltseng This design work is now done, with notes next to each affected section in Figma.

**Comment by ltseng** [comment]
I'm going to update the engineering task with new Figma links for site creation, dashboard, and anything else I see your notes on.
