### ISSUE TITLE
Overlay sheets style consistency

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#475]
[Modal/Overlay Sheets](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2647%3A10445&mode=design&t=MBxxyC91pYvsoziC-1) - overview notes

**Comment by CourtneyLee333** [comment]
@ltseng Let's talk about this when you're back, in terms of the design decisions and how to implement.

**Comment by ltseng** [comment]
Okay, thank you for clarifying. Do you happen to have a list of all the sheets handy? I'd like to include it in the engineering issue that I create.

**Comment by CourtneyLee333** [comment]
I don't have one but can create one. Do you want a list of the links to the relevant Figma frames?

**Comment by ltseng** [comment]
That would be the most helpful, yes!

**Comment by CourtneyLee333** [comment]
Existing overlay sheets:

[App Bar Info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2066%3A93125&mode=design&t=MBxxyC91pYvsoziC-1)

[Home Map Data Layers sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3285%3A17534&mode=design&t=MBxxyC91pYvsoziC-1)

[Data Privacy info sheet sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3809%3A67973&mode=design&t=MBxxyC91pYvsoziC-1)

[Site Soil ID Soil Info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3803%3A23430&mode=design&t=MBxxyC91pYvsoziC-1)

[Site Soil ID (rate this match default)](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3800%3A22539&mode=design&t=MBxxyC91pYvsoziC-1)

[Site Soil ID (manual enter soil sheet)](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3800%3A22811&mode=design&t=MBxxyC91pYvsoziC-1)

[Data Input menu - 3 dots - modal sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2959%3A15748&mode=design&t=MBxxyC91pYvsoziC-1)

[Edit Depth Intervals modal sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2959%3A15885&mode=design&t=MBxxyC91pYvsoziC-1)

[Manager Pinned Note sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2523%3A10334&mode=design&t=MBxxyC91pYvsoziC-1)

[Data Input: Add Note sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2373%3A13938&mode=design&t=MBxxyC91pYvsoziC-1)

[Data Input: Add/View/Delete Single Photo sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2523%3A21202&mode=design&t=MBxxyC91pYvsoziC-1)

**Comment by CourtneyLee333** [comment]
@ltseng This is ready for you to send to engineers. I updated the ticket description to point to the notes in Figma. And I've listed all the relevant sheets in the previous comment.
