### ISSUE TITLE
Design warning for depth intervals when transferring sites to project

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#482]
[Transfer Sites dialog](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4422%3A20473&mode=design&t=n0DkTppczngwlINM-1)

**Comment by CourtneyLee333** [comment]
@ltseng How generic vs. specific do we need to be? For example, a generic message would be a warning that if sites have data entered at different depth intervals than what is specified in the project, that data will be deleted. A more specific route would be to show which sites fall into this category and let the user decide to deselect some, like this:


![Image](https://github.com/techmatters/terraso-product/assets/8915145/271e1b46-8343-4695-a43b-8118b5c7d0bc)

**Comment by ltseng** [comment]
I think we need to do the generic/low-effort thing for now

**Comment by CourtneyLee333** [comment]
@ltseng [Here is the warning.](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4422%3A20473&mode=design&t=n0DkTppczngwlINM-1) It seems that the messaging is getting a bit scattered between this dialog, the sentence on the Transfer Sites screen, and the tooltip. Should we rein all this in?

**Comment by ltseng** [comment]
No, I think that what you have is good and consistent, only surfacing the information that is correct for each context. Let's not add anything else if possible though!
