### ISSUE TITLE
Design error message for failed API refresh

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#485]
- [Climate Report ](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4518%3A11769&mode=design&t=0ARXehq8GA9y3bW5-1)- The offline message should display in place of the entire page content, after “Climate Report” header.
- [Location popover](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1065%3A38018&mode=design&t=0ARXehq8GA9y3bW5-1) - loading and offline messages
- [Dashboard report tiles](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1341%3A45860&mode=design&t=0ARXehq8GA9y3bW5-1) - empty state message for Soil ID and report tiles, other offline messages are sprinkled throughout the screens
- Map search - should display the simple term "Offline" in the search results area when user enters anything other than coordinates. 
- [Map view and soil map layers ](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4523%3A12377&mode=design&t=0ARXehq8GA9y3bW5-1)

**Comment by CourtneyLee333** [comment]
@shrouxm @david-code When the app is offline, is there a default behavior or message when user tries to search the map for a term? I'm assuming that searching the map won't work offline. 

Also, is there any issue with entering coordinates in the search bar while offline to drop a pin in that location on the map?

**Comment by ltseng** [comment]
There is no default error or behavior from Mapbox, so we will need to design some sort of default offline behavior for map search.

Coordinate search while offline does currently work.

**Comment by CourtneyLee333** [comment]
@ltseng How about [this message dialog](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4579%3A26333&mode=design&t=vAQXZjQuvFIXTdka-1) when the user taps the search bar?

**Comment by ltseng** [comment]
Added a comment
