### ISSUE TITLE
Design notification when user's site data has not synced yet

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#488]
- chip on card
- indicator on site itself

[Site Dashboard](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1341%3A45860&mode=design&t=gmmnDjcKMMFBNvFD-1) includes data sync error icon with tooltip. 

[Site card - data not synced](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4587%3A26522&mode=design&t=gmmnDjcKMMFBNvFD-1)

**Comment by CourtneyLee333** [comment]
@ltseng This one is ready for review too.

**Comment by ltseng** [comment]
Left a couple comments
