### ISSUE TITLE
Design notification when user's project data has not synced yet

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#489]
- [indicator on project card](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=165%3A14978&mode=design&t=gmmnDjcKMMFBNvFD-1)
- [Create Project Offline dialog](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4611%3A70838&mode=design&t=YqGFqIkc8AcE1yyq-1) When project is created offline and user taps SAVE, display the projects list with the “Create Project offline dialog” and the data sync error icon on the project card. 
- [Transfer Sites offline dialog](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4611%3A70861&mode=design&t=YqGFqIkc8AcE1yyq-1) When sites are transferred to a project offline and user taps TRANSFER, display the sites list with the “Transfer Sites offline dialog”. 
- [Add Site to Project offline dialog](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4611%3A70882&mode=design&t=YqGFqIkc8AcE1yyq-1)
- Snackbar for Inputs, Team, and Settings screen when offline: "Edits on this screen are not available offline." Form fields and actions should be disabled, except for the project download link. The snackbar will cover the save button, or display above it? We probably should talk with engineers when implementation time comes. 
- When a site is added to a project offline, the data sync error icon will appear on both the project card and the site card. This includes the site card on the Sites tab of the project. 
- And the same for transferring sites, where the icon will display on the origin project (if applicable) as well as the destination project.

**Comment by CourtneyLee333** [comment]
@ltseng Can you give me the list of what can or can't be done for project management while offline?

**Comment by ltseng** [comment]
I modified the project management spec and the syncing of data spec to reflect our last conversation, but pasting the list here:
- I can take and edit data collected for a site, e.g. texture, slope, photos, notes offline
- I can create a site offline and add it to a project
- I can create a project offline and add sites to it, whether new or pre-existing

I'm going to draw the line at editing a project's name/instructions/privacy, changing depth intervals/required data collection methods, and adding users.

**Comment by CourtneyLee333** [comment]
Perfect, thanks!

**Comment by CourtneyLee333** [comment]
@ltseng It seems that the entire Inputs, Team, and Settings screens should be non-editable while offline. I'm thinking to disable the forms and actions there (maybe keep project download link enabled?) and have a snackbar with the offline message on each screen. Does that sound reasonable to you?

**Comment by ltseng** [comment]
Yes, that sounds reasonable to me.

**Comment by CourtneyLee333** [comment]
@ltseng I think I've covered everything you and I discussed. Links are in the issue description.

**Comment by ltseng** [comment]
Looks good! Left one comment, which we may need to point out to engineers in the Github issue and the design.
