### ISSUE TITLE
Searching and filtering map view

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#49]
## User Story

- As a user, I can search for a location that’s relevant for me in a search bar (so that I can look up locations where I am not physically present)
  - search by the name applied to the site
  - search by keywords present in the site's notes
  - search for typical map locations (lat/long pairs, `country`, `region`, `city`, and `address` as defined in [Mapbox's API documentation](https://docs.mapbox.com/api/search/search-box/#administrative-unit-types))
- As a user, I can filter my list of visible sites by: 
  -  Project association
  - role (whether site or project role)

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/100
- [ ] https://github.com/techmatters/terraso-product/issues/101
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/42
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/45
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/124
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/421
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/422
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/370
```

## Acceptance criteria

- I can search for sites by name or notes keyword
- I can search for locations by lat/long pairs or broad location keyword, as specified in the first section
- I can filter sites by project association and by my role within the site.

[Home Screen](https://docs.google.com/document/d/1weFSC4n4-yBXy2ejRoyXJBVbFYfujZD4oa9jSwkx73U/edit#)
[Test Cases](https://docs.google.com/spreadsheets/d/1ApArxu-DMGYqp0l1xPlfxYVE9zd5SoC8MszeicXu4bw/edit#gid=2004954072)

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/675
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/676
```

**Comment by david-code** [comment]
Seems like the Search API is sorted based on the user's location, with the option to specify the coordinates specifically. I get different results when I change my IP address with a VPN.

**Comment by david-code** [comment]
[MapBox playground](https://docs.mapbox.com/playground/search-box/)
