### ISSUE TITLE
Produce assets for slope shape

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#494]
- [The assets folder](https://drive.google.com/drive/folders/1uCq_yBqLtATSCDf8FSIYtXbfg1Peis-X?usp=drive_link)
- should they be in 2 columns or 3 column display?

**Comment by CourtneyLee333** [comment]
@ltseng here you go.

**Comment by ltseng** [comment]
I'm not sure about the politics around image attribution. Let's ask Laura?

**Comment by CourtneyLee333** [comment]
Waiting on Laura for:
- attribution answers
- 2-column layout question asked in Slack

**Comment by CourtneyLee333** [comment]
We've decided to try the 3-column layout and let users zoom in on the images if needed.
