### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#498]
Full list of test cases for January sprint:

- [x] [Home screen sites list view](https://docs.google.com/spreadsheets/d/1IOh-ntQ-nYcZiEkUeDfZYTlx7MZ9XHLByw4y_a-43Ho/edit#gid=2004954072)
- [x] [Searching and filtering map view](https://docs.google.com/spreadsheets/d/1ApArxu-DMGYqp0l1xPlfxYVE9zd5SoC8MszeicXu4bw/edit?usp=drive_link)
- [x] [Searching and filtering projects, sites within projects](https://docs.google.com/spreadsheets/d/1MtbGbLZWrTwAPrHs00i8cffd94n662JQ_YOmtbgDIik/edit?usp=drive_link)
- [x] [Editing a project](https://docs.google.com/spreadsheets/d/1gse2CXz0cjf8m8NrLbs1bgajSEF2wRRtcVyvs4ywkA4/edit?usp=drive_link)
- [x] [Transferring sites between projects](https://docs.google.com/spreadsheets/d/1xlq1rFtj8p9W9xliZfehzP3nujJ6K9IT5rnd9c4_X64/edit#gid=2004954072)
- [x] [Adding users to projects](https://docs.google.com/spreadsheets/d/1QVwPYJoa7RsBV7seoW6cFCEx4kBhYa98Yke7LrkPUUI/edit?usp=drive_link)
- [x] [Changing user roles](https://docs.google.com/spreadsheets/d/13addSpWen8k38OpljVRdeDvXWQefhMnHzxF4m0vJZQo/edit?usp=drive_link)
- [x] [Adding notes to sites](https://docs.google.com/spreadsheets/d/1N6HwpawLuEY-ozfh2Ci3YEzRDf_CXCTrJzNIKQQLAKg/edit#gid=2004954072)
- [x] [Deleting a project](https://docs.google.com/spreadsheets/d/1vkBvEUu0-WIMA-D7Cob_f5H0NcupVh5S6JJQzOg2tYI/edit?usp=drive_link)

[Courtney's QA doc](https://docs.google.com/document/d/1mnFPTAO0jrYgI0A-pxqGxKGmCzyD3qC7UxVzBAEYZOw/edit?usp=sharing)

**Comment by CourtneyLee333** [comment]
Track them in a single big Google sheet with headings for each test case. Lillian will update the spreadsheets today.

**Comment by CourtneyLee333** [comment]
@ltseng I'll finish these up in the morning, but if you want to go ahead and look through you can find the link to my doc in the issue description.

**Comment by CourtneyLee333** [comment]
@ltseng I'm done, as far as I can with the iOS version being unusable for the most part.

**Comment by ltseng** [comment]
Super fast! Thank you.
