### ISSUE TITLE
Design hamburger menu

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#505]
[Sidenav](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5085%3A12411&mode=design&t=c93o6szYlgLkBknq-1) drawer

**Comment by CourtneyLee333** [comment]
@ltseng Super simple for now, expecting we'll add more after MVP. Ready for your review.

@Hanal-code Do you want to review this as well?

**Comment by Hanal-code** [comment]
@CourtneyLee333  Looks fine to me as well. However, I am wondering about the rationale behind the final decision for Units of Measurement options -- 'Metric' and 'English.' The wireframe had labels with examples.  e.g. cm, mm, and in, ft.

**Comment by CourtneyLee333** [comment]
@Hanal-code We got pushback from Paul on including those examples, so we opted to leave them out until we hear from users that they need more detail.
