### ISSUE TITLE
Design help documentation screen

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#507]
Help documentation - could it just be a link to [landpotential.org/knowledge](http://landpotential.org/knowledge) or whatever destination we decide to place the app documentation in?

[Help](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5100%3A12417&mode=design&t=c93o6szYlgLkBknq-1) screen

**Comment by CourtneyLee333** [comment]
@ltseng Once again, super simple for MVP. Ready for your review.

**Comment by ltseng** [comment]
Signed off!
