### ISSUE TITLE
Update old LandPKS app store descriptions

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#522]
**Needs to be done before January 27th**

Changes in [this document](https://docs.google.com/document/d/1M1vlY0Qq9CMiWg0S8tOdxjhkkYwh_25Lr-vTy6Ldpxs/edit) and copied below:

>  ***Special notice: LandPKS is currently being improved with additional features and streamlined workflows. Starting in 2024, we will be releasing the updated version as a new suite of apps that include US and global Soil ID, land monitoring, and a web-based dashboard. The legacy LandPKS app and your site data will remain available as we roll out the new apps.** 

- [x] Update Android app store description
- [ ] Update iOS app store description

**Comment by ltseng** [comment]
@paulschreiber any chance you can take this on before this Saturday (the 27th)?

**Comment by paulschreiber** [comment]
Android:  changes were submitted and approved.

iOS: Apple only lets you make changes to the description when you make a release. They did let me edit the promo text, but that is limited to 170 characters. It says:
>We will be releasing a new suite of apps for Soil ID, land monitoring starting in 2024. This version of the LandPKS app and your site data will remain available.
