### ISSUE TITLE
Update client while offline

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#523]
### Derek 2024/06/14 - plan to rewrite this with engineer based off offline research

Allow user to collect data and manipulate sites and projects while they are offline. Part of a broader epic, see parent for details. 

## References

```[tasklist]
### Components
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/802
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1361
```

## User Story
- As a user, I should be able to take the following actions while my device is not connected to data:
  - I can take and edit data collected for a site, e.g. texture, slope, photos, notes offline

**Comment by DerekCaelin** [comment]
Closing this to rewrite something fresh.
