### ISSUE TITLE
Design notification for when sync is in-progress

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#525]
Paul and I were discussing this when we were sizing #230 - the question arose of whether or not we needed to notify users when the app is actively syncing data, particularly if they are on a slow connection. I believe we had proceeded from the assumption that the actual sync process would be very quick, to the point where a user might not even notice any differences. However, Paul pointed out that a user could be on a slow connection, and actively uploading/downloading large photos, for example.

He presented two options:
1. notify the user every time we're syncing data -> quite noisy and unnecessary
2. notify the user whenever they're trying to edit data that is actively being updated.

Of the two, I think the second is the most reasonable, but let's talk through this @CourtneyLee333 before you spend any time on designing this interaction.

[Data Syncing playground ](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4866%3A26566&mode=design&t=Gm2c8P18M7giThS7-1)

**Comment by CourtneyLee333** [comment]
I think the second sounds most reasonable as well. Can it be as simple as a snackbar that displays on the relevant screen?

**Comment by ltseng** [comment]
I think so!

**Comment by CourtneyLee333** [comment]
Ok, let's have brief discussion at our 1:1.

**Comment by CourtneyLee333** [comment]
The team decided this is not MVP, and needs to wait until we have things working so we can explore the use cases and understand the problem better.

**Comment by CourtneyLee333** [comment]
@ltseng

**Comment by CourtneyLee333** [comment]
Noting that this issue needs research into best practices and existing solutions.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Most, if not all, of the design work is done. But I thought this was pulled from Capri. And I don't see this as being a subissue of a loading indicator, but maybe I'm confused.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 Looks like I miss-connected this issue to the user story - will detach.

**Comment by DerekCaelin** [comment]
We don't currently plan to do this. Will re-open if we do plan this enhancement.
