### ISSUE TITLE
Splash screen and app icon

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#542]
```[tasklist]
### Tasks
- [x] Produce app icons
- [x] Produce splash screen
```
[App icons are in this folder.](https://drive.google.com/drive/folders/1w93-X9D8AA_d3Oqqs7DYl17l7M2McFi_?usp=drive_link) Note that adaptive icons for Android are included.

[Splash screen prototype](https://www.figma.com/file/h4xdqfTq1c84YEn6AZcfHf/Splash-Screen-to-Log-In-Animation?type=design&node-id=0%3A1&mode=design&t=h8OC7wMVogzI6zzf-1), including animations into the login screen and into the home screen. If you don't know how to play the animations I can show you. 

I'm not exactly sure what assets engineers will need to build the splash screen, so just let me know what you need!

**Comment by CourtneyLee333** [comment]
@ltseng @paulschreiber Please note that in addition to the various sizes for Android, the current standard is to use the adaptive icon https://developer.android.com/develop/ui/views/launch/icon_design_adaptive 

I've included the assets needed for adaptive icon.

**Comment by ltseng** [comment]
I'm not going to close this task out since the splash screen is not complete yet, but I will make a comment in https://github.com/techmatters/terraso-mobile-client/issues/866 that this is ready to take on.

**Comment by CourtneyLee333** [comment]
@ltseng It would be good to get a review of this from an engineer, to see whether it's feasible or not to do the animation. Then I can produce the assets accordingly.

**Comment by CourtneyLee333** [comment]
@Hanal-code @ltseng I've updated the splash animation into the login screen to be more subtle. I've also added one for splash screen into the home screen for the logged-in experience.

My purpose for using animation is to subtly convey the quality of professionalism, sleek-ness, of the new app. I want our new users to feel a little bit of excitement at their first impression. 

Animation has been sparsely incorporated into the rest of the app in the form of screen and overlay transitions - subtle dissolves, and moving up/down and left/right. There is the potential to add more, such as animating numbers changing as Soil ID top matches get updated, but that's more sophisticated and not MVP. 

Please let me know what you think of this. 

[Here is the splash animation into log-in screen. ](https://drive.google.com/file/d/1EO2dyGl-LVGTjrxPJYGTNlI79O7StUlN/view?usp=sharing)

[Here is the splash animation into home screen. ](https://drive.google.com/file/d/1dnHzwJEKhph31YpNM2V6HvWsFevyxgZj/view?usp=sharing)

**Comment by ltseng** [comment]
Love it!

**Comment by Hanal-code** [comment]
@CourtneyLee333  re: splash animation. 
- The subtle animation looks more aligned with brand attributes than the bounciness of the initial mockup. 
- The dissolve transition to the map in the home screen looks nice. 

Splash screen animation is not critical to the release, so no need to aim for perfection, but here are a couple of thoughts: 
- The logo feels a little too big in the first frame. Because it's a landscape scene image in a circle, keeping it to around 1/3 of the screen width feels more comfortable.
-  Showing 'Powered by Terraso' in the third segment emphasizes the message and makes it the splash longer. Is it necessary?

**Comment by CourtneyLee333** [comment]
Thank you! @Hanal-code I can reduce the logo in the splash screen. However, that means it will be the same size as it is in the login screen, so the shrinking effect won't happen. [Here it is](https://www.figma.com/proto/h4xdqfTq1c84YEn6AZcfHf/Splash-Screen-to-Log-In-Animation?node-id=0%3A1&scaling=scale-down&starting-point-node-id=2%3A36), let me know what you think.

The "Powered by Terraso" animation isn't part of the splash screen; it's on the login screen. The login screen will be usable while that animation is happening, so it doesn't prevent any actions. Is it necessary? No, but the subtle emphasizing of Terraso could be useful, as Terraso is an important new foundational piece of LandPKS. Maybe less of a delay would be better?
