### ISSUE TITLE
Design and build a template in Hubspot for LandPKS newsletter

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#556]
[Newsletter preview](https://techmatters-9151742.hs-sites.com/landpks-partners-with-terraso-to-build-new-and-improved-suite-of-apps?hs_preview=qvbvwAoV-162323297718)

Will need this info sorted out in the settings tab:

![Image](https://github.com/techmatters/terraso-product/assets/8915145/90e6b7af-4f2e-4f24-a136-36411c37cfee)

**Comment by CourtneyLee333** [comment]
@ltseng Ready for your review!

**Comment by ltseng** [comment]
I'm unable to view the newsletter preview. Can you put a screenshot in?

![Uploading image.png…]()

**Comment by CourtneyLee333** [comment]
@ltseng That's weird. It works for me, even logged out of Hubspot and in a private browser. And the error message references an email address which doesn't make sense. Will you try that link again, just so I know whether it was a glitch or something else is going on?

In the meantime, here you go...

![Screenshot 2024-03-28 at 09-07-30 LandPKS partners with Terraso to build new and improved suite of apps](https://github.com/techmatters/terraso-product/assets/8915145/2f5336b8-cec2-4206-bfa2-435794b30b57)

**Comment by ltseng** [comment]
I skipped showing you a step in between which asked me to log in. I tried Google SSO, which led me to the error page I showed you before.

Thanks for the screenshot, it looks great!

**Comment by CourtneyLee333** [comment]
@Hanal-code Here is the template I've designed for this first newsletter. I kept consistent with many of the styles from the Terraso newsletters.

**Comment by Hanal-code** [comment]
@CourtneyLee333 I had difficulty with Hotpot login and also viewing the image as well (screenshot below).  Can you attach the screenshot here? 
[error]
<img width="320" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/8d6a1674-ab89-4e85-9436-32e9a1919abe">

**Comment by Hanal-code** [comment]
@CourtneyLee333 The newsletter looks good. Nice job on the photo editing - a sneak peek of the new LPKS UI!
