### ISSUE TITLE
Messaging for site with no soil map data

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#557]
It has come to our attention that there is no soil map data for tribal lands. We already knew that there is none for military bases. Currently we have a message for when no soil map data is available in Soil ID screens. We need to add:
- [ ] a message on the map popover when there is no soil map data
- [ ] messaging about why the data not available

NOTPUB = the tribe or governing entity has requested the data not be published publicly. We can determine this and display the appropriate message.

Ute tribal land shows as NOTCOM. Why? I've asked. Seems some wilderness/conservation areas as well show as NOTCOM

**Comment by CourtneyLee333** [comment]
@hamriclr For the piece here about what to display on the location popover when no soil data is available, what do you think the wording should be for Soil ID Top Match and ESD Top Match? "No data available" "No soil data"... something else? We'll explain more why this might be the case in other places where there is more room. Attached image shows the popover with information and the popover with loading and offline messaging. 


![Image](https://github.com/techmatters/terraso-product/assets/8915145/70280e25-2c98-432e-9959-532988e5eff2)

**Comment by ltseng** [comment]
In the case where soil map data is NOTCOM or NOTPUB, we can provide the following link to a list of state soil scientists. That way, they can go bug them for the soil map data, if it's available.
https://www.nrcs.usda.gov/conservation-basics/natural-resource-concerns/soils/state-soil-scientists

**Comment by hamriclr** [comment]
I added some [language for NOTPUB and NOTCOM here] (https://docs.google.com/document/d/1qRvfXfjKkoKAXl3jGeDwlRMXw3rYbvJc5ciY06Ehbqw/edit) for the No Soil Map Data popup message.

**Comment by hamriclr** [comment]
In terms of language for the location popover, maybe "Not Available"? I worry that using "Data" here (as in "Data not available") might be confusing since it could be misinterpreted as "no user-collected data has been taken, so we can't generate a soil ID for you". 

If we could make the "Not available" clickable to show the popup with an explanation of why the data is not available, that would be good too, especially for NOTPUB data.

**Comment by CourtneyLee333** [comment]
For the map popover I used "No matches" to keep it distinct from "Not available offline". "No matches" can display for both Soil ID and ESD. Having a clickable icon to show more about that message on the popover, however, doesn't work. 

![Image](https://github.com/techmatters/terraso-product/assets/8915145/2022bb9f-839b-45b5-8690-fbcdcfe777b0)

**Comment by CourtneyLee333** [comment]
It will look like this on the Site Dashboard:

![Image](https://github.com/techmatters/terraso-product/assets/8915145/46fb1362-cf7d-4b9e-b991-3e4d1184d497)

**Comment by CourtneyLee333** [comment]
And here is the messaging for the Soil ID screen:

![Image](https://github.com/techmatters/terraso-product/assets/8915145/57b1e173-3e4f-49ff-8d38-6ff4fb14e69e)

**Comment by CourtneyLee333** [comment]
@ltseng ready for your review!

**Comment by ltseng** [comment]
This makes sense! Thanks for including the screenshots as well. Do you need me to copy anything into the Soil ID help text doc?

**Comment by CourtneyLee333** [comment]
The help text doc matches what is here, I edited in both places.
