### ISSUE TITLE
Create database flags for accessing 1000L web app vs. LPKS mobile app

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#567]
If there is ever a security breach of the LandPKS mobile app, or of the Terraso web app, we want to be able to identify separate groups of users and notify them of actions to be taken

TBD: need automated process or script for getting users out of Terraso database and getting them into Hubspot, well in advance of any incident.

**Comment by paulschreiber** [comment]
No longer needed.

**Comment by paulschreiber** [comment]
We can't think of a case where we wouldn't notify all users.
