### ISSUE TITLE
Add links to web portal

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#569]
Links added to two places:

[Side drawer menu](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5085%3A12411&mode=design&t=UQFNZL6CHleoRqgC-1)

[Home screen app bar info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2066%3A93125&mode=design&t=UQFNZL6CHleoRqgC-1)

**Comment by CourtneyLee333** [comment]
@ltseng These are the two places we talked about adding the link to for now.

**Comment by ltseng** [comment]
Looks good, and I like the names you've settled on!

**Comment by CourtneyLee333** [comment]
Well, I haven't settled on any names, just going with what we're currently using rather than go into it deeper for now.
