### ISSUE TITLE
Add newsletter subscribe to side drawer menu

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#570]
Include a way for users to subscribe to LandPKS marketing email list. 

[User Settings screen](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5081%3A12379&mode=design&t=2zp26HKhDlS3YReR-1)

**Comment by CourtneyLee333** [comment]
@paulschreiber @shrouxm What are my options for this? Some things that come to mind are:

- a link to a URL that has the form
- a sign-up form in the app
- a checkbox that would do the work of subscribing and unsubscribing

**Comment by ltseng** [comment]
If we assume that the user always wants to use the email on the same account they're logged in with, a checkbox is doable and preferable.
