### ISSUE TITLE
Update soil color guide text

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#572]
It's come to our attention that images can get quite pixelated when cropping in from a far zoom on soil and reference card. We need to add some instructions for this:

- Tell the user to take the photo as close to the subject matter as possible without casting shadows are getting blurry.
- Tell the user to crop to a section that includes as many as the colors as possible on both the soil and the reference card. I think that would make sense, to get an average of different colored pixels.

**Comment by CourtneyLee333** [comment]
@ltseng I added text to the soil and reference card cropping instructions [here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4075%3A32790&mode=design&t=erR5v5fO1PmMyPZD-1). 

And I added a step to the photo method guide for composing the photo [here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4075%3A32825&mode=design&t=erR5v5fO1PmMyPZD-1).

**Comment by ltseng** [comment]
I left a comment on an unrelated instruction, but this looks good to me!
