### ISSUE TITLE
Design experience for unexpected soil colors

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#576]
## Problem

The legacy LandPKS app does the following:
- Allows users to manually input Munsell values from a narrow, defined range
  - Hue (split into two separate dropdown menus)
    - 2.5, 5, 7.5, 10
    - R, YR, Y, GY, G, B, BG 
  - Value :
    - 2.5, 3, 4, 5, 6, 7, 8, 8.5, 9, 9.5
  - Chroma
    - 1, 2, 3, 4, 5, 6, 7, 8
- Allows users to take photos of soil using various color references, which returns an RGB value, which is then converted to a Munsell value. This value is not restricted to the same narrow range as the manual input side.

It's entirely possible for users to take photos of random things around them while testing out the app, and receiving unexpected values, like neon pink or baby blue (I currently have a possible output of 10RP 23/20 in one of my test sites, for example). Looking forward to the future, we want to make sure that we have good data in our database, and are sending good data to WOSIS and LDC. 

## Proposed Solution

The paths for the proposed solution depend on whether or not Jon can help us find a database of valid Munsell values.

Manual input
- Add as many values to hue, chroma, and value as needed to exactly match what is available in the Munsell color book.
  - If the database exists - force the user to choose the most restrictive piece of the Munsell color first (I think it's the alphabetic piece of Hue, such as YR), and then limit the possible set of other values for the rest of the Munsell color inputs accordingly.
  - If the database doesn't exist - then we allow all possible combinations of Hue, Value, and Chroma, and figure out invalid values later when it comes time to send data to LDC/WOSIS

Photo identification algorithm
- If the database exists - when the color algorithm returns a color that doesn't match the expected range, tell the user that the soil is not in the range, and give them a chance to correct it to one that is in the expected range, either 1) providing them help text telling them to check their photo lighting conditions (easier), or 2) by allowing them to directly modify the value returned by the photo algorithm (harder?). It is not required for them to modify the value or retake the photo, and if they do not, the app should go ahead and save the Munsell value returned by the photo algorithm.
- If the database doesn't exist - then just save whatever is returned by the soil color algorithm.

**Comment by ltseng** [comment]
@paulschreiber @shrouxm and @CourtneyLee333 I've created this design task from the soil color discussion that we had earlier this week. Please review and let me know if this seems accurate. I know we're still waiting to hear back from Jon before we decide which variant of this experience to design.

**Comment by shrouxm** [comment]
my only accuracy note is that i thought we decided that regardless of the existence of the database we will still do the first variant, just if we don't have a database there'll be some colors that aren't in the book we accept (but still many colors we'll be able to exclude)

**Comment by ltseng** [comment]
Just to be clear, by first variant, do you mean:

> If the database exists - when the color algorithm returns a color that doesn't match the expected range, tell the user that the soil is not in the range, and give them a chance to correct it to one that is in the expected range, either 1) providing them help text telling them to check their photo lighting conditions (easier), or 2) by allowing them to directly modify the value returned by the photo algorithm (harder?). It is not required for them to modify the value or retake the photo, and if they do not, the app should go ahead and save the Munsell value returned by the photo algorithm.

If so, that's fine, I suppose it should be possible for us to exclude pastel green and neon blue, for example? And if you're able to normalize values returned by the soil color photo algorithm to the closest Munsell value without much effort, that would be fine too!

**Comment by shrouxm** [comment]
yeah! i'm not sure which colors exactly it would exclude, but i imagine it'll include some colors that seem nonsensical for soils. the only way to programmatically exclude _all_ the colors that are nonsensical for soils would be to use a table of which colors are in the book

**Comment by shrouxm** [comment]
maybe a better way to say it is, it will show a warning for any color that couldn't be manually input. but with the current implementation that was following the original spec, you can manually input e.g. the following color: 
![image](https://github.com/techmatters/terraso-product/assets/3411715/cfb540a2-614b-4f47-adaf-4191e5765634)

if we had a database, we could exclude that color both from manual input and the color algorithm. if jon can't turn up a database and we think it's important to have guard rails for this case, we could bother about manually creating one, it'd just be a tedious and error-prone endeavor

**Comment by DerekCaelin** [comment]
We've done this: 

![Image](https://github.com/user-attachments/assets/41923449-5d38-4b51-a906-3ecd088d9d7e)
