### ISSUE TITLE
Photoshop image for blog post

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#583]
[FINAL IMAGE](https://drive.google.com/file/d/1RYwZgCWookswTTlqipae_BnJY71acTOo/view?usp=sharing)

[Folder of images here](https://drive.google.com/drive/folders/1EXDEjnQYMt1ESZhaTCmGNHfC8Pe0wbU3)

For [this blog post](https://docs.google.com/document/d/120tPPl21MR5peuVbNGXALt4GjYx3w5zyB9u2bpvqtCg/edit)

**Comment by CourtneyLee333** [comment]
@ltseng I'm thinking to use the Soil tab screen to show the improved layout and visible results. Can you give me some practical data to put in for these inputs?

![Image](https://github.com/techmatters/terraso-product/assets/8915145/e0fa94ed-4b7d-497b-98ba-9819876e2298)

**Comment by ltseng** [comment]
Made this according to the description for the Niwot soil series, which is a possible soil found in Boulder

![Screenshot_20240325-201759_Terraso LandPKS.jpg](https://github.com/techmatters/terraso-product/assets/2730009/0baa181f-f6a7-41ae-a7a5-0ee9d05e25a0)
