### ISSUE TITLE
Create a message for phone with no accelerometer

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#584]
[See comment thread in Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1930%3A19309&mode=design&t=5nO4C78kWuuYL7aG-1)

**Comment by CourtneyLee333** [comment]
@ltseng Do you consider this Slim MVP, backlog, or something else?

**Comment by ltseng** [comment]
Slim MVP
