### ISSUE TITLE
Create LandPKS + Terraso logo

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#586]
LandPKS + Terraso logo [Mural](https://app.mural.co/t/techmatters9109/m/techmatters9109/1686787792238/f3f925dc26754a4305f6d2458d1cef665f2ab569?wid=0-1711389973041)

[Round 2 exploration in Mural](https://app.mural.co/t/techmatters9109/m/techmatters9109/1686787792238/f3f925dc26754a4305f6d2458d1cef665f2ab569?wid=0-1711566198561)

[Final logo assets](https://drive.google.com/drive/folders/1SVFpAd-y3pQottL1QKFXkOZSoFgmXpOu?usp=drive_link)

**Comment by CourtneyLee333** [comment]
@ltseng The next round is ready for review.

**Comment by ltseng** [comment]
In the first column, I like the size of the TM in the first option the most, and the color of "from Terraso" in the third and last options because they are more subtle.

In the second column, I like the second and third options best. The only difference is the size of "from," right?

**Comment by CourtneyLee333** [comment]
Yes, the size and positioning of "from". I think our comments are best handled in the group meeting. I put the ticket in review so you know it's ready to discuss.

**Comment by ltseng** [comment]
Gotcha, thank you!

**Comment by CourtneyLee333** [comment]
Need to produce final assets.
