### ISSUE TITLE
Draft newsletter requesting LandPKS Usability Testers

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#592]
Draft newsletter: https://docs.google.com/document/d/17r6quEne44IR8LXAAGMZb5vEQFsTq2QTSL8ShaOXNMA/edit

**Comment by ltseng** [comment]
@DerekCaelin and @CourtneyLee333  do you think an additional newsletter is necessary for the LandPKS announcement, specifically for the Terraso newsletter?

**Comment by CourtneyLee333** [comment]
I don't have an opinion.

**Comment by DerekCaelin** [comment]
After talking with @CourtneyLee333 and marketing team, we're holding off on this letter in favor of direct recruitment for now. Will send it out later.
