### ISSUE TITLE
Design some UI for unexpected soil color values

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#593]
The color algorithm currently fails silently if a color is returned outside of what we consider a valid munsell soil color. We should instead show a modal displaying the computed color and informing the user what has happened, and offer them the choice to either proceed with the algorithm's value anyway, or offer them the closest valid munsell soil color to the color the algorithm returned.

[The dialog box.](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5691%3A13153&mode=design&t=erR5v5fO1PmMyPZD-1)

**Comment by CourtneyLee333** [comment]
@shrouxm I'm curious, how will you determine the closest valid munsell soil color to the color the algorithm returned?

**Comment by shrouxm** [comment]
I think there are few enough colors that we can directly compute the distance between the color the algo returned and every possible color in the munsell color space and return the one with the least distance! That should involve significantly less computation than we're already doing to compute the color in the first place, but I'll let you know if these assumptions don't end up making sense.

**Comment by CourtneyLee333** [comment]
@ltseng and @shrouxm Please check my design and let me know if this is what you expected.

**Comment by ltseng** [comment]
Looks good to me!

**Comment by shrouxm** [comment]
@CourtneyLee333 perfect, ty! i think the "unable to identify soil color" dialog can be removed from the figma now, superseded by this

**Comment by CourtneyLee333** [comment]
Alright, that makes sense since we also have the generic technical error dialog.
