### ISSUE TITLE
Review help content for slope

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#618]
Review Slope help content in this doc:
https://docs.google.com/document/d/1zYIfmnZSlksfbZyFE_zE61dcAo-GxTyVu3CoRevcqoU/edit

```[tasklist]
### sections
- [x] Slope Info Sheet
- [x] How to use Slope Meter
- [x] Slope Shape Info Sheet
- [x] Slope Aspect (info sheet)
- [x] Landscape Position (info sheet)
```

Note: The text as of 4/15 is implemented in [Capri](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13582&mode=design&t=itFRWV4FgAozh9Wl-0)

**Comment by hamriclr** [comment]
The only lingering (probably non-Capri) items are:

- adding one or two illustrations to the Slope Meter instructions (and/or a link to the section of the Toolbox video where this is demonstrated, or a new help document we create)
- maybe adding an illustration to the Slope Shape info sheet - the text still feels a little overwhelming but it's hard to describe efficiently in words.

**Comment by DerekCaelin** [comment]
Noted, and thank you. We can revisit enhancements for this design post capri.
