### ISSUE TITLE
Write process doc for LandPKS support

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#629]
Write a low-fidelity process manual that allows Laura, Derek, and Max to process support requests coming in for LandPKS.

## Reference
[LandPKS Support Process](https://docs.google.com/document/d/1Y1nmC2zxkRk9P4i_eK4Cgmb3uXKOkTHGY1ZCg6dNtuM/edit#heading=h.7h4vheie87vp)

## Documentation includes
- [x] How to label, rename, and assign support requests 
- [x] Process for addressing support requests and when to close tickets

**Comment by hamriclr** [comment]
Remaining question: should we set up Hubspot email integration or not? Once this is resolved, can close out.

**Comment by DerekCaelin** [comment]
Laura and I met and decided "no"!
