### ISSUE TITLE
Configure hubspot for processing LandPKS support requests

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#630]
In Hubspot ticketing system:
- [x] Set default columns -- not an option for Hubspot, but put list of recommended order in guidance document
- [x] configure views of the support ticket
- [ ] Get Contact submissions routed to tickets

**Comment by hamriclr** [comment]
@DerekCaelin I'm wrapping up on this for today but I'm not sure that there is a way to set a global custom column order for the ticketing views. I created a new one called "all open tickets" in which the order should be Ticket Name, Category, Priority, Ticket Owner, Ticket -> Contacts, ... -- can you let me know if that looks the same on your end?

**Comment by DerekCaelin** [comment]
@hamriclr did you end up resolving your outstanding Hubspot configuration issues with Paul? Is this OK to close?
