### ISSUE TITLE
Review Help Content for Site Dashboard

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#632]
[Site Dashboard copy document](https://docs.google.com/document/d/1A_EIe7C8m5h78ijz6zNUdFSsUfVFwt8vK_GsRcByXH8/edit#heading=h.oys35urk3eq1)

**Comment by DerekCaelin** [comment]
@hamriclr I've updated this issue with a link to the correct document

**Comment by hamriclr** [comment]
No edits - looks good.
