### ISSUE TITLE
Design button to view site on Soil Web

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#646]
Design a button that enables a user to look up in an external website a map of possible soils.

 We've removed the soil map data layers from the home screen, and the snapshot from the Soil ID screens, so we need to link to the corresponding location on Soil Web. 

Enables: https://github.com/techmatters/terraso-mobile-client/issues/1159

## References
Example Soil Web link: https://casoilresource.lawr.ucdavis.edu/gmap/?loc=41.77093670949497,-72.7470661418328
Design: [Figma frame](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800%3A15155&mode=design&t=baOsgOAD77XQEpwn-1)

## Acceptance Criteria
- [ ] Design a button that brings the user to the appropriate location in a map provided by CA Soil Resource

**Comment by DerekCaelin** [comment]
Example Soil Web link: https://casoilresource.lawr.ucdavis.edu/gmap/?loc=41.77093670949497,-72.7470661418328

**Comment by CourtneyLee333** [comment]
@DerekCaelin Keep or cut from Capri? My guess is cut.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I think this is still in Capri, regardless of whether it's in the launch. My expectation is an external link button. The engineers will attach site lat/long to the url.
