### ISSUE TITLE
Load and display Soil ID data in mobile client location screens

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#653]
Load soil ID data and display it in the application. This includes:
- Info cards on map view for sites and temporary pins
- Dashboard for sites and temporary locations
- Soil info sheet tables

Data should be loaded when the user initially opens a dashboard and be passed through the application as they navigate to relevant screens and info sheets.

# Existing APIs
Depends on the API to be developed in techmatters/terraso-backend#1265

## Acceptance Criteria
- API calls provide data to all listed UI elements
- Engineering approval on data loading mechanism

**Comment by DerekCaelin** [comment]
Paul shared an API that appears to return all the data we need: https://api.staging.terraso.net/soil-id/list/?lat=123&lng=456

**Comment by knipec** [comment]
Not sure what the difference between "Site screen" and "Dashboard for sites" is. Same with "Temporary location screen" and "temporary pins". But I assume one of them means the "location card" that comes up when you click on any temporary map location on the "Home screen"?

**Comment by tm-ruxandra** [comment]
@knipec Yes, sorry I got my terminology confused. I will update the description.

**Comment by DerekCaelin** [comment]
@tm-ruxandra excited to QA this. In what build should I expect to be able to test?

**Comment by tm-ruxandra** [comment]
@DerekCaelin we're working out an issue with SoilID algorithm (see @knipec's slack thread in the LandPKS channel) so hang tight for a bit!

**Comment by DerekCaelin** [comment]
Seeing dummy data from the Soil ID algorithm in
- Info cards on map view for sites and temporary pins
- Dashboard for sites and temporary locations
- Soil info sheet tables

Closing this with the expectation that we'll be testing real data separately
