### ISSUE TITLE
Engineering Research - generate thumbnail of story map

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#66]
How might we generate a preview image for a story map that reflects the title screen, so that the user is able to understand a little better what will be behind the "click"

Goal is to do the work needed to reduce: #60 

![Image](https://user-images.githubusercontent.com/10799815/235726047-0182f084-a07b-49b4-af3a-049a2635bb40.png)

**Comment by josebui** [comment]
Tech doc: https://docs.google.com/document/d/1HhFNWMygCSJPRZtlhJSUQEt97pLSubvoFXkv4WEktGg/edit
