### ISSUE TITLE
Log in to LandPKS with Apple identity on iOS

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#680]
Log in to LandPKS with Apple identity on iOS. A requirement for launch. 

[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=6912-26045&t=ttaXBjiWPjZc8JHS-0)

This is the iOS version of the action. Android version will be accomplished with https://github.com/techmatters/terraso-mobile-client/issues/1444

## Acceptance Criteria
As an iOS user, log in to LandPKS with Apple identity.

**Comment by DerekCaelin** [comment]
@paulschreiber In iOS 135, I was successfully able to log in with iOS. In Android 135, the `Log in with Apple` button did not appear.

**Comment by paulschreiber** [comment]
This is an iOS-only feature.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 ready for your design review.

**Comment by CourtneyLee333** [comment]
Yay, it works! The button styles could use some help:
- The icon is too small, and should match the size of the other buttons on this screen. 
- The typography looks off, and should match the other buttons on this screen.

**Comment by paulschreiber** [comment]
@CourtneyLee333 We can't customize the font/size/color of the Sign in with Apple button. We can adjust the others to better match it. Let me know what you'd like to do.

**Comment by CourtneyLee333** [comment]
Hmm. I'd say let's leave them as-is. The other buttons look better than the Apple one, so I'd rather not make them all look worse.
