### ISSUE TITLE
Design confirmation dialog for users to delete their account

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#683]
Design the confirmation dialog that will inform the user of the consequences of deleting their LandPKS and Terraso account. See parent task for details.

## References:
[Figma: Delete Account section](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=6995%3A35053&mode=design&t=eaky8L27UH6DXksw-1)
[Copy Document](https://docs.google.com/document/d/1gthFDYh2VyhjXao6aw9Na4kyhkzBv2kjXR3nXU-h9Rc/edit)

## Acceptance Criteria
- [x] Research account deletion process and decide what the best confirmation experience is for this instance
- [x] As a user, I should be informed…
     - [x] ... The email address of the account that will be deleted
     - [x] … that all sites of which I am an owner will be deleted
     - [x] … that all projects where I am the sole project manager and all their affiliated sites will be deleted
    so that I know the consequences of my deletion action. 
- [x] After design, update [the copy document](https://docs.google.com/document/d/1gthFDYh2VyhjXao6aw9Na4kyhkzBv2kjXR3nXU-h9Rc/edit) and request review 

Paul's comments:
- Please determine what sort of confirmation dialog/steps we need for deletion (button press, type word "delete", type in email address of account, etc).
- We should also have some language that shows what is being deleted (sites, projects you own, preferences) and what isn't (shared data, 1000L data).

**Comment by CourtneyLee333** [comment]
Proposed workflow:

1. User taps "Delete Account" button.
2. Dialog appears with text describing what will and will not be deleted.
3. User is prompted to type "delete" into a text field, at which point a "Delete Account" button becomes available.
4. Dialog message changes to "Your request has been sent and your account will be deleted within 5 business days. You will receive an email confirmation when your account has been deleted."
5. User is returned to the Settings screen. In place of the "Delete Account" button there is the message "Account deletion pending."

I thought about something more complex. In Google and Apple, for example, you have to go deep into account settings to find the deletion option, and you have to get a verification code as part of the confirmation process. In Microsoft you have a bunch of steps to take like canceling subscriptions checking a bunch of checkboxes you agree to and then they still keep your account active for 60 days in case you change your mind.  Atlassian makes it a little more straightforward and the only confirmation is a delete button, but they still keep your data 14 days so you can restore it. Airbnb is pretty straightforward within the app settings (also just a delete button after a couple of steps) and doesn't seem to keep data once you delete. All of these have a page on the web that give lots of detailed information about the deletion process. 

I proposed the simple approach above to give the extra measure of typing in the word "delete" to prevent butt-dialing type actions, but without going into a series of emails or forms or confirmation codes. We can start here and then determine if more rigorous methods are needed. How does this sound @DerekCaelin ?

**Comment by DerekCaelin** [comment]
This sounds great! Please proceed.

**Comment by CourtneyLee333** [comment]
@paulschreiber @DerekCaelin I've reference the Figma playground location above. Once you approve the text I'll add it to the Capri page.
