### ISSUE TITLE
Write Tests for User Account Deletion

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#687]
[Tests for User Account Deletion](https://docs.google.com/spreadsheets/d/1v4slVQ6k7B8tLJsf1Z6pjYlSNKWaGWhioH4P3fKT914/edit#gid=2004954072)

```[tasklist]
### Review
- [x] Courtney reviews
```

**Comment by CourtneyLee333** [comment]
As I mentioned on Slack, the confirmation stage might need to be a separate form.
