### ISSUE TITLE
Update site creation experience with copy edits

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#696]
Paul reviewed the Site Creation experience on 4/25/2024 and provided copy edits. Update the design in Figma.

## References
[Figma with edits](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-14575&mode=design&t=3GJiwywT4SveYa9g-0)

## Acceptance criteria. 
- [ ] Update Figma design for the Create Site Experience using new copy.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Should this go in Backlog?
