### ISSUE TITLE
Design settings menu update for users who have requested account deletion

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#698]
In the settings menu, signify to the user that their request to delete their account has been received and that they don't need to request it again. Please see parent issue for details.

[Figma: Delete Acct Pending screen](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=6995%3A35081&mode=design&t=eaky8L27UH6DXksw-1)

## Acceptance Criteria
- [x] As a user, I want to know that my request to delete my account has been received and that I can't submit another request.

**Comment by CourtneyLee333** [comment]
@paulschreiber @DerekCaelin Figma playground referenced for your review. When approved I will add it to Capri page.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 works for me, thank you. 👍
