### ISSUE TITLE
Update Location Soils Info sheet designs with help text and Capri content

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#700]
Incorporate feedback from team members to the copy of the design for the Soils Info Page. See parent task for details.

## Text document
[Soil ID help text document](https://docs.google.com/document/d/1qRvfXfjKkoKAXl3jGeDwlRMXw3rYbvJc5ciY06Ehbqw/edit?usp=sharing)

## Designs
[Site Location Soils Info](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800%3A14751&mode=design&t=0trKBKTTURfhALgQ-1)#660 
[Temporary Location Soils Info](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-15906&mode=design&t=3GJiwywT4SveYa9g-0)

## Acceptance Criteria
- [x] Design reflects copy feedback from subject matter experts
- [x] Design reflects copy feedback from Paul

**Comment by CourtneyLee333** [comment]
@paulschreiber Do you want review the text document Laura and I have finalized? The link is in the issue description.
