### ISSUE TITLE
Remove transfer site option site location settings menu

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#701]
Update the site location settings menu to remove transfer site option, which wont be included in the Capri launch. 

## References
After Capri, we will add the feature back in: https://github.com/techmatters/terraso-product/issues/668

## Designs

[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13330&mode=design&t=3GJiwywT4SveYa9g-0)
![Image](https://github.com/techmatters/terraso-product/assets/10799815/bc2a915e-5599-4dd1-a2e7-adb4de33eff1)

## Process
```[tasklist]
### Issues
- [ ] https://github.com/techmatters/terraso-product/issues/702
- [ ] https://github.com/techmatters/terraso-product/issues/703
```

## Acceptance Criteria
- [ ] Remove the option to transfer a site to a project
- [ ] Settings menu should provide option to update name and delete site

**Comment by CourtneyLee333** [comment]
@DerekCaelin Noting this issue needs Capri milestone.

**Comment by paulschreiber** [comment]
@DerekCaelin This was removed a while ago.

**Comment by DerekCaelin** [comment]
Confirmed that this does not appear in 135.
