### ISSUE TITLE
Design Team Members view

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#71]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[LandPKS MUI Library](https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?node-id=8375%3A86793&t=e12gnjGPvVsDDbF9-1)
[LandPKS Wireframes and Prototype](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype?t=hiT0127wb8Tey06i-1) - Project Team frame

**Comment by CourtneyLee333** [comment]
@ltseng Should I mark this as done for now, and we'll create a new issue if we decide to update the member structure?

**Comment by ltseng** [comment]
Up to you - the parent issue will remain open, so you can either open a new issue or continue to work in this one.
