### ISSUE TITLE
Design and build flow for changing member access

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#72]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[LandPKS MUI Library](https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?node-id=8375%3A86793&t=e12gnjGPvVsDDbF9-1)
[LandPKS Wireframes and Prototype](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype?t=hiT0127wb8Tey06i-1) - Manage Team Member

**Comment by ltseng** [comment]
Do you still want this issue deleted?

**Comment by CourtneyLee333** [comment]
I've lost track now. It's in review so might as well leave it here.

**Comment by CourtneyLee333** [comment]
@ltseng Should I mark this as done for now, and we'll create a new issue if we decide to update the member structure?

**Comment by ltseng** [comment]
The parent user story is going to remain open, with a few edits, since it was moved to the June sprint anyway.
