### ISSUE TITLE
Add real elevation data to location popover

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#722]
In the location popover, set elevation real location data to show up in the location popover. 

Issue arising from QA. View parent task for context and more details. 

## Design

Figma
- [Temporary location popover](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13278&t=L1K8BnqSwwSyJfXg-0)
- [Site location dashboard](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13455&t=L1K8BnqSwwSyJfXg-0)
<img width="320" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/7697f84f-cd02-4017-99e2-f3a3d17c2718">

## Acceptance Criteria
- [x] Location popover provides real elevation data

**Comment by DerekCaelin** [comment]
@paulschreiber the popover contains the elevation information, thank you. 

The dashboard does not display elevation information yet. I see `Elevation: Unknown`. Do you want to tackle that as a part of this effort or do you want me to make another issue?

**Comment by paulschreiber** [comment]
I renamed this issue. Please make a second issue to track the dashboard work.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I think this looks good. Assigning to you for your QA, mainly because I think you'll be interested in seeing the loading indicator at work.

**Comment by CourtneyLee333** [comment]
Looks great to me on both platforms! Loading indicators are perfect.

**Comment by DerekCaelin** [comment]
@paulschreiber thanks for this. Passes review!

**Comment by DerekCaelin** [comment]
@paulschreiber as discussed I've made updating the location dashboard it's own issue. https://github.com/techmatters/terraso-product/issues/774
