### ISSUE TITLE
Design task - design loading indicator when waiting for a server response

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#726]
Design an indicator to display whenever the app is waiting for the server to respond. See parent task for details.

**Comment by DerekCaelin** [comment]
Closing as duplicate of https://github.com/techmatters/terraso-product/issues/525

**Comment by DerekCaelin** [comment]
Not actually a duplicat of #525

**Comment by CourtneyLee333** [comment]
@DerekCaelin The loading indicator is already implemented with a basic style of using LandPKS green. I thought we agreed that was good enough and nothing more needs to be designed.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 OK,  is it sufficient to attach https://mui.com/material-ui/react-progress/ as the reference for the implementing engineer?

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I'm trying to find a reference for the implementing engineer to insert. I know @shrouxm knows what to expect, but they might not be the implementer. Is https://mui.com/material-ui/react-progress/ enough, do you think?

**Comment by CourtneyLee333** [comment]
In my understanding the component exists in the app already, and it needs to be implemented on the login screen at this point. I haven't seen it so I don't know what it looks like. But I don't think it needs to be designed.

**Comment by DerekCaelin** [comment]
I'll consider this done then
