### ISSUE TITLE
QA Link Component

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#733]
Slight tweaks to the presentation of internal and external links based on Courtney's feedback to the work done in the parent issue. 

## Acceptance Criteria
Review Courtney's styling comment [here](https://github.com/techmatters/terraso-product/issues/733#issuecomment-2096434737).
- [ ] update internal link styling
- [ ] update external link styling

**Comment by DerekCaelin** [comment]
@CourtneyLee333 courtney this is available in the current build and seems to meet the functional requirement. Over to you for design review.

**Comment by CourtneyLee333** [comment]
@DerekCaelin I don't have v119 available. Do you? Where are you seeing these components in the app?

**Comment by DerekCaelin** [comment]
Ah. @CourtneyLee333 I checked the data privacy screen in v118, and confused the implemented version with your design (they are very similar). Unchecking this for now, we can ask the engineers to cut a release in the standup.

**Comment by CourtneyLee333** [comment]
@knipec The internal link - is it using the correct styles? It looks small. Should be body 1 size and bold.

**Comment by DerekCaelin** [comment]
Reopening this for paul's review

**Comment by DerekCaelin** [comment]
Closing this issue because the feedback from @CourtneyLee333 should be reflected in https://github.com/techmatters/terraso-mobile-client/issues/1289
