### ISSUE TITLE
Update and unify splash screens

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#744]
Update splash screens on iOS and Android to meet the new design.

## Designs
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13085&mode=design&t=jTdUEhWdWZYn87QU-0)

## Process
```[tasklist]
### Issues
- [x] Design task - design experience
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/928
- [ ] QA
```

## Acceptance Criteria

- [ ] Updated splash screen designs for iOS and Android

**Comment by CourtneyLee333** [comment]
FYI this ticket is confusing, but the splash screen still doesn't match the design on either platform.

**Comment by DerekCaelin** [comment]
I'll make a new issue.
