### ISSUE TITLE
Design Capri experience for Rate Soil Match

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#749]
For a site, allow the user to declare, after reviewing their own site's data and information provided by the Soil ID algorithm, what the selected match for Soil ID is. Expectation is to have as small a scope as possible with the intention to improve with https://github.com/techmatters/terraso-product/issues/658. See parent issue for details.

## Acceptance Criteria
- [x] As a manager or contributor, I want to be able to state whether a given soil is 
     - [x] the correct match for a site
  so that the site will either have an official SoilID and Ecological Site ID, or eliminated possible values
- [x] Once I have selected a soil, its status is reflected in the UI of the Site Soil ID screen and the Soil ID tile on the dashboard, so I can see at a glance my progress in selecting a soil to match a site.

[Figma design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800%3A15155&mode=design&t=2LlzoO8ko2P2UbuL-1): a simple checkbox at the bottom of the sheet.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Ready for your review.

**Comment by DerekCaelin** [comment]
A nitpick, I believe we can remove the [reference to a styling update](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-14751&t=8VPVEKWuHXg1sKZa-0) which will not be in Capri.
