### ISSUE TITLE
Review copy - delete user account confirmation dialog

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#751]
Review [copy edit document](https://docs.google.com/document/d/1gthFDYh2VyhjXao6aw9Na4kyhkzBv2kjXR3nXU-h9Rc/edit) for user account deletion.
```[tasklist]
### Tasks
- [x] Derek reviews
- [x] Paul Reviews
```

**Comment by DerekCaelin** [comment]
@CourtneyLee333 this meets my functional review.

**Comment by paulschreiber** [comment]
Left comments in the document.

**Comment by DerekCaelin** [comment]
Closing, thanks both for the review.
