### ISSUE TITLE
Create QA form for selecting a location on the map

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#759]
[QA form "Using the map to find a temporary location dashboard"](https://docs.google.com/forms/d/e/1FAIpQLSfhqaCVZDlmzx6b2TSumDObMg9PvRloP2QDNg5hDHrYhaFOLA/viewform?usp=sharing)

See parent issue for details.

**Comment by CourtneyLee333** [comment]
@DerekCaelin @paulschreiber I have the first form ready, with some comments and help I need from you:

- I'd like your review of the form - Paul, mostly for making sure my details in Section 1 are correct. And Derek, mostly for ensuring my workflow instructions makes sense and I've captured known issues. 
- I limited this test to using the map features, seeing the location popover, and seeing the temporary location dashboard. 
- The steps to get to a Site dashboard (as mentioned in the parent issue) seem like a separate thing and should include the two paths to create a site, filling out the site creation form, seeing the empty sites list, seeing the new site in the sites list, and viewing the site dashboard. 
- Should we QA the account creation and login experience before this one? If so, should we wait until Apple login is ready?
- Timing of this QA test is something to be wrangled, for these reasons: currently there are "known issues" in the form that might be resolved before the test starts; we might need to halt releases while the test goes on, which we plan to cap at one week for feedback. 
- If we have ongoing QA tests and need to halt releases, how will this affect our release and internal QA schedule?
- Derek, I'm assuming you'll coordinate the onboarding and testing with the testers. I made[ this spreadsheet](https://docs.google.com/spreadsheets/d/18rekGPERrQFBXWA2EBDLJzF1F6KL6aNfFRPCSQd_GKU/edit?usp=sharing) to track tester details but I'm not sure it it's needed. 
- I'm thinking to have Amaya test first to spot potential issues with the test itself as well as any major bugs we're not aware of, before passing it to the others. 

All thoughts and feedback welcome!

**Comment by paulschreiber** [comment]
I created a Google doc with revisions to the form text: https://docs.google.com/document/d/1h6KwMP2vmAksxjnlLGUT8bJf89tdvagrPoQs2N71HcY/edit

**Comment by CourtneyLee333** [comment]
I've incorporated Paul's revisions.

**Comment by DerekCaelin** [comment]
I've reviewed. Thanks for your patience. I think this is good to go.
