### ISSUE TITLE
Use real elevation data in site/location dashboard

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#774]
In the temporary and location dashboard, use real elevation data. 

#### Figma
- [Site location dashboard](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13455&t=L1K8BnqSwwSyJfXg-0)
<img width="257" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/5083dea3-1bbe-403c-bf99-85b5a0235809">
<img width="257" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/d2a84a2a-e5b7-4d01-96ae-6682eeeb4e37">

## Acceptance Criteria
- [ ] Location Dashboard provides real elevation data

**Comment by DerekCaelin** [comment]
This meets my expectation. Over to @CourtneyLee333 (reminder, historic sites will not get elevation data in the dashboard; this will be for sites going forward)

**Comment by CourtneyLee333** [comment]
I still see "Elevation:unknown" on the temp location dashboard on Android and iOS. I'm on v142.

**Comment by paulschreiber** [comment]
@CourtneyLee333 I can't reproduce that problem. I see valid elevation. Where (what city/location) are you tapping?

**Comment by CourtneyLee333** [comment]
I'm tapping really close to my house in Asheville 
![Screenshot_20240612-105838](https://github.com/techmatters/terraso-product/assets/8915145/2626f61d-86cc-4538-af9f-8907a63e5d86)

**Comment by CourtneyLee333** [comment]
But I see the issue in other locations as well.

**Comment by DerekCaelin** [comment]
@paulschreiber I can reproduce:

1. Tap map
2. See temporary site popover
3. tap "Learn more"
4. see temporary location dashboard
5. See issue

Elevation = "unknown"

**Comment by paulschreiber** [comment]
Ah, this happens after Learn More! I had only tested tapping Create Site.
