### ISSUE TITLE
Convert bedrock input design to restrictive layers

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#777]
Update the design of the "Bedrock" input to instead record "restrictive layers". A restrictive layer could be "bedrock", or some other issue. See parent issue for details.

## References
- [Bedrock design ](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=6662-22247&t=U0W7uVMw47oIFVd2-0)
- [Restrictive layers design, first draft](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=2002-92480&t=nnoTL52gjNX1G9S1-0)
- [USDA bedrock PDF](https://drive.google.com/file/d/1x3R5NMNmceJxJ0q7tvCcRupDI2a2gL6X/view?usp=drive_link)

**Comment by CourtneyLee333** [comment]
@DerekCaelin It occurs to me that maybe this task should be lower in priority than the MVP landing page and Data Portal page, as there are links in the Capri app that point to these pages.
