### ISSUE TITLE
Design "early stage app" interstitial for first-time users

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#778]
Design an interstitial to set expectations for the user about what the app currently does, and what we expect to add in coming iterations. See parent issue for details.

## References
- Figma design: [Interstitial 1](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8197-44176&t=udWZM1xAt0WWAy3Y-1)
- [Product Spec](https://docs.google.com/document/d/1-eSFLAcrAwOY8qotTvINQoFme2ycFvfGE72RLuQPtTI/edit#heading=h.54w02ys7n8ko)
- [Draft Language](https://docs.google.com/document/d/1Pk4vpc3aRQr1phGyOTkJMHLQ9BTMV2aRdo09Py9zVu0/edit)

## Acceptance Criteria
- [x] As a user of the app, I want to understand that key features are not yet implemented and the app is in early stages so I am not frustrated by failed expectations.

**Comment by CourtneyLee333** [comment]
@DerekCaelin @paulschreiber I made a [copy suggestion for the interstitial here](https://docs.google.com/document/d/1Pk4vpc3aRQr1phGyOTkJMHLQ9BTMV2aRdo09Py9zVu0/edit?usp=sharing) and would like your feedback. 

I'm assuming the interstitial needs to be very simple for Capri release, but in the future I'd like to get more sophisticated with multiple screens to describe the new features in more detail.

**Comment by DerekCaelin** [comment]
Thanks, @CourtneyLee333 - I have no objection to the language in this screen. Agreed that a "whats new?" feature, which would share updates included in the most recent release, would be an interesting next step. Mentioning @knipec, who will be implementing this feature.
