### ISSUE TITLE
Draft early stage app interstitial language

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#779]
Review and edit [Interstitial Language](https://docs.google.com/document/d/1Pk4vpc3aRQr1phGyOTkJMHLQ9BTMV2aRdo09Py9zVu0/edit)

**Comment by CourtneyLee333** [comment]
I made some comments in Slack and a suggested edit in the word doc. I'd leave out for now the concept of Soil ID outside the US as that will be a completely separate app.

**Comment by DerekCaelin** [comment]
@paulschreiber this is ready for your review.

**Comment by paulschreiber** [comment]
@derekcaelin Review complete. Comments in the doc.
