### ISSUE TITLE
Create wordpress site for landpks.terraso.org

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#788]
Create a WordPress site with the domain landpks.terraso.org.

## Acceptance criteria
- [x] create a wordpress site at landpks.terraso.org
- [x] import theme from terraso.org 
- [x] create a staging site for landpks.terraso.org (domain name doesn't matter)

**Comment by paulschreiber** [comment]
Done.
Staging version is http://landpks-terraso-staging.mystagingwebsite.com
