### ISSUE TITLE
Write draft language for the MVP Landing Page

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#790]
Edit and review the [Draft Language MVP Landing Page](https://docs.google.com/document/d/1J0IHP4gHxakHcvHKDD6qNMOyrk7HRasjpvUdrrU5cDg/edit#heading=h.q0dns7qjtkun).

**Comment by DerekCaelin** [comment]
@theladymay @CourtneyLee333 I wrote up some draft language based on the product spec. Please review.
Next reviewers will be:
- Steve
- Laura
- Paul

**Comment by CourtneyLee333** [comment]
I made a few suggestions, but overall looks great!

**Comment by ssfrancis** [comment]
I reviewed and added comments.

**Comment by DerekCaelin** [comment]
@paulschreiber please provide copy edits to the document in this issue.

**Comment by paulschreiber** [comment]
@DerekCaelin I have made suggestions in the document.
