### ISSUE TITLE
QA form outline

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#809]
Write Google forms for:
- [ ] inputs
   - [ ] color
   - [ ] slope
   - [ ] texture
   - [ ] rock fragments
   - [ ] vertical cracks

Before these inputs testing we must:
* Create a project and a site for each user with these inputs required and others hidden.
* Fix Slope Meter ([see on Slack](https://tech-matters.slack.com/archives/C06BQTCAUJF/p1716223456813249))
* Fix clearing out and overwriting Slope Steepness ([see on Slack](https://tech-matters.slack.com/archives/C06BQTCAUJF/p1716230289119049))
* Add Done button to Texture

Known issues:
* Depth intervals are wrong.
* "Cross-slope" needs editing in two places.
* Manual input of slope steepness should show error message on Degree field.
* Manual input should use new text field component.
* Color sometimes give "unexpected color" message with suggestion of the same color.
* Color sometimes give results that are way off. ([see this issue](https://github.com/techmatters/terraso-mobile-client/issues/1352))

- [ ] selecting location on a map

-------
We plan to internally test with Google sheets. 
- [ ] creating site
- [ ] managing site
   - [ ] change name
- [ ] site dashboard
- [ ] create project
- [ ] transfer site in / out

**Comment by CourtneyLee333** [comment]
@DerekCaelin I've updated the description for the next set of inputs to include things we need to do ahead of time to set up the testers, and known issues. Below is what I'm thinking as a general outline of the test. Let me know what you think, please. 

Slope
- Steepness
   - See open circle.
   - Enter manual. Save.
   - Overwrite with Slop Meter. Save.
   - Overwrite with image selection. Save
   - See checked circle.
- Shape
   - See open circle.
   - Choose one. Save.
   - Overwrite with another. Save.
   - See checked circle.
Vertical Cracks
   - See open circle.
   - Choose one. Save.
   - Overwrite with another. Save.
   -  See checked circle.
Texture
   - See open circle.
   - Choose from selection. Save. 
   - Use Guide. 
   - See your answer in the top field. Save. 
   - See checked circle.
Rock Fragment
   - See open circle.
   - Choose from selection. Save. 
   - Overwrite with another. Save.
   - See checked circle.
Color
   - Get some soil, some post-its, Munsell book.
   - Use the photo feature
   - Add your photo to the google form. 
   - What are the results from the app?
   - What are the results from the Munsell book?
   - Do several of these with different colored soils if possible.

**Comment by CourtneyLee333** [comment]
@DerekCaelin I think you originally made this issue with the intent to keep a running list of al the QA we need to do. I've copied all the details I need from this one to the new issue you made for generating the next QA form. So if you want to clean this up and keep it going as a parent task go for it.
