### ISSUE TITLE
Implement "early stage app" interstitial for first-time users

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#813]
Create interstitial for first time users of the mobile app. See parent issue for details. 

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8197-44176&t=Ml0EZ3xwMIi9havR-0)

## Acceptance Criteria
- [ ] As a user, I want to see an interstitial one time that informs me of what to expect in the current app and in future iterations.
### Carissa's AC
When does the interstitial appear
- When user first opens the app, if they have not seen the interstitial on their phone before, interstitial appears (before login screen).
- When user closes and opens the app subsequent times, they will not see the interstitial.
- If logging in as a different user on a phone that has already seen the interstitial, user will not see the interstitial.
- If user uninstalls and re-installs the app, they will see the interstitial again upon opening the app.

Behavior on the interstitial screen
- Pressing "Get started" button from the interstitial leads to home screen
- Pressing "LandPKS from Terraso" external link goes [[for now to landpks.terraso.org]]

**Comment by knipec** [comment]
From message with Derek: 

- I’m gonna need more info about what “first-time users” means – when exactly do they see it? After logging in? (If so, sounds like when a user logs in, we’d ask the backend if they’ve logged in before, and if not, we’d show the interstitial and possibly store a bit of info in the database for that user saying “yup they’ve logged in before so already seen it”.)
- Estimation: 
    - 3 to add the info, query, and mutation to the backend (or less for someone who’s more familiar with it?)
    - 4 to create the page/modal/thing (depending on how complex it is) and hook it up to the backend

**Comment by DerekCaelin** [comment]
@knipec sharing what was said in the comments section of Figma, and updating the issue:
> show this interstitial would be after login, before the user lands on the home screen. This way we can store in the user's account whether they've seen the interstitial. I'll make sure the spec and the Github issue align.

By "first time user" I mean, users who have not seen the interstitial describing the functionality of LandPKS Soil ID, so the definition you provide above makes sense to me.

**Comment by knipec** [comment]
@DerekCaelin I believe this means there will be no way for the user to see it again after they dismiss it the first time. I feel like that's probably fine, but just want to confirm!

**Comment by DerekCaelin** [comment]
@knipec great, that's the expected behavior, at least for this iteration.

**Comment by knipec** [comment]
Update: Instead of saving showing the interstitial after login and saving "has it been seen already?" in the database, we will plan to show the interstitial upon first opening the app, and save "has it been seen already?" to local storage on their device. 
(Decision made in [this slack thread](https://tech-matters.slack.com/archives/C0376RCCXD2/p1718382190619079))

**Comment by CourtneyLee333** [comment]
@knipec I'm assuming this isn't on a build yet. Let me know if that's wrong.

**Comment by knipec** [comment]
@CourtneyLee333 That is correct for now; oops I forgot to ask if Paul would kick off a build in standup, will do that now!

**Comment by CourtneyLee333** [comment]
This looks good on both platforms! On Android there is the green app bar at the top, but I'm not concerned about. Calling this done! 

![Image](https://github.com/techmatters/terraso-product/assets/8915145/80fecc1a-d1d7-409d-a583-6ddb62a4b846)

**Comment by CourtneyLee333** [comment]
This needs to be QA'd after subsequent releases to ensure it only shows once.

**Comment by CourtneyLee333** [comment]
Confirmed I did not see the interstitial again after yesterday's release.
