### ISSUE TITLE
generate QA google form for texture, slope, vertical cracks, color

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#823]
Based on https://github.com/techmatters/terraso-product/issues/809, build a google form to distribute to QA testers.

Before these inputs testing we must:
* Create a project called Project QA Inputs 1 [user initials] and a site called Site QA Inputs 1 [user initials] for each user with these inputs required and others hidden.
* Fix Slope Meter ([see on Slack](https://tech-matters.slack.com/archives/C06BQTCAUJF/p1716223456813249))

Known issues:
* Clearing out manual entry of either degree or percent field on slope steepness does not clear out the other field. 
* "Cross-slope" needs editing in two places?
* Manual input of slope steepness should show error message on Degree field.
* Manual input should use new text field component.
* Color sometimes give "unexpected color" message with suggestion of the same color.
* Color sometimes give results that are way off. ([see this issue](https://github.com/techmatters/terraso-mobile-client/issues/1352))
* Done button is sometimes enabled, sometimes disabled, before the user enters the required data. 

Outline:

Slope
- Steepness
   - See open circle.
   - Enter manual. Save.
   - Overwrite with Slop Meter. Save.
   - Overwrite with image selection. Save
   - See checked circle.
- Shape
   - See open circle.
   - Choose one. Save.
   - Overwrite with another. Save.
   - See checked circle.

Vertical Cracks
   - See open circle.
   - Choose one. Save.
   - Overwrite with another. Save.
   -  See checked circle.

Texture
   - See open circle.
   - Choose from selection. Save. 
   - Use Guide. 
   - See your answer in the top field. Save. 
   - See checked circle.

Rock Fragment
   - See open circle.
   - Choose from selection. Save. 
   - Overwrite with another. Save.
   - See checked circle.

Color
   - Get some soil, some post-its, Munsell book.
   - Use the photo feature
   - Add your photo to the google form. 
   - What are the results from the app?
   - What are the results from the Munsell book?
   - Do several of these with different colored soils if possible.

**Comment by CourtneyLee333** [comment]
Alright @DerekCaelin the form is ready for your review. Please go through the whole thing to make sure I haven't missed details (I'm rather bleary-eyed at this point!) Here is the [front end form](https://forms.gle/DzRivYvdSXacbvuS7) and the [form editor is in this folder ](https://drive.google.com/drive/folders/1KXQLVGL_gIqWOYJQZmCXMpbxJDRO1JWB?usp=drive_link)if you want to compare. 

Note that I have told people they can contact you for photos to use if they don't have their own materials. Hopefully they all have access to a Munsell book and can do a real soil color test.
