### ISSUE TITLE
? Update LandPKS Depth Intervals

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#831]
Derek to confirm this! 

LandPKS depth intervals should be, in CM:

0-1
1-10
10-20
20-50
50-70
70-100
100-120

**Comment by CourtneyLee333** [comment]
We did confirm this, but I'll have to find where we documented the decisions.

**Comment by paulschreiber** [comment]
Is this also covered by #1541?

**Comment by CourtneyLee333** [comment]
I'm pretty sure this is covered by #1541 in mobile-client.
