### ISSUE TITLE
update design for capri add team member experience

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#836]
Update design for add team member experience for launch.

[Notes from team discussion 5/30/2024](https://docs.google.com/document/d/1B6Kubd5tGu6yytjtpo5HpNa2xdaMA-Nailg_GQliwBQ/edit)

- [ ] Research - add button for text field?

**Comment by CourtneyLee333** [comment]
Carissa needs to do some digging and then we will reconvene to finalize our solutions.
