### ISSUE TITLE
[Internal] LandPKS team process recommendations

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-product#849]
## Rough Timeline
**June: Get individual input & buy-in**

1. June 10: Draft 1 document done (can use [“Our Sprint and Backlog dreams” FigJam](https://www.figma.com/board/Tuezw6wpfOnAClTojt5vpu/Our-Sprint-and-Backlog-dreams?node-id=0-1&t=k3aYRXK1zIuciuEm-0))
2. June 10-14: Run the document by each team member
3. (June 14-29: Continue to iterate)
4. June 30: Draft 2 document done (incorporate input & smooth out disagreements)

**July: Get team buy-in & do setup work**
1. July 2: Present in a full team setting, get buy-in (or additional input)
2. (July 1-30: Iterate & setup)
3. July 31: Have all setup work done (GitHub views, status/tag names, meetings on the calendar, etc.)

**August: Try it for a month**

**Comment by DerekCaelin** [comment]
@knipec how do you want to handle this task? move into August? Mark as complete?

**Comment by knipec** [comment]
Hmm I probably will still be doing some thinking on process ongoingly -- I guess the things I'll be focusing on for the August sprint are like: 
- Continue doing bug triage weekly and ad-hoc when needed (hopefully not much active work except remembering to save time at the end of team meeting)
- Focus on process for how to do feature story refinement (with Derek, presumably)
- Focus on process for sprint planning (with Derek)
- Probably have a tech debt / housekeeping triage/prioritization session before the next sprint
- Figure out how to feel like we have a hold on things we're concerned about falling through the cracks (I'm starting to attempt a thing [here](https://www.figma.com/board/KGoIsSHNnP3qOepRgf0pOH/Things-to-attend-to?node-id=0-1&t=FwfpFQsGaI4hEted-0))

So maybe we can close this one out and either make a new August one for visibility? Alternatively, I can just keep it in my head and do it on the side, but I usually lean towards over-communication 🤷

**Comment by knipec** [comment]
@DerekCaelin Let me know if you'd like me to do that!

**Comment by DerekCaelin** [comment]
@knipec if we feel the work was done, let's close this out, and by all means, lets have another issue representing our ongoing process work in August.

**Comment by knipec** [comment]
👍 August stuff now in https://github.com/techmatters/terraso-product/issues/987
