### ISSUE TITLE
Soil depth presets - design update

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#858]
Update presets and defaults for depth intervals in dropdowns for projects and unaffiliated sites.

## Designs
[Figma - Project ](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12975&t=754RJj1snmtTsV5a-0)
[Figma - Unaffiliated Site](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8396-29402&t=yAGxhRYDhFVywIGv-0)

## Acceptance Criteria
- [x] In Project "Soil Pit Depth Intervals" and unaffiliated sites
   - [x] Rename "NRCS" to "NRCS/GSP"
   - [x] Make NRCS/GSP the default 
   - [x] Rename "LandPKS" to "BLM Monitoring Standard"
   - [x] Set "BLM Monitoring Standard" depths to:
       - 0-1 cm
       - 1-10 cm
       - 10-20 cm
       - 20-50 cm
       - 50-70 cm

**Comment by CourtneyLee333** [comment]
@DerekCaelin Will you take a look and make sure I got all the details?

**Comment by DerekCaelin** [comment]
Looks good to me!
