### ISSUE TITLE
Engineering Research - How might we get data from Kobo?

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#87]
Research task: How might a user who has a Kobo account be able to view Kobotoolbox project data in Terraso?

## Data of interest
- Projects
  - Name of project
  - Owner of project
  - People involved
  - Data collected
    - Metadata
      - Questions asked
      - Number of submissions
    - Actual data 

## Questions
* Can SSO process also fetch the API key?
* How do we ensure we have the most up-to-date version of a data set?
* Can Terraso auto-fetch the API key?

## References: 

* [Product Spec - Living Kobo Datasets](https://docs.google.com/document/d/1Tqch8Z_gYLLa3or238Lhrl5kXq1jfgC7tZblF6_TuX0/edit#heading=h.54w02ys7n8ko)
* Kobo’s “Rest” services: https://support.kobotoolbox.org/rest_services.html 
* Share links to KoBo project on Terraso: https://support.kobotoolbox.org/managing_permissions.html 
*  We can get the API token from authenticated users by going to: https://kf.kobotoolbox.org/token/?format=json

**Comment by josebui** [comment]
From the documentation it seems that Kobo doesnt have a Oauth 2 or something similar to allow the user to delegate the authorization directly to another application, it seems that right now the process is to copy the API key directly: https://support.kobotoolbox.org/api.html?highlight=authorization

**Comment by josebui** [comment]
Kobo conversation: https://chat.kobotoolbox.org/#narrow/stream/27-Partner---Terraso/topic/Oauth

**Comment by josebui** [comment]
Research doc: https://docs.google.com/document/d/1OcPBsjZiOnAU_acr_0_77okuti7ijfwnTgRvE6OGLKU/edit#
