### ISSUE TITLE
UX research into offline use

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#892]
Explore and document the existing off-line experience. Look into best practices and existing patterns. 

**Look into other apps that do offline syncing for patterns- Google docs (animation and sliding around), Evernote (syncing notes and notebooks), (exercise app - Steve can talk me through), Strava. Counter example - WhatsApp flashes a bunch of messages as they update and it’s annoying. Outlook lets you read and write emails offline and then sync them when online. Kobo does offline collection. Check Ecobot and iNaturalist. Ask in general channel for good and bad examples.

### Design/Product
- [x] Research other offline apps, look at good examples
- [x] Draw up sample workflows, requirements docs, fatmarker sketches 
- [x] Exchange and synthesize for a shareback session on or before August 6
- [x] Flesh out scenarios where conflicts can arise (due Aug 16)
- [ ] Sketch out workflow where people enter different records, not editable to each other (like SoilStack). What’s necessary for MVP - start without data versions and history and bring that in later. (due Aug 16)

[Courtney's Mural for data sync principles and ideation sketches](https://app.mural.co/t/techmatters9109/m/techmatters9109/1722526555357/a1f448cac9503667ca90bcac4cbcf0c3a5e29e2d?sender=u7b3b2fb95ea53b5320ac3477)

**Comment by CourtneyLee333** [comment]
@DerekCaelin This task got skewed toward data syncing and conflicts. Is there anything else I need to do to finish the offline research part?

**Comment by DerekCaelin** [comment]
My goal is to start planning new design design work. At this stage I'd like to know, based off your research this month:
- what elements of new UI do you have high confidence that we will eventually need to do?
  - which of these elements are critical for launch, from your perspective? EG:
    - signifier that action is not available in an offline state?
    - signifier that client has sent data to the server 

Future research task:
- What should be the sync experience at launch? What should be the sync experience long term?

**Comment by CourtneyLee333** [comment]
@DerekCaelin I think I've done all I can for now. Closing this ticket, and let's create new ones for more specific tasks for features net sprint.
