### ISSUE TITLE
Implement soil id algorithm error handling & loading indicators

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-product#895]
## Acceptance Criteria
When we are loading soil id, show loading indicator. 
When soil id algorithm cannot return a valid soil id, show appropriate error.
- **Temporary Location Callout:** 
  - Loading: shows spinner
  - Error: shows red "Error" for Soil ID and Ecological Site ([Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=6431-19556&t=r2Sj9axNxRobYvt4-0))
  - Data unavailable: shows "No matches"
- **Location Dashboard Screen:** (for both sites and temporary)
  - Loading: shows the LocationPrediction soil ID box, with "Loading..." for the value of Soil ID and Ecological Site
  - Error: shows the LocationPrediction soil ID box, with "Error" for Soil ID and Ecological Site ([Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13448&t=K4Y7eC64S7nitNXx-0))
  - Data unavailable: shows "No matches"
- **Location Soil ID Screen:** (for both sites and temporary) 
  - Loading: Show the section with the header, info button, and a loading spinner 
  - Error: Show the Top Soil Matches section with a "Can't fetch soil map" error message box instead of soil tiles per [Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8748-38210&t=K4Y7eC64S7nitNXx-0)
  - Data unavailable: Show the Top Soil Matches section with a "No soil map data" alert message box instead of soil tiles per [Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8748-38189&t=RXsd1knRpdtoKXSm-0)

### Scenarios to check:
- **Loading**: `40.29795, -113.52856` took several seconds to load for me
- **Data unavailable**: To repro: `57.24394, -111.14606` or anywhere outside the US
- **Success**
- **Error**: To repro: `34.97561, -106.67266` 
carissa comment: Soil Id algorithm failure: I used to have some failing lat/longs but I think improvements to soil ID algorithm have made it harder to find crashes (yay, except for in this case) -- check with garo for failing cases?
- **Error**: Backend unavailable: [[Untested: Disable online connectivity?]]
- (Note: **Error**: Timeout after 20 seconds: Not planned for Capri; is now kinda tracked as part of https://github.com/techmatters/terraso-product/issues/902)

**Comment by knipec** [comment]
Assigning to Courtney for QA now that it's in a build

**Comment by DerekCaelin** [comment]
I was able to test temporary locations for "success" and "no match" and "error". I have a reproduceable set of error coordinates which i added to the comment above. Over to @CourtneyLee333

**Comment by CourtneyLee333** [comment]
Looks good to me!
