### ISSUE TITLE
Create screen shots for stores

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#899]
- [x] Screens

Screens:
- home screen with multiple pins on map and Sites List open to halfway point
- site dashboard with Soil ID tile
- site Soil tab showing default depths and some data collected and some not yet collected
- soil color result page after using photo? (see below)
- soil info page showing description, score tiles, etc (see below)

![Image](https://github.com/techmatters/terraso-product/assets/8915145/6cd20547-9b4f-47e5-9491-a3b5801b24d1)

![Image](https://github.com/techmatters/terraso-product/assets/8915145/764599e3-5a96-4b29-a6c5-4e2b98128752)

**Comment by CourtneyLee333** [comment]
@paulschreiber Can you coordinate getting the screenshots from the emulator?

**Comment by CourtneyLee333** [comment]
Noting that using a location somewhere in US rangelands is a good idea, like outside Boise.

**Comment by DerekCaelin** [comment]
@paulschreiber what do you think of these?
- [home screen with multiple pins on map and Sites List open to halfway point](https://github.com/techmatters/terraso-product/assets/10799815/62bdff7e-804a-4dd0-a4f0-a28ac82f576c)
- [site dashboard with Soil ID tile](https://github.com/techmatters/terraso-product/assets/10799815/529d6375-1ff7-4e2f-b3af-c380b58c05c5)
- [site Soil tab showing default depths and some data collected and some not yet collected](https://github.com/techmatters/terraso-product/assets/10799815/1e6057ae-5c5c-40d1-8e1f-8d36a9a0d995)
- [soil color result page after using photo? (see below)
](https://github.com/techmatters/terraso-product/assets/10799815/ccfb9da8-9fc5-4d3e-b3d7-610deec96bd3)
- [soil info page showing description, score tiles, etc (see below)](https://github.com/techmatters/terraso-product/assets/10799815/8e64a3fe-18e0-4b80-b926-00994a827bf1)

**Comment by CourtneyLee333** [comment]
Do we need the app header to say LandPKS Soil ID?

**Comment by paulschreiber** [comment]
@CourtneyLee333 What do you mean by "app header"?

**Comment by CourtneyLee333** [comment]
App bar - the part at the top with the green background that just says LandPKS.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I think you're right, it should read "LandPKS Soil ID". I'll make an issue. I don't think it's a blocker to have "LandPKS" in the screenshots for now.

**Comment by paulschreiber** [comment]
The app bar title was fixed in https://github.com/techmatters/terraso-mobile-client/pull/1753.

**Comment by paulschreiber** [comment]
Screen shots from:
• iPhone 14 Plus
• iPhone 15 Plus
• iPhone 8 Plus
• iPad Pro 12.9" (2nd Gen)
• iPad Pro 13" (M4)

Android
• Pixel 7a
• Android Tablet 10"
