### ISSUE TITLE
Engineering Research - Leaflet to Mapbox

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#92]
- [ ] Do necessary research for
https://github.com/techmatters/terraso-product/issues/64
https://github.com/techmatters/terraso-web-client/issues/816
- [ ] Update Engineering size of 64 and 816.

**Comment by josebui** [comment]
Tech doc: https://docs.google.com/document/d/1Uceo3L7kibOsrZukGbZ4sayDRaMQzq6YfMB4uWO2kfc/edit#
