### ISSUE TITLE
Change tagline in signin screen and info sheets to Discover your land's potential

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#925]
On Sign-in Screen
- Change tagline from "Soil science in your hands" to `Discover your land's potential`
- Change "Soil science in your hands" on the sites info sheet to `Discover your land's potential`

**Comment by paulschreiber** [comment]
Let's try out styling the title in different ways, i.e.
**LandPKS Soil ID** US

We also have the phrase "Soil Science in Your Hands" on the Info sheet. Do we need to change that?

**Comment by DerekCaelin** [comment]
Yes, we revisited the store page description and [updated some fields.](https://docs.google.com/spreadsheets/d/1fGjIvQiKOcuOkheZdkEEwC3CenRfw1k5cVZcBJAx2M8/edit?gid=2031695413#gid=2031695413)

**Comment by paulschreiber** [comment]
Please highlight the changed fields so we know what to update.

**Comment by paulschreiber** [comment]
The store description is unrelated to this issue. I asked about the in-app info sheet. (Also: please highlight the changed fields in that spreadsheet.)

**Comment by DerekCaelin** [comment]
@paulschreiber Getting back to your question, yes, we should update the info sheet. I will share a separate issue about the store fields.

**Comment by paulschreiber** [comment]
Please verify on 179.

**Comment by DerekCaelin** [comment]
Looks good!
