### ISSUE TITLE
Design - add build number to signin screen

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#949]
Allow users to determine their build by looking at the app (as opposed to test flight, or the settings screen (which requires login)

[The design in Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9702-13798&t=D2nt6I7EzOxLZAh4-1)

## Acceptance Critieria
- [ ] As a user, I want to know the build number of the app I am using, so I can communicate that information to the LandPKS team when asking questions / testing / providing feedback / seeking support.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Are we sure we have a need for this?

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I think the value add is users can tell us the version of the app they are using, even if they can't log in.

**Comment by CourtneyLee333** [comment]
@DerekCaelin I tightened up the design a bit on the screen and put some notes for engineers there. I'm hoping this is minimal work that can be done while adding the version number.
