### ISSUE TITLE
Produce list of changes for first iteration of Soil ID app changelog

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#960]
Write out what we want for first release of Soil ID (maybe just the simple list we include in the interstitial), and then any subsequent release updates. 

[Release notes](https://docs.google.com/document/d/16sJCYDnn2Qa3v6_rXG7rV79i-20CB0wsWarCyWtuAik/edit)

**Comment by DerekCaelin** [comment]
This looks good to me
