### ISSUE TITLE
Blog Update - Map Layers in Story Maps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#962]
Blog: https://docs.google.com/document/d/15uu6Dx6fvqKjsBQfBGuZeZF-0d4G3kEjLWl9Q7_sQq0/edit

```[tasklist]
### Tasks
- [x] Draft Blog
- [x] Amaya/Steve reviews
- [x] Paul Reviews
- [x] Publish English
- [ ] Translate
- [ ] Publish Spanish
```

Documentation https://terraso.org/help/how-to-make-a-story-map/

**Comment by DerekCaelin** [comment]
Thanks @theladymay for the review - over to @paulschreiber.

**Comment by paulschreiber** [comment]
Comments/edits are complete.
