### ISSUE TITLE
Legacy App - Lost Photos issue

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#963]
Referencing here, because the legacy repo is not under the `techmatters` org and can't be added to the project. 

https://github.com/LandPotential/LandPKS_Mobile_Application/issues/71

**Comment by DerekCaelin** [comment]
Details here

[Email - Photos not syncing to cloud on current iOS app.pdf](https://github.com/user-attachments/files/16379336/Email.-.Photos.not.syncing.to.cloud.on.current.iOS.app.pdf)

**Comment by DerekCaelin** [comment]
After speaking with Steve, we agreed that we won't fix this solution for now since the value add doesn't justify the LOE. I will follow up with the user who shared the problem and let them know.

**Comment by DerekCaelin** [comment]
@paulschreiber would you please throw any notes you have about the problem in this issue so we can access them in case we ever pick it up?

**Comment by paulschreiber** [comment]
Updated:
1. the build script to work with Xcode 14.3 or later.
2. the developer team id to be Tech Matters' ID
3. the minimum iOS deployment target to be 13.0
4. the export method (changed `development` to `debugging`)

Notes:
1. On Android, the camera prompt does not even appear. We can reproduce on both Android 12 and Android 14.
2. On iOS, you can take photos but not upload them.
3. The backend API `/APEX/External_Tools/LandPKS_Upload_Image/LandPKS_Upload_Image.php` (which isn't really PHP) works and writes files to the cloud storage bucket when it receives a well-formed POST request. See the LandPKS_API_System repository.
5. The client sends an `img_data` parameter. The backend is looking for a `data` parameter
6. The problem appears to be that `readFromFile()` is returning an empty value, which means no upload attempt is made.

Debugging challenges:
- there are two distinct login methods; one for web and one for app
- in development mode, the web method is used, and it fails (it's treated as a popup and blocked)
- login doesn't work when using `ionic serve` and running the app in a web browser (Google API result is `error: "user_logged_out"`)
- The iOS simulator doesn't simulate a camera (so you can't try taking photos)
- The Android emulator does simulate a camera, but the camera code does not work on Android (see Note #1)
- Running the iOS app on a Apple silicon Mac allows you to take photos, but seems to throw a lot of JavaScript exceptions

To run with live reload
* on your Mac, in one tab: `ionic serve --external` (need `--external` to run on the IP accessible by the phone)
* in a separate tab
```
ionic cordova run ios --livereload-url=http://192.168.7.156:8100 --target=00008030-0001156C0AF3802E --verbose
```
(replace the IP and target)

to get a list of devices
```
ionic cordova run ios --list
ionic cordova run android --list
```
