### ISSUE TITLE
Design and build mechanism for turning data layers on and off

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#97]
```[tasklist]
- [x] Wireframe approved
- [x] Final Design approved
```
[Home Map Data Layers bottom sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3285%3A17534&mode=design&t=zJIFKy6msvxmiuLa-1)

**Comment by CourtneyLee333** [comment]
As of 6/7 - waiting for map discussion

**Comment by CourtneyLee333** [comment]
@ltseng I've modeled this heavily on the Google map app.

**Comment by ltseng** [comment]
Looks intuitive to use! I like it.
