### ISSUE TITLE
Release 2024/08 build of LandPKS Soil ID

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#984]
Release the latest build of LandPKS Soil ID ~8/14/2024

- [x] agree on version number  (1.0.1) 
- [x] agree on release date (august 26)
- [x] a few days before release
   - [x] agree no more fixes go in friday 8/23
   - [x] write up release notes for app store 
   - [x] write up release notes for changelog (more detail?) - https://github.com/techmatters/terraso-product/issues/960
- [ ] release a build pointing at the production server
- [ ] test this build
- [ ] submit to apple and google
- [ ] publish (once both are approved)

**Comment by paulschreiber** [comment]
Version 1.0.1 (184) was published to the app stores today.
