### ISSUE TITLE
Design Review - Effervessence / Soil Structure / Percent Clay

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#992]
Revisit designs for important data inputs and present to the engineering team.

Designs from these stories:
- https://github.com/techmatters/terraso-product/issues/167
- https://github.com/techmatters/terraso-product/issues/162
- https://github.com/techmatters/terraso-product/issues/543

## Designs
- [Effervescence](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9529-24975&t=UgjTmldBsxdxu3eT-1)
- [Soil Structure](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9529-24949&t=UgjTmldBsxdxu3eT-1)
- [Percent Clay](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9786-16020&t=ayaKYHUVgNCqXbux-1)

## Acceptance Criteria
- [x] Designer revisits designs - are they complete and do we need to update them based on what we've learned
- [x] Laura feedback
- [x] BLM feedback
- [x] Design edits if needed
- [x] Designer presents to Engineers for feedback
- [x] Engineers size the designs.

**Comment by CourtneyLee333** [comment]
@hamriclr I've seen various illustrations for soil structure. Do you think the ones used in the legacy app are good to continue with, or should we look for others?

**Comment by CourtneyLee333** [comment]
@DerekCaelin @hamriclr In the original scope we bundled percent clay and rock fragments into texture in terms of project management requirements. On the Soil Pit overview screen we currently display texture and rock fragments separately. So we also want to display percent clay on the overview? Seems yes, since we've been asked for that input multiple times. I'm thinking we might want to separate them out when it comes to requirements, for some flexibility. Let's review this thinking and figure out what makes sense.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 that approach makes sense to me, let's see what Laura thinks.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Some things to note as you create or edit implementation tasks:
- The links to the Figma designs are just for the new input screens. 
- There are other views - project requirements, edit depth interval, and Soil Pit overview - that also need to be updated with these new inputs. I made some additional edits to those views as you'll see. 
- I also update Texture input to clarify Texture Class in light of the new percent clay input. 

Please take a look at all those designs and leave any comments.
